## Setup

In [4]:
import sys
sys.path.append('../../src/')


%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaylimit = 100
%config SqlMagic.named_parameters = "enabled"
%config SqlMagic.autocommit = True

# Banco em arquivo (persiste durante a sessão).
#%sql duckdb:///content/vigimed.duckdb
# Se preferir memória: 
%sql duckdb:///:memory:

#%run ../config/bootstrap.py
from utils import get_project_root
import duckdb
project_root = get_project_root() 
import sys
sys.path.append(project_root)

Connecting to 'duckdb:///:memory:'

## Atualizar a seção e abrir nova

In [5]:
%sql ROLLBACK;

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

## Criar as tabela e fazer as consultas

In [6]:
%%sql
DROP TABLE IF EXISTS dim_medicamentos;
CREATE TABLE dim_medicamentos AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_medicamentos/dim_medicamentos.parquet');

DROP TABLE IF EXISTS dim_atc;
CREATE TABLE dim_atc AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_atc/dim_atc.parquet');

DROP TABLE IF EXISTS dim_notificacoes;
CREATE TABLE dim_notificacoes AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_notificacoes/dim_notificacoes.parquet');

DROP TABLE IF EXISTS dim_soc;
CREATE TABLE dim_soc AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_soc/dim_soc.parquet');

DROP TABLE IF EXISTS fat_notificacoes_medicamentos;
CREATE TABLE fat_notificacoes_medicamentos AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_notificacoes_medicamentos');

DROP TABLE IF EXISTS fat_notificacoes_reacoes;
CREATE TABLE fat_notificacoes_reacoes AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_notificacoes_reacoes/fat_notificacoes_reacoes.parquet');

Running query in 'duckdb:///:memory:'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [Success]
Index: []

## ok  RELACAO_MEDICAMENTO_EVENTO

In [4]:
%%sql
SELECT RELACAO_MEDICAMENTO_EVENTO,count(*) as qt 
FROM dim_medicamentos
GROUP BY 1  
ORDER BY qt DESC
LIMIT 100;

Running query in 'duckdb:///:memory:'

   RELACAO_MEDICAMENTO_EVENTO      qt
0                           1  375585
1                           2  165566
2                           3    8689
3                           4    2047
4                           0    1000

CONFIRMAÇÃO QUE NONE É NULL

In [5]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE RELACAO_MEDICAMENTO_EVENTO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

## ficou para carol  DETENTOR_REGISTRO

In [6]:
%%sql
SELECT DETENTOR_REGISTRO,count(*) as qt 
FROM dim_medicamentos
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

         DETENTOR_REGISTRO      qt
0             DESCONHECIDO  427446
1  NOVARTIS SECTOR: PHARMA    8539
2                CRISTALIA    6456
3       INSTITUTO BUTANTAN    4572
4                   PFIZER    4259
5             PFIZER, INC.    3705
6                EUROFARMA    3063
7                    LIBBS    2816
8            NOT SPECIFIED    2724
9                   BIOGEN    2545

In [7]:
%%sql 

COPY (
SELECT DETENTOR_REGISTRO,count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
) TO 'detentor_list.csv' (HEADER, DELIMITER ',');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

CONFIRMAÇÃO QUE NONE É NULL

In [8]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE DETENTOR_REGISTRO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

## ficou para mel CONCENTRACAO

In [9]:
%%sql
SELECT CONCENTRACAO,count(*) as qt 
FROM dim_medicamentos
GROUP BY 1  
ORDER BY qt DESC
LIMIT 20;

Running query in 'duckdb:///:memory:'

    CONCENTRACAO      qt
0   DESCONHECIDO  460269
1          100MG    3328
2          500MG    3161
3             1G    2892
4        10MG/ML    1976
5         500 MG    1888
6           50MG    1656
7         100 MG    1636
8           10MG    1420
9        50MG/ML    1314
10          20MG    1248
11          40MG    1187
12        150 MG    1118
13          5 MG    1103
14         15 MG    1032
15         50 MG    1018
16       20MG/ML     938
17           5MG     937
18         300MG     905
19      10 MG/ML     897

CONFIRMANDO QUE NONE  É  NULL

In [10]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE CONCENTRACAO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

## ok COMPONENTE_SUSPEITO

In [11]:
%%sql
SELECT COMPONENTE_SUSPEITO,count(*) as qt 
FROM dim_medicamentos
GROUP BY 1  
ORDER BY qt DESC
LIMIT 50;

Running query in 'duckdb:///:memory:'

   COMPONENTE_SUSPEITO      qt
0                    0  496737
1                    1   55897
2                    2     127
3                    4      37
4                    5      32
5                    3      24
6                    7      11
7                    8       8
8                    6       7
9                    9       7

CONFIRMANDO QUE NONE  É  NULL

In [12]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE COMPONENTE_SUSPEITO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

## ok ACAO_ADOTADA

In [13]:
%%sql
SELECT ACAO_ADOTADA,count(*) as qt 
FROM dim_medicamentos
GROUP BY 1  
ORDER BY qt DESC
LIMIT 50;

Running query in 'duckdb:///:memory:'

   ACAO_ADOTADA      qt
0             0  346766
1             1   85273
2             2   55618
3             3   52568
4             4    8202
5             5    4460

CONFIRMAÇÃO QUE  NONE   É NULL

In [14]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE ACAO_ADOTADA IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

In [15]:
534294/552887

0.9663710667821815

## ok - LISTA- PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO

In [16]:

%%sql
SELECT PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,count(*) as qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 50;

Running query in 'duckdb:///:memory:'

,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,qt
0,[DESCONHECIDO],534294
1,[ERRO DE MEDICACAO],7995
2,[USO OFF-LABEL USO SEM REGISTRO],3411
3,[LOTES TESTADOS E DENTRO DAS ESPECIFICACOES],1296
4,[SUPERDOSE],921
5,[USO INCORRETO],918
6,"[ERRO DE MEDICACAO, USO INCORRETO]",834
7,"[ERRO DE MEDICACAO, USO OFF-LABEL USO SEM REGISTRO]",833
8,[ABUSO],468
9,[EXPOSICAO OCUPACIONAL],302
10,[],206
11,"[USO OFF-LABEL USO SEM REGISTRO, ERRO DE MEDICACAO]",194
12,"[ERRO DE MEDICACAO, USO INCORRETO, ABUSO]",143
13,"[USO INCORRETO, USO OFF-LABEL USO SEM REGISTRO]",128
14,"[LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, ERRO DE MEDICACAO]",77
15,"[SUPERDOSE, ERRO DE MEDICACAO]",72
16,[MEDICAMENTO TOMADO FORA DA DATA DE VALIDADE],69
17,"[USO INCORRETO, ABUSO]",52
18,[LOTES TESTADOS E FORA DAS ESPECIFICACOES],51
19,"[MEDICAMENTO TOMADO FORA DA DATA DE VALIDADE, ERRO DE MEDICACAO]",48
20,"[SUPERDOSE, ERRO DE MEDICACAO, USO INCORRETO, ABUSO]",38
21,[FALSIFICACAO],36
22,[MEDICAMENTO TOMADO PELO PAI],33
23,"[ERRO DE MEDICACAO, USO INCORRETO, USO OFF-LABEL USO SEM REGISTRO]",30
24,"[ERRO DE MEDICACAO, SUPERDOSE]",26
25,"[SUPERDOSE, ERRO DE MEDICACAO, USO OFF-LABEL USO SEM REGISTRO]",23
26,"[SUPERDOSE, USO INCORRETO, ABUSO]",19
27,"[SUPERDOSE, USO OFF-LABEL USO SEM REGISTRO]",18
28,"[SUPERDOSE, ABUSO]",17
29,"[ERRO DE MEDICACAO, ABUSO]",17
30,"[SUPERDOSE, LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, ERRO DE MEDICACAO]",15
31,"[ERRO DE MEDICACAO, MEDICAMENTO TOMADO FORA DA DATA DE VALIDADE]",14
32,"[SUPERDOSE, LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, USO INCORRETO]",13
33,"[FALSIFICACAO, ERRO DE MEDICACAO]",13
34,"[MEDICAMENTO TOMADO FORA DA DATA DE VALIDADE, ERRO DE MEDICACAO, USO INCORRETO]",12
35,"[FALSIFICACAO, ERRO DE MEDICACAO, USO INCORRETO, ABUSO]",12
36,"[USO OFF-LABEL USO SEM REGISTRO, USO INCORRETO]",12
37,"[SUPERDOSE, USO INCORRETO]",12
38,"[ABUSO, USO OFF-LABEL USO SEM REGISTRO]",11
39,"[USO INCORRETO, USO OFF-LABEL USO SEM REGISTRO, ERRO DE MEDICACAO]",11
40,"[FALSIFICACAO, USO INCORRETO, USO OFF-LABEL USO SEM REGISTRO]",10
41,"[LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, ERRO DE MEDICACAO, USO OFF-LABEL USO SEM REGISTRO]",10
42,"[LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, FALSIFICACAO]",10
43,"[USO INCORRETO, ERRO DE MEDICACAO]",9
44,"[USO INCORRETO, ABUSO, USO OFF-LABEL USO SEM REGISTRO]",8
45,"[USO OFF-LABEL USO SEM REGISTRO, SUPERDOSE]",8
46,"[USO OFF-LABEL USO SEM REGISTRO, MEDICAMENTO TOMADO FORA DA DATA DE VALIDADE, ERRO DE MEDICACAO]",7
47,"[LOTES TESTADOS E FORA DAS ESPECIFICACOES, ERRO DE MEDICACAO]",6
48,"[ABUSO, SUPERDOSE]",6
49,"[LOTES TESTADOS E DENTRO DAS ESPECIFICACOES, USO OFF-LABEL USO SEM REGISTRO]",6

In [17]:
%%sql

SELECT * FROM dim_medicamentos
WHERE PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO = 'SUPERDOSE|ERRO DE MEDICACAO|USO "OFF-LABEL" USO SEM REGISTRO' 
AND IDENTIFICACAO_NOTIFICACAO ='BR-ANVISA-300090408'

Running query in 'duckdb:///:memory:'

RuntimeError: (_duckdb.ConversionException) Conversion Error: Type VARCHAR with value 'SUPERDOSE|ERRO DE MEDICACAO|USO "OFF-LABEL" USO SEM REGISTRO' can't be cast to the destination type VARCHAR[]

LINE 2: WHERE PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO = 'SUPERDOSE|ERRO DE MEDICACAO|USO "OFF-LABEL" USO SEM REGISTRO...
                                                             ^
[SQL: SELECT * FROM dim_medicamentos
WHERE PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO = 'SUPERDOSE|ERRO DE MEDICACAO|USO "OFF-LABEL" USO SEM REGISTRO'
AND IDENTIFICACAO_NOTIFICACAO ='BR-ANVISA-300090408']
(Background on this error at: https://sqlalche.me/e/20/9h9h)

In [ ]:
%%sql

SELECT COUNT(*) FROM dim_medicamentos

Running query in 'duckdb:///:memory:'

   count_star()
0        552887

CONFIRMANDO  QUE NONE  É NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   534294

## ficou para sil INDICACAO_MEDDRA

In [8]:
%%sql

SELECT INDICACAO_MEDDRA,count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 100;

Running query in 'duckdb:///:memory:'

                                   INDICACAO_MEDDRA      qt
0                                      DESCONHECIDO  325534
1    USO DE MEDICAMENTO PARA INDICACAO DESCONHECIDA   19595
2         PRODUTO USADO PARA INDICACAO DESCONHECIDA   16515
3                                   DOENCA DE CROHN    6875
4                                ARTRITE REUMATOIDE    6207
5                                       HIPERTENSAO    4399
6                            PROFILAXIA DE COVID-19    4179
7                                ESCLEROSE MULTIPLA    4085
8                                  MIELOMA MULTIPLO    3449
9                          ESPONDILITE ANQUILOSANTE    3139
10                                   CANCER DE MAMA    3119
11                                              DOR    2982
12                                        ANALGESIA    2769
13                        NEOPLASIA MALIGNA DA MAMA    2694
14                                         DIABETES    2502
15                                         INFECCAO    2269
16                               ARTRITE PSORIATICA    2146
17                                       PROFILAXIA    2014
18                 PRE-MEDICACAO PARA QUIMIOTERAPIA    2000
19                                         PSORIASE    1821
20                                             ASMA    1791
21                                COLITE ULCERATIVA    1728
22                                        DEPRESSAO    1602
23                            PRESSAO ARTERIAL ALTA    1509
24                      CANCER DO COLON METASTATICO    1399
25                           TERAPIA ANTICOAGULANTE    1262
26                         IMUNIZACAO PARA COVID-19    1243
27                                        ANSIEDADE    1227
28                    CANCER COLORRETAL METASTATICO    1222
29                              TERAPIA ANTIBIOTICA    1179
30                       CANCER DE MAMA METASTATICO    1088
31                                      OSTEOPOROSE     997
32                         DIABETES MELLITUS TIPO 2     994
33                                                |     984
34                                      MALARIA SOE     983
35                       TOMOGRAFIA COMPUTADORIZADA     981
36                                        EPILEPSIA     915
37                                          SEDACAO     847
38                                        CONVULSAO     833
39                                        PNEUMONIA     818
40                           INSUFICIENCIA CARDIACA     791
41                                        ANESTESIA     774
42                                  HIPOTIREOIDISMO     765
43                    CANCER METASTATICO COLORRETAL     747
44                              LINFOMA NAO-HODGKIN     738
45                             HIPERTENSAO ARTERIAL     736
46                                    ESQUIZOFRENIA     719
47                   CANCER DE MAMA TRIPLO-NEGATIVO     711
48                          CARCINOMA HEPATOCELULAR     692
49                                  DOENCA DE FABRY     688
50                                          INSONIA     656
51                                           NAUSEA     648
52                      FIBROSE PULMONAR IDIOPATICA     611
53                      LUPUS ERITEMATOSO SISTEMICO     602
54                                DIABETES MELLITUS     602
55                                     CONTRACEPCAO     583
56                                FIBRILACAO ATRIAL     567
57                                    PRE-MEDICACAO     557
58                                    QUIMIOTERAPIA     549
59                                         COVID-19     547
60              LINFOMA DIFUSO DE GRANDES CELULAS B     523
61                                        NEOPLASIA     516
62                               DISTURBIO CARDIACO     510
63                                       COLESTEROL     508
64                       IMUNIZACAO CONTRA COVID-19     505
65                       CARCINOMA DA MAMA INVASIVO     494
66                                           ANEMIA     477
67                    EXAME DE IMAGEM COM CONTRASTE     465
68                       NEOPLASIA MALIGNA DO COLON     460
69                            VACINACAO PROFILATICA     453
70                     LEUCEMIA LINFOCITICA CRONICA     447
71                            RETOCOLITE ULCERATIVA     422
72                                         GLAUCOMA     408
73                                 CONTROLE DO PESO     402
74                        LEUCEMIA MIELOIDE CRONICA     396
75                     CANCER DE MAMA HER2-POSITIVO     393
76                                         ARRITMIA     388
77                                  IMUNOSSUPRESSAO     386
78                                NEOPLASIA DA MAMA     386
79                                DISTURBIO DO SONO     377
80                                EFEITO ANALGESICO     371
81                              DOENCA DE PARKINSON     371
82                                DERMATITE ATOPICA     363
83               HEMOGLOBINURIA PAROXISTICA NOTURNA     358
84                     URTICARIA CRONICA ESPONTANEA     347
85                         CANCER RETAL METASTATICO     342
86                                CANCER COLORRETAL     334
87                         PRESSAO ARTERIAL ANORMAL     328
88                   IMUNIZACAO CONTRA FEBRE DENGUE     327
89                          LEUCEMIA MIELOIDE AGUDA     323
90                            DISTURBIO DA TIREOIDE     321
91  TRANSTORNO DE DEFICIT DE ATENCAO-HIPERATIVIDADE     317
92                                       IMUNIZACAO     314
93                      NEOPLASIA MALIGNA DO OVARIO     308
94                                     DISLIPIDEMIA     298
95         CANCER DO PULMAO DE CELULAS NAO PEQUENAS     297
96                               ANESTESIA ESPINHAL     292
97                                            FEBRE     279
98                                      TUBERCULOSE     279
99                                         TROMBOSE     277

CONFIRMANDO QUE NONE  É NULL

In [9]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE INDICACAO_MEDDRA IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0        0

COPIAR PARA  CSV

In [10]:
%%sql 

COPY (
SELECT INDICACAO_MEDDRA,count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
) TO 'indicacao_meddra.csv' (HEADER, DELIMITER ',');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

## INDICACAO_RELATADA_NOTIFICADOR_INICIAL

In [ ]:
%%sql
SELECT INDICACAO_RELATADA_NOTIFICADOR_INICIAL, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

      INDICACAO_RELATADA_NOTIFICADOR_INICIAL      qt
0                                       None  315982
1        PRODUCT USED FOR UNKNOWN INDICATION   11420
2            DRUG USE FOR UNKNOWN INDICATION    6094
3                         ARTRITE REUMATOIDE    3424
4                            DOENCA DE CROHN    3213
5                                   DIABETES    3030
6                                HIPERTENSAO    2904
7  PRODUTO USADO PARA INDICACAO DESCONHECIDA    1925
8                   ESPONDILITE ANQUILOSANTE    1687
9                         MULTIPLE SCLEROSIS    1663

CONFIRMANDO  QUE NONE É NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE INDICACAO_RELATADA_NOTIFICADOR_INICIAL IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   315982

## ficou para mel NUMERO_LOTE

In [ ]:
%%sql
SELECT NUMELO_LOTE, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

         NUMELO_LOTE      qt
0               None  385104
1       DESCONHECIDO   11823
2      NAO INFORMADO    5603
3                 NI    5187
4            UNKNOWN    2907
5  ASKED BUT UNKNOWN     705
6                UNK     540
7       DESCONHECIDA     537
8           IGNORADO     515
9           4120Z005     303

CONFIRMANDO NONE = NULL

In [ ]:
%%sql
COPY (
    SELECT 
        NUMELO_LOTE, 
        count(*) AS qt
    FROM 
        dim_medicamentos
    GROUP BY 
        1
    ORDER BY 
        qt DESC
) 
TO 'relatorio_lotes_duckdb.csv' (HEADER, DELIMITER ';');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE NUMELO_LOTE IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   385104

## ficou para mel DOSE

In [ ]:
%%sql
SELECT DOSE, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
limit 10;

Running query in 'duckdb:///:memory:'

                   DOSE      qt
0                  None  339554
1    100 MILLIGRAM (MG)   10204
2     50 MILLIGRAM (MG)    9612
3     10 MILLIGRAM (MG)    8231
4    300 MILLIGRAM (MG)    7323
5  1 DOSAGE FORM ({DF})    6812
6     20 MILLIGRAM (MG)    6795
7     40 MILLIGRAM (MG)    6051
8    500 MILLIGRAM (MG)    5743
9            1 GRAM (G)    5266

CONFIRMANDO NONE = NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE DOSE IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   339554

## ficou para mel FREQUENCIA_DOSE

In [13]:
%%sql
SELECT FREQUENCIA_DOSE, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  FREQUENCIA_DOSE      qt
0    DESCONHECIDO  382662
1           1 DIA   34451
2     1 POR 1 DIA   16549
3               1    8122
4         12 HORA    6179
5         CICLICO    5583
6           TOTAL    5109
7   2 POR 12 HORA    4604
8           1 MES    3992
9        8 SEMANA    3903

CONFIRMANDO NONE = NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE FREQUENCIA_DOSE IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0     3583

## ficou para mel DURACAO

In [14]:
%%sql
SELECT DURACAO, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 50;

Running query in 'duckdb:///:memory:'

         DURACAO      qt
0   DESCONHECIDO  473049
1          1 DIA   20933
2          2 DIA    4107
3          3 DIA    3079
4         1 HORA    2959
5          5 DIA    2485
6       1 MINUTO    2274
7          4 DIA    2253
8      30 MINUTO    2101
9          7 DIA    1878
10        2 HORA    1577
11         6 DIA    1501
12         0 DIA    1404
13         8 DIA    1261
14        10 DIA    1105
15      5 MINUTO    1070
16     10 MINUTO    1058
17         9 DIA     843
18     20 MINUTO     757
19        15 DIA     719
20     15 MINUTO     718
21        11 DIA     709
22        3 HORA     693
23        14 DIA     651
24        12 DIA     577
25     60 MINUTO     576
26         1 ANO     576
27        22 DIA     563
28         1 MES     554
29         3 MES     550
30         2 MES     544
31        13 DIA     512
32        4 HORA     472
33     90 MINUTO     439
34        21 DIA     378
35         2 ANO     374
36        16 DIA     373
37     40 MINUTO     339
38         6 MES     334
39       24 HORA     334
40        20 DIA     319
41        30 DIA     311
42         5 MES     310
43      2 MINUTO     310
44         4 MES     289
45        17 DIA     282
46        19 DIA     261
47        23 DIA     259
48         3 ANO     257
49        5 HORA     249

CONFIRMANDO  NONE =  NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE DURACAO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   473049

## ok INICIO_ADMINISTRACAO

In [ ]:
%%sql
SELECT INICIO_ADMINISTRACAO, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  INICIO_ADMINISTRACAO      qt
0                  NaT  331918
1           2020-01-01     546
2           2020-01-02     423
3           2022-01-01     410
4           2021-01-01     410
5           2021-07-07     376
6           2019-01-01     356
7           2021-06-01     349
8           2023-01-01     342
9           2021-01-21     316

CONFIRMANDO NAT= NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE INICIO_ADMINISTRACAO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   331918

##  ok FIM_ADMINISTRACAO

In [ ]:
%%sql
SELECT FIM_ADMINISTRACAO, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  FIM_ADMINISTRACAO      qt
0               NaT  410120
1        2020-01-02     232
2        2024-01-02     195
3        2020-01-01     191
4        2021-07-07     187
5        2021-05-19     184
6        2021-05-05     172
7        2023-02-28     169
8        2023-01-02     166
9        2021-01-02     166

CONFIRMANDO  NAT= NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE FIM_ADMINISTRACAO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   410120

## FORMA_FARMACEUTICA

In [ ]:
%%sql
SELECT FORMA_FARMACEUTICA, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

                                                  FORMA_FARMACEUTICA      qt
0                                                               None  400411
1                                                  SOLUCAO INJETAVEL   20974
2                                                         COMPRIMIDO   14599
3                                                             TABLET   11193
4                                                             AMPOLA   10271
5                                                          INJETAVEL    9670
6                                             SOLUTION FOR INJECTION    9399
7                                                 FILM-COATED TABLET    4434
8                                                            SOLUCAO    4393
9                                                      FRASCO AMPOLA    3856
10                             CONCENTRATE FOR SOLUTION FOR INFUSION    2949
11                                             SOLUTION FOR INFUSION    2884
12                                                           UNKNOWN    2630
13                                              SOLUCAO PARA INFUSAO    2193
14                                                         INJECTION    1795
15                                                    PO LIOFILIZADO    1769
16                                                            FRASCO    1683
17                                                           CAPSULA    1649
18                                                           LIQUIDA    1520
19                                                           CAPSULE    1221
20                                              SOLUCAO PARA INJECAO    1100
21                                               SUSPENSAO INJETAVEL    1094
22                                              COMPRIMIDO REVESTIDO    1011
23                                                               FAP     967
24                                         PO PARA SOLUCAO INJETAVEL     965
25                                                           LIQUIDO     943
26                                             CANETA PRE-PREENCHIDA     897
27                                      INTRAUTERINE DELIVERY SYSTEM     890
28                                                     FRASCO-AMPOLA     878
29                                                           SOL INJ     798
30                                                INFUSION, SOLUTION     767
31                                                                PO     761
32                                                      SOLUCAO ORAL     663
33                          SOLUTION FOR INJECTION IN PRE-FILLED PEN     662
34                      SOLUTION FOR INJECTION IN PRE-FILLED SYRINGE     606
35                     POWDER AND SOLVENT FOR SOLUTION FOR INJECTION     603
36                                         PROLONGED-RELEASE CAPSULE     594
37                                                        PO LIOFILO     587
38                             PO LIOFILIZADO PARA SOLUCAO INJETAVEL     585
39                  POWDER FOR CONCENTRATE FOR SOLUTION FOR INFUSION     573
40                                              PO LIOFILO INJETAVEL     561
41                                             PO PARA USO INJETAVEL     506
42                                                     COATED TABLET     482
43                           SOLUCAO INJETAVEL EM SERINGA PREENCHIDA     473
44                                                                CP     472
45                      INJECTION, POWDER, LYOPHILIZED, FOR SOLUTION     467
46                                  POWDER FOR SOLUTION FOR INFUSION     451
47                                                             BOLSA     435
48                                                     CAPSULE, HARD     425
49                                                     FRASCO/AMPOLA     412
50                                                      CAPSULA DURA     407
51                                                           INJECAO     390
52                                      PO PARA SOLUCAO PARA INFUSAO     361
53                                                       COMPRIMIDOS     350
54                                                                EV     349
55                                               EYE DROPS, SOLUTION     315
56                                               SOLUCAO INTRAVENOSA     305
57                                            COMPRIMIDOS REVESTIDOS     287
58                                                      DESCONHECIDO     267
59                                                                FA     264
60                                                     NAO INFORMADO     254
61                                                        ENDOVENOSA     248
62                                                     SOL.INJETAVEL     246
63                                 POWDER FOR SOLUTION FOR INJECTION     236
64                                                           SERINGA     230
65                                           MODIFIED-RELEASE TABLET     226
66                                                         SUSPENSAO     222
67                                               UNKNOWN FORMULATION     215
68                                                      PO INJETAVEL     213
69                                                           TABLETS     213
70                                                            SOLIDA     201
71                                                          INFUSION     190
72                                  INFUSION AMPOULES, VIALS/BOTTLES     186
73                   POWDER AND SOLVENT FOR SUSPENSION FOR INJECTION     184
74                                                         EYE DROPS     183
75                             CONCENTRADO PARA SOLUCAO PARA INFUSAO     178
76                                                                FR     175
77                                                            XAROPE     173
78                                                      DESCONHECIDA     169
79                                                SOLUCAO ENDOVENOSA     164
80                                                 INHALATION POWDER     151
81                                                          AMPOULES     151
82                              INFUSION AMPOULES, DRY VIALS/BOTTLES     147
83                    SOLUCAO PARA INJECAO EM SERINGA PRE-PREENCHIDA     145
84                                                    SUSPENSAO ORAL     142
85                           PO LIOFILIZADO PARA SUSPENSAO INJETAVEL     139
86                                                   ORAL SUSPENSION     138
87                                                SERINGA PREENCHIDA     133
88                                              ADESIVO TRANSDERMICO     129
89                                            PO PARA RECONSTITUICAO     128
90                                                               INJ     122
91                                                             GOTAS     119
92                                                               AMP     115
93                                                          IMPLANTE     114
94                                                  ACIDO GADOTERICO     114
95                                          SUSPENSION FOR INJECTION     107
96                                                           INHALER     107
97                                                        ENDOVENOSO     106
98                                                   PO PARA SOLUCAO     105
99                                                             VIALS     102
100                                                       VIALS, DRY     101
101                                                TRANSDERMAL PATCH     100
102                                           SUSPENSAO PARA INJECAO      99
103                                  INHALATION POWDER, HARD CAPSULE      97
104                                         PROLONGED-RELEASE TABLET      97
105                           SOLUCAO INJETAVEL EM CANETA PREENCHIDA      96
106                       SOLUCAO PARA INJECAO EM SERINGA PREENCHIDA      94
107                                                     ANEL VAGINAL      94
108                                                         CAPSULAS      93
109                                                      INTRAVENOSA      93
110                                                               IV      93
111                   SUSPENSION FOR INJECTION IN PRE-FILLED SYRINGE      92
112                                                             ORAL      92
113                                                       IOBITRIDOL      91
114                               SOLUCAO PRESSURIZADA PARA INALACAO      87
115                                                         SOL. INJ      87
116                                             COATED TABLETS, FILM      86
117                                                          INFUSAO      81
118                                                         CARTUCHO      80
119                               COMPRIMIDO DE LIBERACAO MODIFICADA      80
120                                        INJETAVEL - FRASCO AMPOLA      79
121                                                    CAPSULE, SOFT      79
122                                                           DRAGEA      78
123                         GASTRO-RESISTANT TABLET TABLET CONTR REL      78
124                                    FRASCO AMPOLA- PO LIOFILIZADO      73
125                                                  INHALANT POWDER      72
126                                             ORAL DROPS, SOLUTION      71
127                                               COMPRIMIDO SIMPLES      70
128                                               VIALS, INTRAVENOUS      70
129                                                          ADESIVO      68
130                                                          COLIRIO      67
131                               SOLUCAO PARA DILUICAO PARA INFUSAO      67
132                                             POWDER FOR INJECTION      65
133                                                      SPRAY NASAL      65
134                                                SOLUCAO OFTALMICA      65
135                                                LIQUIDO INJETAVEL      64
136                                                         CAPSULES      63
137                                                              GEL      62
138                                                            SYRUP      60
139                                           PRESSURISED INHALATION      58
140                                      PO PARA SUSPENSAO INJETAVEL      58
141                                                         AEROSSOL      58
142                               PRESSURISED INHALATION, SUSPENSION      57
143                                                   SOL. INJETAVEL      57
144                                FRASCO AMPOLA - SOLUCAO INJETAVEL      55
145                                                  COMPRIMIDO ORAL      55
146                                                            CREME      55
147                                            EYE DROPS, SUSPENSION      55
148                             PO E SOLVENTE PARA SOLUCAO INJETAVEL      53
149                                   COMPRIMIDO REVESTIDO POR FILME      53
150                                                              F/A      52
151                                        PO P/ SUSPENSAO INJETAVEL      52
152                                SOLUCAO INJETAVEL PRONTA PARA USO      51
153                                COMPRIMIDO REVESTIDO POR PELICULA      51
154                                               SOLUCAO INJETAVEL.      50
155                                                   FRASCO- AMPOLA      50
156                                                              F.A      50
157                                 SOLUCAO CONCENTRADA PARA INFUSAO      49
158                                            AMPOULES, INTRAVENOUS      49
159                                                 SOLUCAO AEROSSOL      49
160                                                           POMADA      48
161                                                            SPRAY      47
162                                                    SOL INJETAVEL      46
163                                                EMULSAO INJETAVEL      46
164                                                  PO PARA INJECAO      45
165                               COMPRIMIDO DE LIBERACAO PROLONGADA      45
166                                                       SUSPENSION      45
167                                                            DROPS      45
168                                                         OINTMENT      45
169                                            INHALANT, PRESSURISED      44
170                                                       ORAL DROPS      44
171                                                      NASAL SPRAY      43
172                                                      INTRAVENOSO      43
173                                                 PO PARA INALACAO      42
174                                                          AMPOLAS      42
175                                           AEROSOL FOR INHALATION      41
176                      SOLUCAO INJETAVEL EM SERINGA PRE-PREENCHIDA      40
177                                                             COMP      39
178                                                      SUPOSITORIO      39
179                                               NEBULISER SOLUTION      39
180                                                              SOL      39
181                                                          AEROSOL      39
182                                                         PILLULES      38
183                                                  PO LIOFILIZAVEL      38
184                                         PO LIOFILIZADO INJETAVEL      37
185                                                    ORAL SOLUTION      37
186                                                  FRASCO / AMPOLA      37
187                                                            SACHE      36
188                                            SOLUCAO PARA INALACAO      36
189                                       POWDER FOR ORAL SUSPENSION      35
190                                      CAPSULAS DE LIBERACAO LENTA      35
191                                       CAPSULA DE LIBERACAO LENTA      35
192                                                           SOLIDO      34
193                             COMPRIMIDO COM REVESTIMENTO ENTERICO      34
194                    SOLUCAO PARA INJECAO EM CANETA PRE-PREENCHIDA      33
195                                                           CP REV      33
196                                                     LIQUIDO ORAL      30
197                                                        PO INJ FA      30
198                                                               AP      30
199                                                         VIA ORAL      30
200                                            SOLUCAO PARA DILUICAO      30
201                              AMPOLAS DE INFUSAO, FRASCOS/FRASCOS      30
202                                                           CANETA      29
203                                             PO SOLUCAO INJETAVEL      29
204                                                               VO      28
205                                                  FRASCO - AMPOLA      27
206                                                        IOPROMIDA      27
207                                            INJECAO INTRAMUSCULAR      27
208                     SERINGA PRE-PREENCHIDA COM SOLUCAO INJETAVEL      27
209                                                         GRANULES      27
210                                                         SOLUTION      27
211                                         CONCENTRADO PARA INFUSAO      27
212                                                           2,5 MG      26
213                                        SOLUCAO ESTERIL INJETAVEL      26
214                                                    SOLUCAO GOTAS      26
215                                                            CREAM      26
216                                               SOLUCAO ORAL GOTAS      26
217                                            FRASCOS, INTRAVENOSOS      26
218                          PO E SOLVENTE PARA SOLUCAO PARA INFUSAO      25
219                                                   COATED TABLETS      24
220                                                             FAMP      24
221                                 PRE FILLED SYRINGES, INTRAVENOUS      24
222                                                   FRASCO/ AMPOLA      24
223                       SOLUCAO INJETAVEL EM CANETA PRE-PREENCHIDA      24
224                                                   QUIMIOTERAPICA      24
225                            SOLUCAO INJETAVEL EM CANETA PRE-CHEIA      24
226                                        COMPRIMIDO ORODISPERSIVEL      23
227                                              INJECTION, SOLUTION      23
228                                                       INJETAVEL.      23
229                         SOLUCAO INJECTAVEL EM SERINGA PREENCHIDA      23
230                                                         SUSP INJ      22
231                                                         ENVELOPE      22
232                                          PO P/ SOLUCAO INJETAVEL      22
233                                                              CAP      21
234                                                    PO INALATORIO      21
235                          BRUKINSA (ZANUBRUTINIBE) CAPSULA, 80 MG      21
236                                   SOLUCAO PARA INJECAO / INFUSAO      21
237                                       SOLUCAO INJETAVEL - AMPOLA      21
238                     COMPRIMIDO REVESTIDO DE LIBERACAO PROLONGADA      21
239                                                COMPRIMIDO 600 MG      21
240                                              SPRAY (UNSPECIFIED)      21
241                                                  PRONTA PARA USO      21
242                                                          FRASCOS      21
243                                                   PO LIOF INJ FA      20
244                                            COMPRIMIDO MASTIGAVEL      20
245                                                           200 MG      20
246                                               SOLUCAO PARENTERAL      20
247                                   GASTRO-RESISTANT COATED TABLET      19
248                                            COMPRIMIDO SUBLINGUAL      19
249                                      PO PARA INFUSAO INTRAVENOSA      19
250                               PO LIOFILIZADO PARA RECONSTITUICAO      18
251                                                        COMPRIMDO      18
252                                                        FR AMPOLA      18
253                                                 AMPOLA INJETAVEL      18
254                                                   FRANSCO/AMPOLA      18
255                                                 PO PARA DILUICAO      18
256                                               INJECAO SUBCUTANEA      18
257                                                       INTRATECAL      18

In [ ]:
%%sql

COPY(
SELECT FORMA_FARMACEUTICA, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC
)
TO 'forma_farm.csv' (HEADER, DELIMITER ',');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

CONFIRMANDO NONE = NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE FORMA_FARMACEUTICA IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   400411

## VIA_ADMINISTRACAO

In [7]:
%%sql
SELECT VIA_ADMINISTRACAO, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

                                                 VIA_ADMINISTRACAO      qt
0                                                     DESCONHECIDO  307548
1                                                             ORAL   43987
2                                              INFUSAO INTRAVENOSA   26438
3                                                    INTRAMUSCULAR   20872
4                                                     DESCONHECIDA   18940
5                                   INTRAVENOSA (NAO ESPECIFICADO)   18495
6                                                               EV   14144
7                                                          UNKNOWN   11536
8                                                       ENDOVENOSA   10601
9                                                       SUBCUTANEA    9775
10                                      E2B R2 CODE: 065 - UNKNOWN    9741
11                                                     INTRAVENOSA    9411
12                                                      ENDOVENOSO    4687
13                                                              IV    4263
14                                                 VIA INTRAVENOSA    3776
15                                                        VIA ORAL    2932
16                                                        ORAL USE    2735
17                                        E2B R2 CODE: 050 - OTHER    2589
18                           INTRAVENOUS (NOT OTHERWISE SPECIFIED)    2410
19                                               BOLUS INTRAVENOSO    2165
20                                                              VO    1656
21                                                     INTRAVENOSO    1648
22                                                      INTRATECAL    1403
23                                                      IV INFUSAO    1158
24                                                           OUTRA     952
25                                                             EVI     925
26                                                   NAO INFORMADO     910
27                                                    SUBCUTANEOUS     892
28                                                 INTRAVENOUS USE     814
29                                                   INTRA-UTERINE     552
30                                                         CUTANEA     535
31                                                SUBCUTANEOUS USE     530
32                                          REPIRATORIA (INALACAO)     504
33                                                       INJETAVEL     489
34                               INJECTION NOT OTHERWISE SPECIFIED     447
35                                        RESPIRATORY (INHALATION)     428
36                                                       IV DIRETO     375
37                                                              SC     374
38                                                    INTRAUTERINA     354
39                                                  VIA ENDOVENOSA     345
40                                                          VENOSA     336
41                                                       OFTALMICA     330
42                                                     INTRAVENOUS     324
43                                                          TOPICA     270
44                                                           NASAL     256
45                                                VIA INTRAVENOSA.     254
46                                               SONDA NASOENTERAL     253
47                                                    TRANSDERMICA     220
48                                                        EPIDURAL     203
49                                                  VIA SUBCUTANEA     201
50                                                      SUBCUTANEO     192
51                             UNKNOWN, E2B R2 CODE: 065 - UNKNOWN     191
52                                                              IM     185
53                                                           IVBIC     162
54                                                     EM BOLUS EV     155
55                                                         VAGINAL     154
56                                                              NI     150
57                                                      SUBLINGUAL     143
58                                               INTRAMUSCULAR USE     136
59                                                           OTHER     134
60                                                      INALATORIA     119
61                                                      SUBDERMICA     114
62                                                  INTRACAVERNOSA     107
63                                                 INALATORIA ORAL     101
64                                                  VIA SUBDERMICA      99
65                                                      OCULAR USE      98
66                                                   TRANPLACENTAL      96
67                                                         INFUSAO      96
68                                              VIA GASTROENTERICA      94
69                                                  VIA INALATORIA      92
70                                                      OPHTHALMIC      91
71                                                          VENOSO      91
72                                           VIA SONDA NASOENTERAL      87
73                                                      INALATORIO      87
74                                                          TOPICO      86
75                                                     INTRAOCULAR      77
76                                                VIA DESCONHECIDA      76
77                                                 INTRA-ARTICULAR      75
78                                                             E.V      72
79                                                           RETAL      72
80                        DESCONHECIDO, E2B R2 CODE: 065 - UNKNOWN      70
81                                                              SL      66
82                                        INJECAO NAO ESPECIFICADA      63
83                                                       PERIDURAL      62
84                                                    INTRADERMICA      61
85                                                  INHALATION USE      60
86                                                         INJECAO      57
87                                               VIA INTRAMUSCULAR      56
88                                                      PARENTERAL      56
89                                                          OCULAR      55
90                                                         ENTERAL      53
91                                                             SNE      53
92                                                  VIA INTRATECAL      52
93                             INJETAVEL, E2B R2 CODE: 050 - OTHER      46
94                                                  TRANSPLACENTAL      44
95                                              SONDA NASOENTERICA      44
96                                                    TRANSDERMICO      43
97                                         GOTEJAMENTO INTRAVENOSO      40
98                                              SONDA NASOGASTRICA      39
99                                                            E.V.      39
100                                                            EVB      38
101                                                       INALACAO      37
102                                                     RAQUIDIANA      36
103                                                    ENDOVENOSA.      35
104                      NAO INFORMADO, E2B R2 CODE: 065 - UNKNOWN      35
105                                                   TRANSMAMARIA      34
106           INJECAO NAO ESPECIFICADA, E2B R2 CODE: 065 - UNKNOWN      34
107                                                   GASTROSTOMIA      33
108                                       MEMBRO SUPERIOR ESQUERDO      33
109                                                    NASOENTERAL      32
110                                                  NAO INFORMADA      31
111                                               VIA GASTROSTOMIA      30
112                                                          BUCAL      29
113                                                            V.O      29
114                                                      VIA ORAL.      29
115                                                        TOPICAL      28
116                                                           I.V.      27
117                                                             IT      27
118                                                           IVBC      27
119                        GASTROENTERAL, E2B R2 CODE: 050 - OTHER      25
120                                                      VIA SONDA      25
121                                        MEMBRO SUPERIOR DIREITO      24
122                                                     INTAVENOSA      24
123                                                 INTRA-ARTERIAL      24
124                                          INALACAO RESPIRATORIA      23
125                                                   INTRA-VENOSA      22
126                  INTRAVENOSO (NAO ESPECIFICADO DE OUTRA FORMA)      22
127                                                            SNG      22
128                                                    INTRAVITREA      21
129                                                      VIA NASAL      21
130                                                USO INTRAVENOSO      21
131                                                           0108      21
132                                                    HEMODIALISE      21
133                                              INTRAVENOUS BOLUS      19
134                                                 USO INALATORIO      19
135                                                            I.V      18
136                                                  SONDA ENTERAL      18
137                                                     SUBDERMICO      18
138                                                     INHALATION      18
139                                                 BRACO ESQUERDO      18
140                                                   VIA EPIDURAL      17
141                                                     INTRANASAL      16
142                                      INTRAVENOSA OU SUBCUTANEA      16
143                                                    SUB CUTANEA      16
144                                                          SONDA      16
145                                                        CAPILAR      16
146                                                   INTRAVESICAL      15
147                                               TRANSPLACENTARIA      15
148                                                   INTRA VENOSA      15
149                                                     OROFARINGE      15
150                                 ADMINISTRADO NO BRACO ESQUERDO      14
151                                                       EV BOLUS      14
152                                              INALATORIO (ORAL)      14
153                                               VIA TRANSDERMICA      14
154                                         VIA SONDA NASOENTERICA      14
155                                 ADMINISTRADA NO BRACO ESQUERDO      14
156                                                     ENDEVENOSA      13
157                                                         DENTAL      13
158                                                      AURICULAR      13
159                                                 RAQUIANESTESIA      13
160                                                INALATORIO ORAL      13
161                                               INTRARRAQUIDIANA      13
162                                        INTRATECAL (RAQUIDIANA)      13
163                                                             CP      13
164                                                      VIA RETAL      13
165                                                 USO SUBCUTANEO      13
166                                                         AMPOLA      13
167                                                  BRACO DIREITO      12
168                                            INALATORIO VIA ORAL      12
169                                                    INTRA-NASAL      12
170                                             SONDA NASO ENTERAL      12
171                                            USO INALATORIO ORAL      12
172                     NASOGASTRIC TUBE, E2B R2 CODE: 050 - OTHER      12
173                                                             VS      12
174                                      BOMBA DE INFUSAO CONTINUA      11
175                       INTRAVENOSA (SEM MAIORES ESPECIFICACOES)      11
176                                                VIA ENDOVENOSA.      11
177                                                            GTT      11
178                                                       INALADOR      11
179                                    USO INALATORIO POR VIA ORAL      11
180                                               VIA INTRAVESICAL      11
181                                                            SOG      11
182                                                  INTRAVASCULAR      10
183                                                  SUBARACNOIDEA      10
184                                                  INTRACEREBRAL      10
185                                                   SUBARACNOIDE      10
186                                                            IVD      10
187                                              SOLUCAO INJETAVEL      10
188                                                      ENDOVENSO      10
189                                                             VE      10
190                                                      NASAL USE       9
191                                              SONDA OROGASTRICA       9
192                                                    INTRAVEMOSO       9
193                                                   ENDOTRAQUEAL       9
194                                                 HIPODERMOCLISE       9
195                                                    INTROVENOSA       9
196                                                       ESPINHAL       9
197                                                          BOLUS       9
198                                                  SUBCONJUNTIVA       9
199                                                     VIA OCULAR       8
200                                  ADMINISTRADA NO BRACO DIREITO       8
201                                                           V.O.       8
202                                                       IGNORADO       8
203                                                  VIA OFTALMICA       8
204                                                     ENVOVENOSA       8
205                                                    INTRATHECAL       8
206                                                   NASOGASTRICA       8
207                                                 VIA SUBLINGUAL       8
208                                                       USO ORAL       8
209                                                INTRAPERITONEAL       7
210                                       ORAL FORMULATION: TABLET       7
211                                                   ENDOCERVICAL       7
212                                               BOMBA DE INFUSAO       7
213                                                  INTRATRAQUEAL       7
214                                                     ENDEVENOSO       7
215                                                  USO OFTALMICO       7
216                                            SOLUCAO INTRAVENOSA       7
217                                               INFUSAO CONTINUA       7
218                                    S.N.E. (SONDA NASOENTERICA)       7
219                                               INTRAVENOUS DRIP       7
220                                                      OTOLOGICA       7
221                                         VIA INTRAVENOSA DIRETA       7
222                                  ADMINISTRADO NO BRACO DIREITO       6
223                                                     ENDOVESONA       6
224                                               SONDA OROGATRICA       6
225                                             VIA INTRA-ARTERIAL       6
226                                                             R2       6
227                                               TRANSPLACENTARIO       6
228                                                          RAQUI       6
229                                                      OTOLOGICO       6
230                                                             IN       6
231                                                INTRATHECAL USE       6
232                                                      OFTALMICO       6
233                                                     VIA TOPICA       6
234                                           INTRAVENOSA EM BOLUS       6
235                                               INTRAVENOSA (IV)       6
236                                                   INTRAVENOSSA       6
237                                         VIA SONDA NASOGASTRICA       6
238                                                     INFUSAO EV       6
239                                                            BIC       6
240                                                      ENDOENOSA       6
241                                                    ENDO VENOSO       6
242                                                     COMPRIMIDO       6
243                                          USO INALATORIO (ORAL)       5
244                                                VIA NASOENTERAL       5
245                                                INF INTRAVENOSA       5
246                                                        IM / EV       5
247                                                  GASTROENTERAL       5
248                                                          LOCAL       5
249                                                ORAL INHALATION       5
250                          INTRAVENOSO (SEM OUTRA ESPECIFICACAO)       5
251                                             INFUSAO ENDOVENOSA       5
252                                                   ENDOVENOSO .       5
253                                          RESPIRACAO INALATORIA       5
254                                     SONDA NASOGASTRICA ENTERAL       5
255                                                VIA INTRAVENOSO       5
256                                                 NAO PERGUNTADO       5
257                                                 INTRA MUSCULAR       5
258                                                    VIA ENTERAL       5
259                  RESPIRATORY (INHALATION) FORMULATION: AEROSOL       5
260                                                   INTRAVENOSO.       5
261                                               BOLUS ENDOVENOSO       5
262                                                    INTARVENOSA       5
263                                                    SONDA (SNE)       5
264                                               VIA SONDAENTERAL       4

CONFIRMANDO NONE =  NULL

In [ ]:
%%sql

COPY (
    SELECT VIA_ADMINISTRACAO, count(*) AS qt
    FROM dim_medicamentos
    GROUP BY 1
    ORDER BY qt DESC
) TO 'via_admin.csv' (HEADER, DELIMITER ',');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE VIA_ADMINISTRACAO IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   307203

## OK VIA_ADMINISTRACAO_MAE_PAI

In [23]:
%%sql
SELECT VIA_ADMINISTRACAO_MAE_PAI_VALOR, count(*) AS qt
FROM dim_medicamentos
GROUP BY 1
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

  VIA_ADMINISTRACAO_MAE_PAI_VALOR      qt
0                    DESCONHECIDO  552815
1                            ORAL      31
2                INTRAVENOSA (IV)      20
3                 SUBCUTANEA (SC)      13
4              INTRAMUSCULAR (IM)       3
5                    RESPIRATORIA       2
6                   INTRACEREBRAL       2
7                    INTRAUTERINA       1

CONFIRMANDO NONE = NULL

In [ ]:
%%sql
SELECT COUNT(*) AS qt_null
FROM dim_medicamentos
WHERE VIA_ADMINISTRACAO_MAE_PAI IS NULL;

Running query in 'duckdb:///:memory:'

   qt_null
0   552748

## TESTE  VARIAVEL POSOLOGIA

In [ ]:
%%sql
SELECT DOSE, FREQUENCIA_DOSE, FORMA_FARMACEUTICA, VIA_ADMINISTRACAO, DURACAO, POSOLOGIA
FROM fat_notificacoes_medicamentos
WHERE DOSE IS NOT NULL
  AND FREQUENCIA_DOSE IS NOT NULL
  AND FORMA_FARMACEUTICA IS NOT NULL
  AND VIA_ADMINISTRACAO IS NOT NULL
  AND DURACAO IS NOT NULL
  AND POSOLOGIA IS NOT NULL
LIMIT 15;

Running query in 'duckdb:///:memory:'

,DOSE,FREQUENCIA_DOSE,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,DURACAO,POSOLOGIA
0,10 milligram (mg),8 por 8 hora,Solução injetável,bolus intravenoso,1 dia,8 em 8 horas
1,2 millilitre (mL),,Suspensão injetável,bolus intravenoso,1 hora,Dose única|
2,60 milligram (mg),2 por 2 dia,Solução injetável,subcutânea,10 dia,12 em 12 horas|
3,50 millilitre (mL),4 por 4 dia,Solução injetável,bolus intravenoso,3 hora,8 em 8 horas|
4,150 milligram (mg),2 por 12 hora,solução injetável,infusão intravenosa,25 dia,ciprofloxacino 150mg EV 12/12 administrar em 1 hora
5,1500 milligram (mg),3 por 8 hora,Comprimido,oral,5 dia,Clavulin 500 mg - 01 comprimido de 8/8 horas por 7 dias.
6,120 milligram (mg),6 por 4 hora,Comprimido,oral,34 dia,Morfina 10 mg - 2 comprimidos de 4/4 h.
7,300 milligram (mg),1 por 1 dia,Cápsula,oral,13 dia,Gabapentina 300 mg - 1 vez ao dia à noite.
8,100 milligram (mg),,Solução injetável,bolus intravenoso,1 dia,Dose única
9,450 milligram (mg),,Solução injetável,bolus intravenoso,1 dia,Dose única
10,50 milligram (mg),4 por 8 hora,Solução injetável,bolus intravenoso,10 minuto,50 mg/mL|8 em 8 horas
11,450 milligram (mg),,Solução injetável,bolus intravenoso,1 dia,Dose única|
12,100 milligram (mg),,Solução injetável,bolus intravenoso,1 dia,Dose única|
13,300 milligram (mg),,Comprimido simples,oral,2 hora,Diária
14,50 milligram (mg),,Comprimido simples,oral,2 hora,Diária