#  ⭐ `dim_dose`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root, normalize_dose

import re
import pandas as pd
from unidecode import unidecode

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet")  
bronze['DOSE']= bronze['DOSE'].fillna('DESCONHECIDO')
bronze = (
    bronze[['DOSE']]
    .value_counts()
    .rename('FREQUENCIA_REGISTROS')
    .reset_index()
) 
bronze.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS'], dtype='object')

In [4]:
bronze.DOSE.nunique()

9764

In [5]:
bronze.head(40)

                    DOSE  FREQUENCIA_REGISTROS
0           DESCONHECIDO                339554
1     100 milligram (mg)                 10204
2      50 milligram (mg)                  9612
3      10 milligram (mg)                  8231
4     300 milligram (mg)                  7323
5   1 dosage form ({DF})                  6812
6      20 milligram (mg)                  6795
7      40 milligram (mg)                  6051
8     500 milligram (mg)                  5743
9             1 gram (g)                  5266
10      5 milligram (mg)                  4643
11    150 milligram (mg)                  4503
12    400 milligram (mg)                  4425
13    200 milligram (mg)                  4335
14     25 milligram (mg)                  4016
15   1000 milligram (mg)                  3744
16    600 milligram (mg)                  2880
17      8 milligram (mg)                  2709
18            2 gram (g)                  2669
19  2 dosage form ({DF})                  2601
20      2 milligram (mg)                  2584
21      4 milligram (mg)                  1947
22     30 milligram (mg)                  1917
23     15 milligram (mg)                  1762
24     60 milligram (mg)                  1652
25      1 milligram (mg)                  1550
26  3 dosage form ({DF})                  1422
27     75 milligram (mg)                  1388
28     80 milligram (mg)                  1344
29    10 millilitre (mL)                  1290
30    2.5 milligram (mg)                  1220
31     20 microgram (ug)                  1216
32    120 milligram (mg)                  1167
33    750 milligram (mg)                  1134
34    250 milligram (mg)                  1088
35   2000 milligram (mg)                  1051
36    0.5 milligram (mg)                  1028
37   100 millilitre (mL)                   914
38    800 milligram (mg)                   914
39     90 milligram (mg)                   910

In [6]:
bronze.to_csv(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos_DOSE.csv", sep=";", index=False)

# 🥈 Silver

normalized data, medium quality

In [7]:
silver = normalize_dose(bronze, col="DOSE")

silver.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS', 'DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR',
       'DOSE_VALOR'],
      dtype='object')

In [8]:
silver[['DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR']].drop_duplicates().sort_values(by='DOSE_TIPO_VALOR')

                                    DOSE_TIPO_CHAVE  DOSE_TIPO_VALOR
0                                      desconhecido                0
1                                    milligram (mg)                1
29                                  millilitre (mL)                2
9                                          gram (g)                3
31                                   microgram (ug)                4
5                                dosage form ({DF})                5
81                   milligram per kilogram (mg/kg)                6
101              milligram per square metre (mg/m2)                7
60                        international unit ([iU])                8
84                   drop (1/12 millilitre) ([drp])                9
104                milligram per millilitre (mg/mL)               10
223                 milligram per decilitre (mg/dL)               11
3159                       microgram per day (ug/d)               12
2354      milligram per kilogram per hour (mg/kg/h)               13
420           international unit per litre ([iU]/L)               14
4416              milligram per 24 hour (mg/(24.h))               15
1419                               gram metre (g.m)               16
584                       gram per decilitre (g/dL)               17
1947                                total ({total})               18
1776                                      metre (m)               19
475                             per milligram (/mg)               20
6995            millilitre per square metre (mL/m2)               21
2385                              degree Kelvin (K)               22
629                                 enzyme unit (U)               23
2985                          milliequivalent (meq)               24
795                milli-international unit (m[iU])               25
2983                 per international unit (/[iU])               26
2004      international unit per kilogram ([iU]/kg)               27
7337                     tablespoon (US) ([tbs_us])               28
7345        milliequivalent per millilitre (meq/mL)               29
4419                                 24 hour (24.h)               30
5500                nanogram per millilitre (ng/mL)               31
2389                      milligram per hour (mg/h)               32
2400                kilo-international unit (k[iU])               33
6228                       Maclagan unit ([mclg'U])               34
2633              milligram per 12 hour (mg/(12.h))               35
7069                    per cubic millimetre (/mm3)               36
3278  microgram per kilogram per minute (ug/kg/min)               37
1627                                   per day (/d)               38
495        milligram per kilogram per day (mg/kg/d)               39

In [9]:
silver.DOSE_VALOR.value_counts(dropna=False).head(10)

DOSE_VALOR
1.0      104
5.0       82
2.0       70
500.0     59
4.0       58
10.0      53
100.0     50
3.0       50
50.0      47
20.0      45
Name: count, dtype: int64

In [10]:
silver.query("DOSE_TIPO_CHAVE == 'desconhecido'").DOSE.value_counts(dropna=False).head(40)

DOSE
DESCONHECIDO                                      1
1.1 microgram per kilogram per hour (ug/kg/h)     1
1 milligram per minute (mg/min)                   1
1 month (mo)                                      1
1 per 250 millilitre (/(250.mL))                  1
1 second (s)                                      1
1 week (wk)                                       1
1.0 millimole (mmol)                              1
1.000                                             1
1 gram per 24 hour (g/(24.h))                     1
1.25 microgram per kilogram (ug/kg)               1
1 millicurie (mCi)                                1
1.250.00                                          1
1.2E+07 dosage form ({DF})                        1
1.3                                               1
1.3 milligram per cubic metre (mg/m3)             1
1.34                                              1
1.1 milligram per 10 hour (mg/(10.h))             1
1.12 microgram per kilogram per hour (ug/kg/h)    1
1.14 microgram per kilogram (ug/kg)               1
1 milligram per day (mg/d)                        1
1 microgram per millilitre (ug/mL)                1
0.15 millilitre per minute (mL/min)               1
0.12 microgram per kilogram per day (ug/kg/d)     1
0.17 millilitre per minute (mL/min)               1
0.2 microgram per kilogram (ug/kg)                1
0.2 milliequivalent per litre (meq/L)             1
0.2 millilitre per hour (mL/h)                    1
0.2 millilitre per kilogram (mL/kg)               1
0.14 microgram per kilogram (ug/kg)               1
0.1 microgram per kilogram per hour (ug/kg/h)     1
0.1 per millilitre (/mL)                          1
0.12 microgram per kilogram per hour (ug/kg/h)    1
1 hundred per microlitre (10*2/uL)                1
1.000.00                                          1
1.02 microgram per kilogram per hour (ug/kg/h)    1
1.04 microgram per kilogram per hour (ug/kg/h)    1
1.050000 per enzyme unit (/U)                     1
1.1 microgram per kilogram (ug/kg)                1
1 gram per kilogram per day (g/kg/d)              1
Name: count, dtype: int64

In [11]:
hist = silver

In [12]:
hist.to_parquet(Path(project_root) / "data/02_silver/hist_dim_dose/hist_dim_dose.parquet", index=False)

In [13]:
hist.to_csv(Path(project_root) / "data/02_silver/hist_dim_dose/hist_dim_dose_MANUAL.csv", sep=";", index=False)

# 🥇 Gold

In [14]:
hist.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS', 'DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR',
       'DOSE_VALOR'],
      dtype='object')

In [15]:
dim = hist[['DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR']].sort_values(by='DOSE_TIPO_VALOR').drop_duplicates()
dim

                                    DOSE_TIPO_CHAVE  DOSE_TIPO_VALOR
0                                      desconhecido                0
646                                  milligram (mg)                1
3304                                millilitre (mL)                2
2670                                       gram (g)                3
1929                                 microgram (ug)                4
325                              dosage form ({DF})                5
4618                 milligram per kilogram (mg/kg)                6
5469             milligram per square metre (mg/m2)                7
8704                      international unit ([iU])                8
84                   drop (1/12 millilitre) ([drp])                9
8180               milligram per millilitre (mg/mL)               10
1686                milligram per decilitre (mg/dL)               11
9152                       microgram per day (ug/d)               12
7429      milligram per kilogram per hour (mg/kg/h)               13
6003          international unit per litre ([iU]/L)               14
9621              milligram per 24 hour (mg/(24.h))               15
3176                               gram metre (g.m)               16
7186                      gram per decilitre (g/dL)               17
1947                                total ({total})               18
7349                                      metre (m)               19
8497                            per milligram (/mg)               20
6995            millilitre per square metre (mL/m2)               21
3182                              degree Kelvin (K)               22
2199                                enzyme unit (U)               23
3423                          milliequivalent (meq)               24
1907               milli-international unit (m[iU])               25
5769                 per international unit (/[iU])               26
7094      international unit per kilogram ([iU]/kg)               27
7337                     tablespoon (US) ([tbs_us])               28
8666        milliequivalent per millilitre (meq/mL)               29
4419                                 24 hour (24.h)               30
5570                nanogram per millilitre (ng/mL)               31
2691                      milligram per hour (mg/h)               32
7093                kilo-international unit (k[iU])               33
6228                       Maclagan unit ([mclg'U])               34
2633              milligram per 12 hour (mg/(12.h))               35
9358                    per cubic millimetre (/mm3)               36
3278  microgram per kilogram per minute (ug/kg/min)               37
8663                                   per day (/d)               38
9711       milligram per kilogram per day (mg/kg/d)               39

In [16]:
dim.to_csv(Path(project_root) / "data/03_gold/dim_dose/dim_dose.csv",sep=";", index=False)