#  ⭐ `dim_atc`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root , normalize_atc
 
import pandas as pd

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

### ATC

In [3]:
bronze_atc = pd.read_excel(Path(project_root) / "data/01_bronze/atc/2025 ATC index with DDDs_english.xlsx")  
renomear = {
    "ATC code": "CODIGO_ATC_LEVEL",
    "ATC level name": "NIVEL_NOME_ATC",
    "DDD": "DDD_VALOR",
    "Unit": "DDD_UNIDADE",
    "Adm.R": "DDD_ADMINISTRACAO",
    "Comment": "DDD_COMENTARIO",
}

bronze_atc = bronze_atc.rename(columns=renomear)

In [4]:
bronze_atc.head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
0,A,ALIMENTARY TRACT AND METABOLISM,NaN,NaN,NaN,NaN
1,A01,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
2,A01AA,Caries prophylactic agents,NaN,NaN,NaN,NaN
3,A01AA01,sodium fluoride,1.10,mg,O,0.5 mg fluoride
4,A01AA02,sodium monofluorophosphate,NaN,NaN,NaN,NaN
5,A01AA03,olaflur,1.10,mg,O,NaN
6,A01AA04,stannous fluoride,NaN,NaN,NaN,NaN
7,A01AA30,combinations,NaN,NaN,NaN,NaN
8,A01AA51,"sodium fluoride, combinations",NaN,NaN,NaN,NaN
9,A01A,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
10,A01AB,Antiinfectives and antiseptics for local oral treatment,NaN,NaN,NaN,NaN
11,A01AB02,hydrogen peroxide,60.00,mg,O,NaN
12,A01AB03,chlorhexidine,30.00,mg,O,NaN
13,A01AB04,amphotericin B,40.00,mg,O,NaN
14,A01AB05,polynoxylin,0.18,g,O,NaN
15,A01AB06,domiphen,3.00,mg,O,NaN
16,A01AB07,oxyquinoline,80.00,mg,O,NaN
17,A01AB08,neomycin,NaN,NaN,NaN,NaN
18,A01AB09,miconazole,0.20,g,O,NaN
19,A01AB10,natamycin,20.00,mg,O,NaN

In [5]:
bronze_atc[bronze_atc["NIVEL_NOME_ATC"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
16,A01AB07,oxyquinoline,80.0,mg,O,NaN
465,A07AX01,broxyquinoline,NaN,NaN,NaN,NaN
2483,D08AH03,oxyquinoline,NaN,NaN,NaN,NaN
2656,G01AC01,diiodohydroxyquinoline,0.2,g,V,NaN
2660,G01AC06,broxyquinoline,0.1,g,V,NaN
2661,G01AC30,oxyquinoline,NaN,NaN,NaN,NaN
5898,P01AA,Hydroxyquinoline derivatives,NaN,NaN,NaN,NaN
5899,P01AA01,broxyquinoline,NaN,NaN,NaN,NaN
6175,R02AA14,oxyquinoline,NaN,NaN,NaN,NaN

In [6]:
bronze_atc.columns

Index(['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC', 'DDD_VALOR', 'DDD_UNIDADE',
       'DDD_ADMINISTRACAO', 'DDD_COMENTARIO'],
      dtype='object')

In [7]:
bronze_atc[['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC']].describe()

       CODIGO_ATC_LEVEL NIVEL_NOME_ATC
count              7435           7435
unique             6897           6045
top             G03CA03   combinations
freq                 10             38

### MEDICAMENTOS

In [8]:
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet") 
bronze = (
    bronze[['NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC']]
    .value_counts()
    .rename('FREQUENCIA_REGISTROS')
    .reset_index()
)
bronze['PRINCIPIOS_ATIVOS_WHODRUG_LIMPO'] = bronze['PRINCIPIOS_ATIVOS_WHODRUG'].replace('_x000D_', '', regex=True).str.strip()
bronze['CODIGO_ATC_5DIGITOS'] = bronze['CODIGO_ATC'].replace('_x000D_', '', regex=True).str.strip()

In [9]:
 
bronze.head()

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS
0,COVID-19 vaccine AstraZeneca,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX,14481,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX
1,Comirnaty,Tozinameran,J07BX,8808,Tozinameran,J07BX
2,CoronaVac,COVID-19 vaccine inact (Vero) CZ02,J07BX,6280,COVID-19 vaccine inact (Vero) CZ02,J07BX
3,Cosentyx,Secukinumab,L04AC,4980,Secukinumab,L04AC
4,Tramadol,Tramadol,N02AX,3888,Tramadol,N02AX

In [10]:
bronze.query("CODIGO_ATC=='S02DC'")

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS
2836,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC,25,Hydroxyquinoline borate|Trolamine,S02DC
6217,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC,7,Hydroxyquinoline borate|Trolamine,S02DC

In [11]:
bronze[bronze["NOME_MEDICAMENTO_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC, FREQUENCIA_REGISTROS, PRINCIPIOS_ATIVOS_WHODRUG_LIMPO, CODIGO_ATC_5DIGITOS]
Index: []

In [12]:
bronze[bronze["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS
2836,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC,25,Hydroxyquinoline borate|Trolamine,S02DC
6217,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC,7,Hydroxyquinoline borate|Trolamine,S02DC
17926,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,1,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX
17927,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,1,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB

# 🥈 Silver

normalized data, medium quality

In [13]:
silver = bronze.copy()

In [14]:
hist = normalize_atc(silver, bronze_atc, threshold=75)
hist.head()

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
0,COVID-19 vaccine AstraZeneca,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX,14481,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX,J07BX,76.864407
1,Comirnaty,Tozinameran,J07BX,8808,Tozinameran,J07BX,J07BX,78.548387
2,CoronaVac,COVID-19 vaccine inact (Vero) CZ02,J07BX,6280,COVID-19 vaccine inact (Vero) CZ02,J07BX,J07BX,78.461538
3,Cosentyx,Secukinumab,L04AC,4980,Secukinumab,L04AC,L04AC10,89.166667
4,Tramadol,Tramadol,N02AX,3888,Tramadol,N02AX,N02AX02,89.166667

In [15]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
2836,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC,25,Hydroxyquinoline borate|Trolamine,S02DC,S02DC,76.052632
6217,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC,7,Hydroxyquinoline borate|Trolamine,S02DC,S02DC,76.052632
17926,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,1,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,desconhecido,NaN
17927,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,1,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,desconhecido,NaN

In [16]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
2836,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC,25,Hydroxyquinoline borate|Trolamine,S02DC,S02DC,76.052632
6217,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC,7,Hydroxyquinoline borate|Trolamine,S02DC,S02DC,76.052632
17926,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,1,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,desconhecido,NaN
17927,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,1,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,desconhecido,NaN

In [17]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
63,Rituximab,Rituximabe,L01FA_x000D_|L04AG,979,Rituximabe,L01FA|L04AG,L01FA01,76.491228
160,Mabthera,Rituximab,L01XC,503,Rituximab,L01XC,desconhecido,NaN
198,Rituximab,Rituximab,L01FA,440,Rituximab,L01FA,L01FA01,89.166667
300,Rituximab,Rituximab,L01XC,321,Rituximab,L01XC,desconhecido,NaN
337,Riximyo,Rituximabe,L01FA,297,Rituximabe,L01FA,L01FA01,87.324561
381,Truxima,Rituximabe,L01FA_x000D_|L04AG,272,Rituximabe,L01FA|L04AG,L01FA01,76.491228
523,Vivaxxia,Rituximabe,L01FA,204,Rituximabe,L01FA,L01FA01,87.324561
532,Riximyo,Rituximab,L01FA,202,Rituximab,L01FA,L01FA01,89.166667
550,Mabthera,Rituximab,L01FA,197,Rituximab,L01FA,L01FA01,89.166667
672,Mabthera,Rituximabe,L01FA,157,Rituximabe,L01FA,L01FA01,87.324561
690,Vivaxxia,Rituximab,L01FA,153,Rituximab,L01FA,L01FA01,89.166667
794,Rituximab,Rituximabe,L01FA|L04AG,132,Rituximabe,L01FA|L04AG,L01FA01,76.491228
892,Riximyo,Rituximab,L01XC,116,Rituximab,L01XC,desconhecido,NaN
1034,Truxima,Rituximab abbs,L01FA,97,Rituximab abbs,L01FA,L01FA01,89.166667
1138,Vivaxxia,Rituximab,L01XC,88,Rituximab,L01XC,desconhecido,NaN
1187,Ruxience,Rituximabe,L01FA_x000D_|L04AG,83,Rituximabe,L01FA|L04AG,L01FA01,76.491228
1389,Truxima,Rituximab,L01FA,67,Rituximab,L01FA,L01FA01,89.166667
1482,Mabthera,Rituximabe,L01FA_x000D_|L04AG,62,Rituximabe,L01FA|L04AG,L01FA01,76.491228
2158,Rituximab bs pfizer,Rituximab biosimilar 2,L01FA,37,Rituximab biosimilar 2,L01FA,L01FA01,89.166667
2542,Truxima,Rituximabe,L01FA,29,Rituximabe,L01FA,L01FA01,87.324561
2678,Ruxience,Rituximabe,L01FA,27,Rituximabe,L01FA,L01FA01,87.324561
2935,Truxima,Rituximabe,L01FA|L04AG,24,Rituximabe,L01FA|L04AG,L01FA01,76.491228
3018,Ruxience,Rituximab pvvr,L01FA,23,Rituximab pvvr,L01FA,L01FA01,89.166667
5066,R CHOP,Ciclofosfamida_x000D_|Cloridrato de doxorrubicina_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,10,Ciclofosfamida|Cloridrato de doxorrubicina|Prednisone|Rituximabe|Sulfato de vincristina,L01XY,desconhecido,NaN
5348,Rituxim,Rituximabe,L01FA,9,Rituximabe,L01FA,L01FA01,87.324561
6168,Mabthera,Rituximabe,L01FA|L04AG,7,Rituximabe,L01FA|L04AG,L01FA01,76.491228
6170,Mabthera sc,Rituximab,L01FA,7,Rituximab,L01FA,L01FA01,89.166667
6175,Truxima,Rituximab,L01XC,7,Rituximab,L01XC,desconhecido,NaN
6283,Ruxience,Rituximabe,L01FA|L04AG,6,Rituximabe,L01FA|L04AG,L01FA01,76.491228
6555,Rituxikal,Rituximabe,L01FA,6,Rituximabe,L01FA,L01FA01,87.324561
6613,Rituximab abbs,Rituximab abbs,L01FA,6,Rituximab abbs,L01FA,L01FA01,89.166667
7320,Mabthera sc,Rituximab,L01XC,5,Rituximab,L01XC,desconhecido,NaN
7630,R CHOP,Cyclophosphamide|Doxorubicin hydrochloride|Prednisone|Rituximab|Vincristine sulfate,L01XY,4,Cyclophosphamide|Doxorubicin hydrochloride|Prednisone|Rituximab|Vincristine sulfate,L01XY,L01XY,76.775701
8685,Rituxan,Rituximab,L01XC,3,Rituximab,L01XC,desconhecido,NaN
8695,"Rituximab,Venetoclax",Rituximabe_x000D_|Venetoclax,L01XY,3,Rituximabe|Venetoclax,L01XY,desconhecido,NaN
9436,"Chlorambucil,Rituximab",Clorambucila_x000D_|Rituximabe,L01XY,3,Clorambucila|Rituximabe,L01XY,desconhecido,NaN
10414,Truxima,Rituximab abbs,L01XC,2,Rituximab abbs,L01XC,desconhecido,NaN
11543,Rituximab bs,Rituximab biosimilar 1,L01FA,2,Rituximab biosimilar 1,L01FA,L01FA01,89.166667
11632,Rixathon,Rituximabe,L01FA,2,Rituximabe,L01FA,L01FA01,87.324561
12425,"Cyclophosphamide,Prednisone,Rituximab,Vincristine sulfate",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,2,Ciclofosfamida|Prednisone|Rituximabe|Sulfato de vincristina,L01XY,L01XY,77.395833

In [18]:
hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

/var/folders/6r/t8g0l_4n2h97mg8j0fp43scr0000gn/T/ipykernel_22597/2012540531.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
160,Mabthera,Rituximab,L01XC,503,Rituximab,L01XC,desconhecido,NaN
300,Rituximab,Rituximab,L01XC,321,Rituximab,L01XC,desconhecido,NaN
892,Riximyo,Rituximab,L01XC,116,Rituximab,L01XC,desconhecido,NaN
1138,Vivaxxia,Rituximab,L01XC,88,Rituximab,L01XC,desconhecido,NaN
6175,Truxima,Rituximab,L01XC,7,Rituximab,L01XC,desconhecido,NaN
7320,Mabthera sc,Rituximab,L01XC,5,Rituximab,L01XC,desconhecido,NaN
8685,Rituxan,Rituximab,L01XC,3,Rituximab,L01XC,desconhecido,NaN
10414,Truxima,Rituximab abbs,L01XC,2,Rituximab abbs,L01XC,desconhecido,NaN
14238,Ruxience,Rituximab,L01XC,1,Rituximab,L01XC,desconhecido,NaN
5066,R CHOP,Ciclofosfamida_x000D_|Cloridrato de doxorrubicina_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,10,Ciclofosfamida|Cloridrato de doxorrubicina|Prednisone|Rituximabe|Sulfato de vincristina,L01XY,desconhecido,NaN
8695,"Rituximab,Venetoclax",Rituximabe_x000D_|Venetoclax,L01XY,3,Rituximabe|Venetoclax,L01XY,desconhecido,NaN
9436,"Chlorambucil,Rituximab",Clorambucila_x000D_|Rituximabe,L01XY,3,Clorambucila|Rituximabe,L01XY,desconhecido,NaN
14408,"Rituximab,Venetoclax",Rituximabe|Venetoclax,L01XY,1,Rituximabe|Venetoclax,L01XY,desconhecido,NaN
15820,"Cyclophosphamide,Prednisone,Rituximab",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe,L01XY,1,Ciclofosfamida|Prednisone|Rituximabe,L01XY,desconhecido,NaN
19120,FCR,Ciclofosfamida_x000D_|Fludarabine_x000D_|Rituximabe,L01XY,1,Ciclofosfamida|Fludarabine|Rituximabe,L01XY,desconhecido,NaN

In [19]:
histv2 = hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")
histv2 = normalize_atc(histv2, bronze_atc, threshold=75)
histv2.head()

/var/folders/6r/t8g0l_4n2h97mg8j0fp43scr0000gn/T/ipykernel_22597/3878801764.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  histv2 = hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC, FREQUENCIA_REGISTROS, PRINCIPIOS_ATIVOS_WHODRUG_LIMPO, CODIGO_ATC_5DIGITOS, CODIGO_ATC_LEVEL, CODIGO_ATC_LEVEL_SCORE]
Index: []

In [20]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("golimumab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
16,Simponi,Golimumab,L04AB,2078,Golimumab,L04AB,L04AB06,89.166667
34,Simponi,Golimumabe,L04AB,1482,Golimumabe,L04AB,L04AB06,87.324561
161,Golimumab,Golimumabe,L04AB,503,Golimumabe,L04AB,L04AB06,87.324561
1085,Bio manguinhos golimumabe,Golimumabe,L04AB,93,Golimumabe,L04AB,L04AB06,87.324561
2886,Golimumab,Golimumab,L04AB,24,Golimumab,L04AB,L04AB06,89.166667
5979,Simponi iv,Golimumabe,L04AB,7,Golimumabe,L04AB,L04AB06,87.324561
8678,Golimumab recombinant,Golimumabe,L04AB,3,Golimumabe,L04AB,L04AB06,87.324561
12819,Simponi aria,Golimumab,L04AB,1,Golimumab,L04AB,L04AB06,89.166667

In [21]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("golimumab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
16,Simponi,Golimumab,L04AB,2078,Golimumab,L04AB,L04AB06,89.166667
34,Simponi,Golimumabe,L04AB,1482,Golimumabe,L04AB,L04AB06,87.324561
161,Golimumab,Golimumabe,L04AB,503,Golimumabe,L04AB,L04AB06,87.324561
1085,Bio manguinhos golimumabe,Golimumabe,L04AB,93,Golimumabe,L04AB,L04AB06,87.324561
2886,Golimumab,Golimumab,L04AB,24,Golimumab,L04AB,L04AB06,89.166667
5979,Simponi iv,Golimumabe,L04AB,7,Golimumabe,L04AB,L04AB06,87.324561
8678,Golimumab recombinant,Golimumabe,L04AB,3,Golimumabe,L04AB,L04AB06,87.324561
12819,Simponi aria,Golimumab,L04AB,1,Golimumab,L04AB,L04AB06,89.166667

In [22]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("infliximab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
6,Remsima,Infliximabe,L04AB,3145,Infliximabe,L04AB,L04AB02,87.500000
7,Remicade,Infliximab,L04AB,2961,Infliximab,L04AB,L04AB02,89.166667
11,Infliximab,Infliximab,L04AB,2521,Infliximab,L04AB,L04AB02,89.166667
18,Infliximab,Infliximabe,L04AB,2007,Infliximabe,L04AB,L04AB02,87.500000
23,Remicade,Infliximabe,L04AB,1824,Infliximabe,L04AB,L04AB02,87.500000
57,Bio manguinhos infliximabe,Infliximabe,L04AB,1034,Infliximabe,L04AB,L04AB02,87.500000
206,Bio manguinhos infliximabe,Infliximab,L04AB,434,Infliximab,L04AB,L04AB02,89.166667
498,Remsima,Infliximab,L04AB,209,Infliximab,L04AB,L04AB02,89.166667
589,Infliximab Recombinant,Infliximabe,L04AB,182,Infliximabe,L04AB,L04AB02,87.500000
638,Infliximab Recombinant,Infliximab,L04AB,170,Infliximab,L04AB,L04AB02,89.166667
866,Xilfya,Infliximabe,L04AB,120,Infliximabe,L04AB,L04AB02,87.500000
2216,Xilfya,Infliximab,L04AB,36,Infliximab,L04AB,L04AB02,89.166667
4063,Infliximab biosimilar 1,Infliximab biosimilar 1,L04AB,14,Infliximab biosimilar 1,L04AB,L04AB02,89.166667
5043,Avsola,Infliximabe,L04AB,10,Infliximabe,L04AB,L04AB02,87.500000
5269,Infliximab dyyb,Infliximab dyyb,L04AB,9,Infliximab dyyb,L04AB,L04AB02,89.166667
6347,Remsima sc,Infliximabe,L04AB,6,Infliximabe,L04AB,L04AB02,87.500000
7053,Infliximab bs pfizer,Infliximab biosimilar 3,L04AB,5,Infliximab biosimilar 3,L04AB,L04AB02,89.166667
8710,Infliximab bs nichiiko,Infliximab,L04AB,3,Infliximab,L04AB,L04AB02,89.166667
12445,Renflexis,Infliximabe,L04AB,2,Infliximabe,L04AB,L04AB02,87.500000
13825,Remicade lyophilisat,Infliximab,L04AB,1,Infliximab,L04AB,L04AB02,89.166667

In [23]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("infliximab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
6,Remsima,Infliximabe,L04AB,3145,Infliximabe,L04AB,L04AB02,87.500000
7,Remicade,Infliximab,L04AB,2961,Infliximab,L04AB,L04AB02,89.166667
11,Infliximab,Infliximab,L04AB,2521,Infliximab,L04AB,L04AB02,89.166667
18,Infliximab,Infliximabe,L04AB,2007,Infliximabe,L04AB,L04AB02,87.500000
23,Remicade,Infliximabe,L04AB,1824,Infliximabe,L04AB,L04AB02,87.500000
57,Bio manguinhos infliximabe,Infliximabe,L04AB,1034,Infliximabe,L04AB,L04AB02,87.500000
206,Bio manguinhos infliximabe,Infliximab,L04AB,434,Infliximab,L04AB,L04AB02,89.166667
498,Remsima,Infliximab,L04AB,209,Infliximab,L04AB,L04AB02,89.166667
589,Infliximab Recombinant,Infliximabe,L04AB,182,Infliximabe,L04AB,L04AB02,87.500000
638,Infliximab Recombinant,Infliximab,L04AB,170,Infliximab,L04AB,L04AB02,89.166667
866,Xilfya,Infliximabe,L04AB,120,Infliximabe,L04AB,L04AB02,87.500000
2216,Xilfya,Infliximab,L04AB,36,Infliximab,L04AB,L04AB02,89.166667
4063,Infliximab biosimilar 1,Infliximab biosimilar 1,L04AB,14,Infliximab biosimilar 1,L04AB,L04AB02,89.166667
5043,Avsola,Infliximabe,L04AB,10,Infliximabe,L04AB,L04AB02,87.500000
5269,Infliximab dyyb,Infliximab dyyb,L04AB,9,Infliximab dyyb,L04AB,L04AB02,89.166667
6347,Remsima sc,Infliximabe,L04AB,6,Infliximabe,L04AB,L04AB02,87.500000
7053,Infliximab bs pfizer,Infliximab biosimilar 3,L04AB,5,Infliximab biosimilar 3,L04AB,L04AB02,89.166667
8710,Infliximab bs nichiiko,Infliximab,L04AB,3,Infliximab,L04AB,L04AB02,89.166667
12445,Renflexis,Infliximabe,L04AB,2,Infliximabe,L04AB,L04AB02,87.500000
13825,Remicade lyophilisat,Infliximab,L04AB,1,Infliximab,L04AB,L04AB02,89.166667

In [24]:
hist.to_csv(
    Path(project_root) / "data/02_silver/hist_dim_atc/hist_dim_atc_MANUAL.csv",
    sep=";",
    decimal=",",
    encoding="utf-8-sig",   # em vez de utf-8
    index=False,
)

In [25]:
silver.head(2)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,FREQUENCIA_REGISTROS,PRINCIPIOS_ATIVOS_WHODRUG_LIMPO,CODIGO_ATC_5DIGITOS,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
0,COVID-19 vaccine AstraZeneca,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX,14481,COVID-19 vaccine NRVV Ad (ChAdOx1 nCoV-19),J07BX,J07BX,76.864407
1,Comirnaty,Tozinameran,J07BX,8808,Tozinameran,J07BX,J07BX,78.548387

# 🥇 Gold

In [26]:
hist.columns

Index(['NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC',
       'FREQUENCIA_REGISTROS', 'PRINCIPIOS_ATIVOS_WHODRUG_LIMPO',
       'CODIGO_ATC_5DIGITOS', 'CODIGO_ATC_LEVEL', 'CODIGO_ATC_LEVEL_SCORE'],
      dtype='object')

In [27]:
#dim = hist[['DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR']].drop_duplicates()
#dim.to_parquet(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.parquet", index=False)

In [28]:

#dim.to_csv(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.csv", sep=";", index=False)