#  ⭐ `dim_dose`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root, normalize_dose

import re
import pandas as pd
from unidecode import unidecode

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/anvisa/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/anvisa/Medicamentos/Medicamentos.parquet")  
bronze['DOSE']= bronze['DOSE'].fillna('DESCONHECIDO')
bronze = (
    bronze[['DOSE']]
    .value_counts()
    .rename('FREQUENCIA_REGISTROS')
    .reset_index()
) 
bronze.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS'], dtype='object')

In [4]:
bronze.DOSE.nunique()

10242

In [5]:
bronze.head(40)

                    DOSE  FREQUENCIA_REGISTROS
0           DESCONHECIDO                362716
1     100 milligram (mg)                 10888
2      50 milligram (mg)                 10206
3      10 milligram (mg)                  8807
4     300 milligram (mg)                  7805
5      20 milligram (mg)                  7264
6   1 dosage form ({DF})                  7168
7      40 milligram (mg)                  6389
8     500 milligram (mg)                  6151
9             1 gram (g)                  5719
10      5 milligram (mg)                  5025
11    150 milligram (mg)                  4723
12    200 milligram (mg)                  4682
13    400 milligram (mg)                  4677
14     25 milligram (mg)                  4272
15   1000 milligram (mg)                  4093
16    600 milligram (mg)                  3064
17      8 milligram (mg)                  2988
18            2 gram (g)                  2875
19      2 milligram (mg)                  2751
20  2 dosage form ({DF})                  2743
21      4 milligram (mg)                  2083
22     30 milligram (mg)                  2005
23     15 milligram (mg)                  1885
24     60 milligram (mg)                  1740
25      1 milligram (mg)                  1721
26  3 dosage form ({DF})                  1522
27     75 milligram (mg)                  1478
28     80 milligram (mg)                  1439
29    10 millilitre (mL)                  1410
30    2.5 milligram (mg)                  1345
31    120 milligram (mg)                  1252
32     20 microgram (ug)                  1251
33    750 milligram (mg)                  1212
34    250 milligram (mg)                  1163
35   2000 milligram (mg)                  1140
36    0.5 milligram (mg)                  1105
37   100 millilitre (mL)                  1005
38    800 milligram (mg)                   975
39     90 milligram (mg)                   939

In [6]:
bronze.to_csv(Path(project_root) / "eda/Medicamentos/Medicamentos_DOSE.csv", sep=";", index=False)

# 🥈 Silver

normalized data, medium quality

In [7]:
silver = normalize_dose(bronze, col="DOSE")

silver.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS', 'DOSE_TIPO_VALOR', 'DOSE_TIPO_CHAVE',
       'DOSE_VALOR'],
      dtype='object')

In [8]:
silver[['DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR']].drop_duplicates().sort_values(by='DOSE_TIPO_VALOR')

      DOSE_TIPO_CHAVE                                DOSE_TIPO_VALOR
9504               30                                 24 hour (24.h)
7596               34                       Maclagan unit ([mclg'U])
2821               22                              degree Kelvin (K)
0                   0                                   desconhecido
6                   5                             dosage form ({DF})
83                  9                 drop (1/12 millilitre) ([drp])
650                23                                enzyme unit (U)
9                   3                                       gram (g)
1426               16                               gram metre (g.m)
599                17                      gram per decilitre (g/dL)
60                  8                      international unit ([iU])
2255               27      international unit per kilogram ([iU]/kg)
348                14          international unit per litre ([iU]/L)
1886               33                kilo-international unit (k[iU])
1871               19                                      metre (m)
32                  4                                 microgram (ug)
3636               12                       microgram per day (ug/d)
3936               37  microgram per kilogram per minute (ug/kg/min)
818                25               milli-international unit (m[iU])
3326               24                          milliequivalent (meq)
5362               29        milliequivalent per millilitre (meq/mL)
1                   1                                 milligram (mg)
2839               35              milligram per 12 hour (mg/(12.h))
5123               15              milligram per 24 hour (mg/(24.h))
186                11                milligram per decilitre (mg/dL)
2475               32                      milligram per hour (mg/h)
78                  6                 milligram per kilogram (mg/kg)
531                39       milligram per kilogram per day (mg/kg/d)
2508               13      milligram per kilogram per hour (mg/kg/h)
95                 10               milligram per millilitre (mg/mL)
103                 7             milligram per square metre (mg/m2)
29                  2                                millilitre (mL)
5253               21            millilitre per square metre (mL/m2)
7554               31                nanogram per millilitre (ng/mL)
4820               36                    per cubic millimetre (/mm3)
1730               38                                   per day (/d)
3084               26                 per international unit (/[iU])
446                20                            per milligram (/mg)
862                28                     tablespoon (US) ([tbs_us])
1927               18                                total ({total})

In [9]:
silver.DOSE_VALOR.value_counts(dropna=False).head(10)

DOSE_VALOR
1.0      108
5.0       87
2.0       77
500.0     60
4.0       59
10.0      58
3.0       54
100.0     51
20.0      50
50.0      49
Name: count, dtype: int64

In [10]:
silver.query("DOSE_TIPO_CHAVE == 'desconhecido'").DOSE.value_counts(dropna=False).head(40)

Series([], Name: count, dtype: int64)

In [11]:
hist = silver

In [12]:
hist.to_parquet(Path(project_root) / "data/02_silver/hist_dim_dose/hist_dim_dose.parquet", index=False)

In [13]:
hist.to_csv(Path(project_root) / "data/02_silver/hist_dim_dose/hist_dim_dose_MANUAL.csv", sep=";", index=False)

# 🥇 Gold

In [14]:
hist.columns

Index(['DOSE', 'FREQUENCIA_REGISTROS', 'DOSE_TIPO_VALOR', 'DOSE_TIPO_CHAVE',
       'DOSE_VALOR'],
      dtype='object')

In [15]:
dim = hist[['DOSE_TIPO_CHAVE', 'DOSE_TIPO_VALOR']].sort_values(by='DOSE_TIPO_VALOR').drop_duplicates()
dim

       DOSE_TIPO_CHAVE                                DOSE_TIPO_VALOR
9609                30                                 24 hour (24.h)
7596                34                       Maclagan unit ([mclg'U])
3987                22                              degree Kelvin (K)
4987                 0                                   desconhecido
4118                 5                             dosage form ({DF})
10124                9                 drop (1/12 millilitre) ([drp])
2360                23                                enzyme unit (U)
6770                 3                                       gram (g)
3814                16                               gram metre (g.m)
1095                17                      gram per decilitre (g/dL)
3746                 8                      international unit ([iU])
6410                27      international unit per kilogram ([iU]/kg)
3910                14          international unit per litre ([iU]/L)
5473                33                kilo-international unit (k[iU])
5561                19                                      metre (m)
9945                 4                                 microgram (ug)
8062                12                       microgram per day (ug/d)
9967                37  microgram per kilogram per minute (ug/kg/min)
9259                25               milli-international unit (m[iU])
5416                24                          milliequivalent (meq)
9618                29        milliequivalent per millilitre (meq/mL)
7150                 1                                 milligram (mg)
7567                35              milligram per 12 hour (mg/(12.h))
9548                15              milligram per 24 hour (mg/(24.h))
9111                11                milligram per decilitre (mg/dL)
2611                32                      milligram per hour (mg/h)
2076                 6                 milligram per kilogram (mg/kg)
4314                39       milligram per kilogram per day (mg/kg/d)
4637                13      milligram per kilogram per hour (mg/kg/h)
508                 10               milligram per millilitre (mg/mL)
162                  7             milligram per square metre (mg/m2)
2738                 2                                millilitre (mL)
5253                21            millilitre per square metre (mL/m2)
7554                31                nanogram per millilitre (ng/mL)
4820                36                    per cubic millimetre (/mm3)
1730                38                                   per day (/d)
5275                26                 per international unit (/[iU])
7969                20                            per milligram (/mg)
862                 28                     tablespoon (US) ([tbs_us])
1927                18                                total ({total})

In [16]:
dim.to_csv(Path(project_root) / "data/03_gold/dim_dose/dim_dose.csv",sep=";", index=False)