#  ⭐ `dim_via_administracao`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root , normalizar_via_administracao#, normalizar_via_fuzzy

import re
import pandas as pd
from unidecode import unidecode

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet") 
bronze =  bronze[["VIA_ADMINISTRACAO_MAE_PAI","VIA_ADMINISTRACAO"]].drop_duplicates()
bronze.columns

Index(['VIA_ADMINISTRACAO_MAE_PAI', 'VIA_ADMINISTRACAO'], dtype='object')

In [7]:
bronze.VIA_ADMINISTRACAO.nunique()

1837

In [5]:
bronze.VIA_ADMINISTRACAO_MAE_PAI.nunique()

23

In [6]:
bronze.to_csv(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos_VIA_ADM.csv", sep=";", index=False)

# 🥈 Silver

normalized data, medium quality

In [25]:
import pandas as pd
from unidecode import unidecode
from rapidfuzz import process, fuzz

# 1. Palavras canônicas -> códigos finais
CANONICAL_KEYWORDS = {
    "Implant": [
        "implant",
        "intrauterine delivery system",
        "intrauterino",
        "intra-uterino","braço"
    ],
    "Inhal": [
        "inhalacao", "inhalation", "inalatorio", "inalatoria",
        "aerosol", "nebulizacao", "respiratoria", "uso inalatorio",
    ],
    "Instill": [
        "oftalmica", "oftalmico", "ophthalmic",
        "colirio", "ocular", "otologica", "auricular","ocular"
    ],
    "N": [
        "nasal", "intranasal", "spray nasal",
    ],
    "O": [
        "via oral", "oral", "uso oral",
        "oral use",
        "enteral", "gastroenteral", "gastroenterica",
        "sonda nasogastrica", "nasogastric tube",
        "sonda nasoenteral", "gastrostomia", "jejunostomia",
    ],
    "P": [
        "intravenosa", "intravenoso", "endovenosa", "endovenoso","ev / iv",
        "intravenous"
        "ev", "iv", "infusao", "bolus", "bomba de infusao",
        "intramuscular", "im",
        "subcutanea", "subcutaneo", "sc",
        "hipodermoclise",
        "intratecal", "intrathecal", "raquidiana", "epidural", "peridural",
        "intraperitoneal", "intracavitaria", "intravesical",
        "hemodialise", "extracorporea",
        "parenteral",
        "intravitreal", "intravitre",
        "dental",
        "transplacental", "transmamaria", "transmammary","intramuscular",
        "tranplacental"
    ],
    "R": [
        "retal", "via retal", "rectal",
    ],
    "SL": [
        "sublingual", "buccal", "bucal", "oromucosal", "oromucosa",
    ],
    "TD": [
        "topica", "topico", "tópica", "tópico",
        "cutanea", "cutaneo", "cutaneous",
        "dermatologica",
        "transdermica", "transdermico", "transdermal",
        "percutanea",
    ],
    "V": [
        "vaginal", "intravaginal",
    ],
}

# 2. Lista auxiliar para fuzzy: (palavra_canonica_normalizada, codigo)
CANONICAL_FLAT = []
for code, words in CANONICAL_KEYWORDS.items():
    for w in words:
        CANONICAL_FLAT.append(
            (unidecode(w).lower().strip(), code)
        )

UNKNOWN_TOKENS = [
    "unknown", "desconhecid", "e2b r2 code: 065", "e2b r2 code: 050",
    "nao informado", "não informado", "nao informada", "não informada",
    "nao perguntado", "não perguntado",
    "nao questionado", "não questionado",
    "via desconhecida", "rota desconhecida",
    "via de administracao nao informada",
    "via de administracao nao especificada",
    "route of administration not applicable",
]


def _preprocess(text: str) -> str:
    return " ".join(unidecode(str(text)).lower().strip().split())


def _is_unknown(s: str) -> bool:
    if s in {"", "none", "nan", "na", "n/a"}:
        return True
    return any(tok in s for tok in UNKNOWN_TOKENS)


def normalizar_via_fuzzy(value: str,
                         score_threshold: int = 80) -> str:
    """
    Normaliza via de administração usando fuzzy matching
    contra palavras canônicas definidas em CANONICAL_KEYWORDS.
    Retorna um dos códigos:
      Implant, Inhal, Instill, N, O, P, R, SL, TD, V
    ou 'desconhecido'.
    """
    if pd.isna(value):
        return "desconhecido"

    s = _preprocess(value)

    # 1) Desconhecido explícito
    if _is_unknown(s):
        return "desconhecido"

    # 2) Tratamento simples de combinações claras:
    #    se tiver oral + venoso/subcutâneo, prioriza P
    has_oral = "oral" in s
    has_parenteral_token = any(
        t in s
        for t in ("intraven", "endoven", "venos", "intramus", "subcut", "hipodermoclise")
    )
    if has_oral and has_parenteral_token:
        return "P"

    # 3) Fuzzy: compara a string s com todas as palavras canônicas
    candidates = [w for (w, _) in CANONICAL_FLAT]
    best, score, idx = process.extractOne(
        s,
        candidates,
        scorer=fuzz.partial_ratio
    )

    if score < score_threshold:
        return "desconhecido"

    # recupera o código associado à palavra canônica escolhida
    canon_word, code = CANONICAL_FLAT[idx]
    return code

In [26]:
silver = pd.read_csv(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos_VIA_ADM.csv", sep=";") ## Manual Normalization
 
silver.columns

Index(['VIA_ADMINISTRACAO_MAE_PAI', 'VIA_ADMINISTRACAO'], dtype='object')

In [14]:
silver["VIA_ADMINISTRACAO_CHAVE"] = silver["VIA_ADMINISTRACAO"].apply(normalizar_via_administracao)
silver["VIA_ADMINISTRACAO_MAE_PAI_CHAVE"] = silver["VIA_ADMINISTRACAO_MAE_PAI"].apply(normalizar_via_administracao)

In [15]:

silver["VIA_ADMINISTRACAO_MAE_PAI_CHAVE"].value_counts()

VIA_ADMINISTRACAO_MAE_PAI_CHAVE
desconhecido    1850
O                 10
P                  8
TD                 6
Implant            1
Inhal              1
Name: count, dtype: int64

In [27]:
silver["VIA_ADMINISTRACAO_CHAVE_fuzzy"] = silver["VIA_ADMINISTRACAO"].apply(normalizar_via_fuzzy)
silver["VIA_ADMINISTRACAO_MAE_PAI_CHAVE_fuzzy"] = silver["VIA_ADMINISTRACAO_MAE_PAI"].apply(normalizar_via_fuzzy)

In [29]:

silver.to_csv(Path(project_root) / "data/02_silver/hist_via_adm/MANUAL_hist_via_adm.csv", sep=";", index=False)

In [28]:
silver["VIA_ADMINISTRACAO_CHAVE_fuzzy"].value_counts()

VIA_ADMINISTRACAO_CHAVE_fuzzy
P               856
desconhecido    381
O               250
Inhal           100
TD               98
Implant          77
Instill          58
N                21
R                14
SL               13
V                 8
Name: count, dtype: int64

In [18]:
silver["VIA_ADMINISTRACAO_MAE_PAI_CHAVE_fuzzy"].value_counts()

VIA_ADMINISTRACAO_MAE_PAI_CHAVE_fuzzy
desconhecido    1848
P                 14
O                 11
Implant            2
Inhal              1
Name: count, dtype: int64

In [21]:
silver.query("VIA_ADMINISTRACAO_MAE_PAI_CHAVE_fuzzy=='desconhecido'")["VIA_ADMINISTRACAO"].drop_duplicates()

0                                                infusão intravenosa
1                                                               oral
2                                                                NaN
3                                                      intramuscular
4                                     intravenosa (não especificado)
5                                                              outra
6                                                            vaginal
7                                                         subcutânea
8                                                            cutânea
9                                                           epidural
10                                            repiratória (inalação)
11                                                         oftálmica
12                                                             nasal
13                                                            dental
14                                                   intra-articular
15                                                     tranplacental
16                                                 bolus intravenoso
17                                                      desconhecida
18                                                        intratecal
19                                                      transmamária
20                                                            tópica
21                                                      intradérmica
22                                                     intralesional
23                                                             retal
24                                                        sublingual
25                                                     subconjuntiva
26                                                     intravesical
27                                                           uretral
28                                                     intracerebral
29                                                        parenteral
30                                                             bucal
31                                                      intrauterina
32                                                    intracavernosa
33                                                      transdérmica
34                                                         auricular
35                                                      endotraqueal
36                                                    intra-arterial
37                                                       intradiscal
38                                                     intracervical
39                                                        subdérmica
40                                                      intratumoral
41                                                        orofaringe
42                                                   intra-amniótica
43                                                        perineural
44                                                  intracoronariana
45                                                       intraocular
46                                                       hemodiálise
47                                                      endocervical
48                                                    intralinfática
49                                                      intramedular
51                                                   inalatório oral
53                                                     Não informado
54                                                   Inalatória oral
55                                                      DESCONHECIDO
56                                                         endovenos
57                                    Medicamento utilizado pela mae
58                                                     Não informada
59                                                            Dose 3
60                                                            Dose 2
61                                                            Dose 1
62                                                (INTRAVENOUS DRIP)
63                                           gotejamento intravenoso
64                                                       Intravenoso
65                                                       intravenosa
66                                                      Desconhecida
67                                                           Capilar
68                                                        ENDOVENOSA
69                                  Informou somente que é injetável
70                                                     não informada
71                                          Membro superior esquerdo
72                                                     intratraqueal
73                                                       antiemético
74                  câncer de mama RH+/HER2- avançado ou metastático
75                                                       intravenoso
76                                                     intrahepática
77                                                          Inalação
78                                                       Intravitrea
79                                              comprimido revestido
80                                                      Desconhecido
81          PRODUTO DE USO INTRAMUSCULAR (VIA DE ADM. NÃO INFORMADA)
82                                           Membro superior direito
83                                                boulos intravenosa
84                                                      nasogástrica
85                                                         Injetavel
87                                                           Injeção
88                                                        Inalatório
90                                                 Em ambos os olhos
91                                              corpo intracavernoso
92                                     questionado, mas desconhecido
93                                                     NÃO INFORMADO
94                                                          Ignorado
95                                                      desconhecido
96                                   administrado via sonda gástrica
97                                                          inalação
98                                                        endovenoso
99                                                        endovenosa
100                                                         Espinhal
101                                                         espinhal
102                                                    não informado
103                                                       uso ocular
104                                                      Intravítrea
105                                         Oral Formulation: Tablet
106            Oral Formulation: Unknown / Oral Formulation: Unknown
107                                                Intravenoso bolus
108                                         membro superior esquerdo
109                                                      retrotulbar
110                                          membro superior direito
111                                                          injeção
112                                        Membro superior esquerdo.
113                                                         Psoríase
114                                          Gotejamento intravenoso
115                                                   via endovenosa
116       Genuxal 1.200mg diluído em 500ml de soro fisiológico 0,9%,
117      asma súbita de difícil controle/ predominantemente alérgica
118                                                       Inalatória
119                                   Músculo vasto lateral esquerdo
120                            músculo vasto lateral da coxa direito
121                        Produto de uso oral (porem não informado)
122                            Intravenous (not otherwise specified)
123                                                    Braço direito
124                                                   Braço esquerdo
125                                                   braço esquerdo
127                                                  intraperitoneal
128                                                    INTRAMUSCULAR
129                                                     Subcutaneous
130                                                    braço direito
131                                                      Nasoenteral
132                                         Membro superior esquerda
133                                                           Ocular
135                                                       SUBCUTÂNEA
136                                                        injetável
137                                                   Inhalation use
138                                                             Oral
139                                                      Intravenosa
140                                                              N/I
141                                                    Intravascular
143                                                          UNKNOWN
144                                             UNK Formulation: UNK
145                                Subcutaneous Formulation: Unknown
146                                               Sonda nasogástrica
147                    intravenoso (não especificado de outra forma)
148                    Respiratory (inhalation) Formulation: Aerosol
149                                        Oral Formulation: Capsule
150                                                          Unknown
151                                                          unknown
152                             Intramuscular Formulation: Injection
153                                   administrada no braço esquerdo
154                                                   Não perguntado
155                                   administrado no braço esquerdo
157                             Oral Formulation: Film-coated tablet
158                                                         Inalador
159                       type 2 diabetes (Type 2 diabetes mellitus)
160                                                    intrasinovial
162                                    administrado no braço direito
163                                                    Não Informado
164                                    Administrado no braço direito
165                                                               NF
166            Respiratory (inhalation) Formulation: Inhalant Powder
168                                    administrada no braço direito
169                                   Administrado no braço esquerdo
170                                      Não informada pelo relator.
171                                                    Não Informada
172                                       Não Informada pelo Relator
173                                                           200 MG
174                                               300 MG - 2X AO DIA
175                                    Administrada no braço direito
176                                via desconhecida no braço direito
177                                  braço direito, via desconhecida
178                              via desconhecida, no braço esquerdo
179                                                     respiratória
180                                                              Dor
181                         administrada no musculo deltoide direito
183                                                       inalatório
184                            Aplicação em membro superior esquerdo
185                               Subcutaneous Formulation:  Unknown
186                                                        INJETÁVEL
187                                   Administrada no braço esquerdo
189                                                       19-01-2021
190                                                       27-05-2020
191                                              barriga e antebraço
192                                                   Vaginal e oral
193                                                    Gastroenteral
194                                                       Endovenoso
195                                              Infusão intravenosa
196                                                      Intravítreo
197                                                       subcutâneo
198                                                     Intravitreal
199                                                         INALANTE
200                                                              UNK
201                                                 Auricular (otic)
202                              INTRAVENOUS OTHERWISE NOT SPECIFIED
203                                                             N.I.
205                                          GOTEJAMENTO INTRAVENOSO
206                      INTRAVENOSA DE OUTRA FORMA NÃO ESPECIFICADA
207                                                   Gotejamento IV
208                                                     intravitreal
209                                                         inalador
210                                                      Intra-nasal
212                                                          Inalado
213                                       aplicação no vasto lateral
214                                                     nasogástrico
215                                                      intravitrea
216                                        Acromegalia (Acromegalia)
217                                                          INJEÇÃO
218                        todos por via endovenosa para pré-infusão
219                              por via endovenosa para pré-infusão
220                                                     Coxa direita
221                            Localização Anatômica: braço esquerdo
222                             Outra via de administração (Infusão)
223                                                          Enteral
224             via intravenosa (1 mg/kg, a cada 3 semanas x 4 doses
225                                Via de administração desconhecida
226                                   Intramuscular no braço direito
227                                   intramuscular no braço direito
228                                                ignorado regime 4
229                                                ignorado regime 3
230                                                ignorado regime 2
231                                                         ignorado
232                                                     Não relatada
233                                                   USO INTRANASAL
234                                              Circuito de Infusão
236                               Via de administração não informada
237                                                     Transmamaria
238                                                    não conhecida
239                                               Sonda nasoentérica
240                         Via de administração do paciente - outra
242                     2 cápsulas via oral e 2 cápsulas via vaginal
243                                      Intravenoso por gotejamento
244                                                Sonda nasoenteral
245                                                      INTRAVENOSA
246                                                       Endovenosa
247                                         injeção não especificada
248                          Não especificado a via de administração
249                            Via de administração não especificada
250                                                          infusão
254                                         Injeção não especificada
255                                                          Infusão
257                                                           ocular
258                                                Tubo nasogástrico
259                                                    intrameníngea
260                                                               EV
261                                                   ventro-gluteal
262                                                      intracórnea
263                                       E2B R2 Code: 065 - Unknown
264                                                   Via inalatória
265                                                         Via oral
266                                                            oral
267                                                       Subcutânea
268                                         Respiratory (inhalation)
269            Vacinada no braço direito, E2B R2 Code: 065 - Unknown
271                                                        "Injeção"
272                                         E2B R2 Code: 050 - Other
273                                                          enteral
274                         Desconhecido, E2B R2 Code: 065 - Unknown
275             injeção não especificada, E2B R2 Code: 065 - Unknown
276             injeção não especificado, E2B R2 Code: 065 - Unknown
277             Injeção não especificada, E2B R2 Code: 065 - Unknown
278                                                       INTRATECAL
279                              enteral, E2B R2 Code: 065 - Unknown
280                                                    Intramuscular
281                                                SUBCLAVIA DIREITA
282                                                       subcutanea
283                                                      ENDOVENOSA
284                                                 intravenosa&#39,
285                                                        Injetável
286                                                               IN
287                                                         Uso oral
288                              Injetável, E2B R2 Code: 050 - Other
289                                                               IV
290                                                               VO
291                                                     Intravenosa
292                                                via intramuscular
293                                                  via intravenosa
294                                                       Intratecal
295                                                      Sub cutânea
296                                                            Oral
297                                             Infusão intravenosa
298                                                            ORAL
299                                                         EV BOLUS
300                                                      Intratecal
301                                                               ev
302                                                  Via intravenosa
303                                                 Via intravenosa
304                                                             ORAL
305                    infusão port-a-cath, E2B R2 Code: 050 - Other
306                                                          INFUSÃO
307                                                         INFUSÃO
308          Injetável via veia periférica, E2B R2 Code: 050 - Other
309                                               Infusão endovenosa
310                                                         via oral

In [7]:

silver["VIA_ADMINISTRACAO_CHAVE"].value_counts()

VIA_ADMINISTRACAO_CHAVE
P               755
desconhecido    516
O               253
TD              139
Inhal            96
Instill          50
N                21
SL               16
V                11
R                10
Implant           9
Name: count, dtype: int64

In [ ]:
silver.query("VIA_ADMINISTRACAO_CHAVE=='desconhecido'")["VIA_ADMINISTRACAO"].value_counts()

VIA_ADMINISTRACAO
Transplacental                                                 7
tranplacental                                                  7
transmamária                                                   4
E2B R2 Code: 065 - Unknown                                     2
Transplacentária                                               2
E2B R2 Code: 050 - Other                                       2
desconhecida                                                   2
Unknown                                                        2
transplacentária                                               2
outra                                                          2
Endenosa                                                       1
intra- vitrea                                                  1
IVAD                                                           1
MSE                                                            1
EV,,                                                           1
mse                                                            1
VIA TÓPICA                                                     1
EV4E84346                                                      1
Via subdérrmica                                                1
PERITONEAL                                                     1
VL. D                                                          1
VL.E                                                           1
Frasco                                                         1
it                                                             1
dermica                                                        1
dental                                                         1
DESCONHECIDO                                                   1
Medicamento utilizado pela mae                                 1
Não informada                                                  1
Dose 3                                                         1
Dose 2                                                         1
Dose 1                                                         1
Desconhecida                                                   1
Capilar                                                        1
não informada                                                  1
Membro superior esquerdo                                       1
intratraqueal                                                  1
antiemético                                                    1
câncer de mama RH+/HER2- avançado ou metastático               1
intrahepática                                                  1
comprimido revestido                                           1
Desconhecido                                                   1
PRODUTO DE USO INTRAMUSCULAR (VIA DE ADM. NÃO INFORMADA)       1
Membro superior direito                                        1
Em ambos os olhos                                              1
questionado, mas desconhecido                                  1
NÃO INFORMADO                                                  1
Ignorado                                                       1
desconhecido                                                   1
não informado                                                  1
Oral Formulation: Unknown / Oral Formulation: Unknown          1
membro superior esquerdo                                       1
retrotulbar                                                    1
membro superior direito                                        1
Membro superior esquerdo.                                      1
Psoríase                                                       1
Genuxal 1.200mg diluído em 500ml de soro fisiológico 0,9%,     1
asma súbita de difícil controle/ predominantemente alérgica    1
Músculo vasto lateral esquerdo                                 1
músculo vasto lateral da coxa direito                          1
Produto de uso oral (porem não informado)                      1
Braço direito                                                  1
Braço esquerdo                                                 1
braço esquerdo                                                 1
braço direito                                                  1
Membro superior esquerda                                       1
N/I                                                            1
Intravascular                                                  1
UNKNOWN                                                        1
UNK Formulation: UNK                                           1
Subcutaneous Formulation: Unknown                              1
unknown                                                        1
administrada no braço esquerdo                                 1
Não perguntado                                                 1
administrado no braço esquerdo                                 1
type 2 diabetes (Type 2 diabetes mellitus)                     1
intrasinovial                                                  1
administrado no braço direito                                  1
Não Informado                                                  1
Administrado no braço direito                                  1
NF                                                             1
administrada no braço direito                                  1
Administrado no braço esquerdo                                 1
Não informada pelo relator.                                    1
Não Informada                                                  1
Não Informada pelo Relator                                     1
200 MG                                                         1
300 MG - 2X AO DIA                                             1
Administrada no braço direito                                  1
via desconhecida no braço direito                              1
braço direito, via desconhecida                                1
via desconhecida, no braço esquerdo                            1
Dor                                                            1
administrada no musculo deltoide direito                       1
Aplicação em membro superior esquerdo                          1
Subcutaneous Formulation:  Unknown                             1
Administrada no braço esquerdo                                 1
19-01-2021                                                     1
27-05-2020                                                     1
barriga e antebraço                                            1
UNK                                                            1
N.I.                                                           1
aplicação no vasto lateral                                     1
Acromegalia (Acromegalia)                                      1
Coxa direita                                                   1
Localização Anatômica: braço esquerdo                          1
Via de administração desconhecida                              1
ignorado regime 4                                              1
ignorado regime 3                                              1
ignorado regime 2                                              1
ignorado                                                       1
Não relatada                                                   1
Via de administração não informada                             1
Transmamaria                                                   1
não conhecida                                                  1
Via de administração do paciente - outra                       1
Não especificado a via de administração                        1
Via de administração não especificada                          1
ventro-gluteal                                                 1
intracórnea                                                    1
Vacinada no braço direito, E2B R2 Code: 065 - Unknown          1
Desconhecido, E2B R2 Code: 065 - Unknown                       1
injeção não especificada, E2B R2 Code: 065 - Unknown           1
injeção não especificado, E2B R2 Code: 065 - Unknown           1
Injeção não especificada, E2B R2 Code: 065 - Unknown           1
enteral, E2B R2 Code: 065 - Unknown                            1
SUBCLAVIA DIREITA                                              1
IN                                                             1
Injetável, E2B R2 Code: 050 - Other                            1
infusão port-a-cath, E2B R2 Code: 050 - Other                  1
Injetável via veia periférica, E2B R2 Code: 050 - Other        1
NI                                                             1
Ampola                                                         1
PÓ LIOFILIZADO                                                 1
Via de administração não disponível                            1
LOCAL                                                          1
Aplicado no membro inferior direito                            1
GTM                                                            1
VIA IM                                                         1
Contínuo                                                       1
Não informado, E2B R2 Code: 065 - Unknown                      1
Transmamário                                                   1
Transplacentário                                               1
periferico                                                     1
medicamento utilizado pelo pai, E2B R2 Code: 065 - Unknown     1
NQ                                                             1
Via leite materno, E2B R2 Code: 050 - Other                    1
perioferico                                                    1
Deltóide Direito                                               1
product taken by father                                        1
Product taken by male partner                                  1
Questionado, mas não informado                                 1
SOG                                                            1
vacinada no braço direito, E2B R2 Code: 065 - Unknown          1
BIC                                                            1
LOCAL                                                          1
Periférico                                                     1
periferica                                                     1
vacinada no braço esquerdo, E2B R2 Code: 065 - Unknown         1
ENDOENOSA                                                      1
pulmonar                                                       1
ENDOENOSO                                                      1
SNG                                                            1
Via Intravascular                                              1
não informada via de administração                             1
sonda nasoenteral, E2B R2 Code: 050 - Other                    1
100mg 2 cps (1 cp manhã e 1 cp a noite)                        1
vacinado no braço esquerdo, E2B R2 Code: 065 - Unknown         1
endovanosa                                                     1
Via leite materno                                              1
Intravenosa, E2B R2 Code: 065 - Unknown                        1
SUBCULTÂNEA                                                    1
e                                                              1
Unknown, E2B R2 Code: 065 - Unknown                            1
Deltóide Esquerdo                                              1
Nos pulsos                                                     1
Região do abdômen                                              1
Injeção, E2B R2 Code: 050 - Other                              1
administrada por volta de 8h30, E2B R2 Code: 065 - Unknown     1
GÁSTRICA                                                       1
Gastroenteral, E2B R2 Code: 050 - Other                        1
topica                                                         1
ni, E2B R2 Code: 065 - Unknown                                 1
questionado, mas não informado, E2B R2 Code: 065 - Unknown     1
CP                                                             1
TÓPICA                                                         1
intradermica                                                   1
IVBIC                                                          1
tópica                                                         1
gargarejo                                                      1
Peridual                                                       1
EVC                                                            1
Via oral, E2B R2 Code: 050 - Other                             1
IV/ IM                                                         1
IV- IM                                                         1
Nasogastric tube, E2B R2 Code: 050 - Other                     1
infiltration                                                   1
Desconhecida, E2B R2 Code: 065 - Unknown                       1
Tópica                                                         1
Intradermica                                                   1
Outra                                                          1
Endo                                                           1
Paciente informou "aplicação" porém não foi especificado       1
via intravascular                                              1
Deltoide esquerdo                                              1
Sonda (não especificada), E2B R2 Code: 050 - Other             1
Inalatória, E2B R2 Code: 050 - Other                           1
IV/SC                                                          1
via cateter                                                    1
desconhecido, E2B R2 Code: 065 - Unknown                       1
antes da quimioterapia                                         1
depois da quimioterapia                                        1
INJEÇÃO NÃO ESPECIFICADA, E2B R2 Code: 065 - Unknown           1
intraveosa                                                     1
via tubo nasogástrico, E2B R2 Code: 050 - Other                1
Vasto Lateral D                                                1
MSD                                                            1
Intravneosa                                                    1
VIA INTRECAL                                                   1
intra dermica                                                  1
injeção não especificada, E2B R2 Code: 050 - Other             1
envodenoso                                                     1
Localização anatômica: Vasto lateral direito                   1
aplicou Vick no pescoço                                        1
injação não especificada                                       1
intravemosa                                                    1
Gel                                                            1
intravenoso não especificado, E2B R2 Code: 050 - Other         1
2B06929 / 2B06986                                              1
Usa a dois anos                                                1
Transmammary                                                   1
Doença de Crohn                                                1
 Sol inj                                                       1
ANESTESIA LOCORREGIONAL                                        1
INTRADÉRMICA                                                   1
oftamológica                                                   1
VIA ENDOENOSA                                                  1
Braço não especificado                                         1
IT                                                             1
Intradérmica                                                   1
Não se aplica                                                  1
21J23KH                                                        1
UNKNOWN, E2B R2 Code: 065 - Unknown                            1
Endonenosa                                                     1
AMP                                                            1
otológica, E2B R2 Code: 065 - Unknown                          1
Periférica                                                     1
VI                                                             1
--2012                                                         1
arterial                                                       1
W024682                                                        1
SA                                                             1
ampola                                                         1
INTRAVASCULAR                                                  1
 IT                                                            1
gastroenteral, E2B R2 Code: 050 - Other                        1
cápsula                                                        1
INTRAVE                                                        1
Sol inj                                                        1
EV,                                                            1
Não informado                                                  1
tranplacentária                                                1
via desconhecida                                               1
Descohecido                                                    1
ni                                                             1
Other                                                          1
0108                                                           1
Via endotraqueal                                               1
VS                                                             1
gastrica                                                       1
in right eye                                                   1
Não infomado                                                   1
não informa                                                    1
deconhecido                                                    1
intracerebroventricular                                        1
intretecal                                                     1
via tópica                                                     1
Ampola                                                         1
Rota desconhecida                                              1
Oral / Transplacentária                                        1
VLE                                                            1
TÓPICA                                                         1
INTRADERMICA                                                   1
HDC                                                            1
Aplicou Vick no peito e no nariz                               1
duração de 2 anos, 6 meses e 16 dias                           1
comprimido                                                     1
via administração                                              1
Product taken by father                                        1
Não informada.                                                 1
não reportado                                                  1
VIA SUBCTÂNEA                                                  1
VIA SUBCTÃNEA                                                  1
iv/im                                                          1
BC                                                             1
Via subcuânea                                                  1
AD                                                             1
Intrevwnosa                                                    1
via tópica                                                     1
Route of administration not applicable                         1
Exposição pelo leite materno                                   1
endeveoso                                                      1
comprimidos                                                    1
VIA ALVEOLAR                                                   1
NEBULIZAÇÃO                                                    1
HDC B                                                          1
Tópica                                                         1

In [14]:

silver["VIA_ADMINISTRACAO_MAE_PAI_CHAVE"].value_counts()

VIA_ADMINISTRACAO_MAE_PAI_CHAVE
desconhecido    1849
P                 16
O                  9
Implant            1
Inhal              1
Name: count, dtype: int64

In [7]:
silver.head(2)

  DETENTOR_REGISTRO DETENTOR_REGISTRO_PADRONIZADO
0   ABACUS MEDICINE               ABACUS MEDICINE
1            ABBOLT                         ABBOT

In [8]:
silver.DETENTOR_REGISTRO.nunique()

6675

In [9]:
silver.DETENTOR_REGISTRO_PADRONIZADO.nunique()

271

In [10]:
silver.DETENTOR_REGISTRO_PADRONIZADO.value_counts().head(20)

DETENTOR_REGISTRO_PADRONIZADO
DESCONHECIDO              2080
ASTRAZENECA                284
PFIZER                     257
FIOCRUZ                    195
CRISTALIA                  176
JOHNSON & JOHNSON          161
BLAU FARMACÊUTICA          109
EMS                        103
UNIAO QUIMICA               97
MEDICAMENTO MANIPULADO      97
SINOVAC BIONTECH            94
SANOFI                      93
EUROFARMA                   87
ABL                         82
TEUTO                       79
HIPOLABOR                   76
HALEX ISTAR                 68
MERCK                       67
FRESENIUS KABI              60
INSTITUTO BUTANTAN          59
Name: count, dtype: int64

In [11]:
dim = silver[['DETENTOR_REGISTRO']].drop_duplicates().fillna('DESCONHECIDO')
dim.head(20)

                     DETENTOR_REGISTRO
0                      ABACUS MEDICINE
1                               ABBOLT
2                                ABBOT
3                         ABBOT BRASIL
4       ABBOT L: 0071/20 V: 31/01/2022
5       ABBOT L: 1040818 V: 31/03/2022
6   ABBOT LABORATORIUOS DO BRASIL LTDA
7                   ABBOTH BIOLOGICALS
8                               ABBOTT
9                          ABBOTT B.V.
10               ABBOTT BIOLOGICAL B.V
11                  ABBOTT BIOLOGICALS
12                       ABBOTT BRASIL
13                       ABBOTT BRAZIL
14                       ABBOTT CENTER
15                    ABBOTT DO BRASIL
16                 ABBOTT LABORATORIES
17         ABBOTT LABORATORIES LIMITED
18   ABBOTT LABORATORIO DO BRASIL LTDA
19       ABBOTT LABORATORIOS DO BRASIL

In [12]:
# termos genéricos que não diferenciam empresas farmacêuticas
STOPWORDS_EMPRESA = {
    "SA", "S/A", "S.A", "S.A.", "SA.", "S A",
    "LTDA", "LTD", "EIRELI", "ME", "EPP",
    "COMERCIO", "COMERCIAL", "INDUSTRIA", "INDUSTRIAL",
    "LABORATORIO", "LABORATORIOS", "LAB",
    "FARMACEUTICA", "FARMACEUTICO", "FARMACEUTICOS","PHARMA",
    "DO", "DA", "DE", "DOS", "DAS", "E",
}

def limpar_texto_empresa(texto: str) -> str:
    """Normaliza texto de nome de empresa para criar uma chave estável."""
    if pd.isna(texto):
        return ""
    
    s = str(texto).strip()
    s = unidecode(s)           # remove acentos
    s = s.upper()              # caixa alta
    s = re.sub(r"[^A-Z0-9 ]+", " ", s)  # tira pontuação
    tokens = [t for t in s.split() if t not in STOPWORDS_EMPRESA]
    s = " ".join(tokens)
    s = re.sub(r"\s+", " ", s).strip()  # colapsa espaços
    
    return s

def criar_key_detentor(texto: str) -> str:
    """Wrapper pra ficar semântico."""
    return limpar_texto_empresa(texto)

In [13]:
dim["DETENTOR_REGISTRO_VALOR"] = dim["DETENTOR_REGISTRO"].apply(criar_key_detentor)
dim["DETENTOR_REGISTRO_VALOR"].nunique()

5404

In [14]:
silver[['DETENTOR_REGISTRO_PADRONIZADO']].nunique()

DETENTOR_REGISTRO_PADRONIZADO    271
dtype: int64

In [15]:
dim = silver[['DETENTOR_REGISTRO_PADRONIZADO']].drop_duplicates().fillna('DESCONHECIDO')
dim["DETENTOR_REGISTRO_VALOR"] = dim["DETENTOR_REGISTRO_PADRONIZADO"].apply(criar_key_detentor)
dim["DETENTOR_REGISTRO_VALOR"].nunique()

265

In [16]:
dim.head()

    DETENTOR_REGISTRO_PADRONIZADO DETENTOR_REGISTRO_VALOR
0                 ABACUS MEDICINE         ABACUS MEDICINE
1                           ABBOT                   ABBOT
30                         ABBVIE                  ABBVIE
46                            ABL                     ABL
128           ACCORD FARMACÊUTICA                  ACCORD

In [17]:
freq = (
    dim
    .groupby(["DETENTOR_REGISTRO_VALOR", "DETENTOR_REGISTRO_PADRONIZADO"])
    .size()
    .reset_index(name="n")
)
freq.sort_values("n", ascending=False).head(10)

  DETENTOR_REGISTRO_VALOR DETENTOR_REGISTRO_PADRONIZADO  n
0         ABACUS MEDICINE               ABACUS MEDICINE  1
1                   ABBOT                         ABBOT  1
2                  ABBVIE                        ABBVIE  1
3                     ABL                           ABL  1
4                  ACCORD           ACCORD FARMACÊUTICA  1
5                    ACHE                          ACHÉ  1
6        ADC THERAPEUTICS              ADC THERAPEUTICS  1
7                   ADIUM                         ADIUM  1
8                  AIRELA                        AIRELA  1
9                   ALCON                         ALCON  1

In [18]:
dim_detentor = (
    freq
    .sort_values(["DETENTOR_REGISTRO_VALOR", "n"], ascending=[True, False])
    .drop_duplicates("DETENTOR_REGISTRO_VALOR")
    #.rename(columns={"DETENTOR_REGISTRO_PADRONIZADO": "DETENTOR_REGISTRO_CANONICO"})
    [["DETENTOR_REGISTRO_VALOR", "DETENTOR_REGISTRO_PADRONIZADO"]]
    .reset_index(drop=True)
)
dim_detentor.head()

  DETENTOR_REGISTRO_VALOR DETENTOR_REGISTRO_PADRONIZADO
0         ABACUS MEDICINE               ABACUS MEDICINE
1                   ABBOT                         ABBOT
2                  ABBVIE                        ABBVIE
3                     ABL                           ABL
4                  ACCORD           ACCORD FARMACÊUTICA

In [19]:
dim_detentor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DETENTOR_REGISTRO_VALOR        265 non-null    object
 1   DETENTOR_REGISTRO_PADRONIZADO  265 non-null    object
dtypes: object(2)
memory usage: 4.3+ KB

In [20]:
silver[['DETENTOR_REGISTRO_PADRONIZADO']].nunique()

DETENTOR_REGISTRO_PADRONIZADO    271
dtype: int64

In [21]:
dim_detentor =  silver[['DETENTOR_REGISTRO_PADRONIZADO']].drop_duplicates().fillna('DESCONHECIDO')
dim_detentor["DETENTOR_REGISTRO_VALOR"] = dim_detentor["DETENTOR_REGISTRO_PADRONIZADO"].apply(criar_key_detentor)
dim_detentor.insert(0, "DETENTOR_REGISTRO_CHAVE", range(1, len(dim_detentor) + 1))
dim_detentor.info()

<class 'pandas.core.frame.DataFrame'>
Index: 271 entries, 0 to 6764
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DETENTOR_REGISTRO_CHAVE        271 non-null    int64
 1   DETENTOR_REGISTRO_PADRONIZADO  271 non-null    object
 2   DETENTOR_REGISTRO_VALOR        271 non-null    object
dtypes: int64(1), object(2)
memory usage: 8.5+ KB

In [22]:
dim_detentor.DETENTOR_REGISTRO_CHAVE.nunique()

271

In [23]:
hist = silver.merge(dim_detentor, on="DETENTOR_REGISTRO_PADRONIZADO", how="left")
hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6765 entries, 0 to 6764
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DETENTOR_REGISTRO              6761 non-null   object
 1   DETENTOR_REGISTRO_PADRONIZADO  6765 non-null   object
 2   DETENTOR_REGISTRO_CHAVE        6765 non-null   int64
 3   DETENTOR_REGISTRO_VALOR        6765 non-null   object
dtypes: int64(1), object(3)
memory usage: 211.5+ KB

In [24]:
hist.head()

,DETENTOR_REGISTRO,DETENTOR_REGISTRO_PADRONIZADO,DETENTOR_REGISTRO_CHAVE,DETENTOR_REGISTRO_VALOR
0,ABACUS MEDICINE,ABACUS MEDICINE,1,ABACUS MEDICINE
1,ABBOLT,ABBOT,2,ABBOT
2,ABBOT,ABBOT,2,ABBOT
3,ABBOT BRASIL,ABBOT,2,ABBOT
4,ABBOT L: 0071/20 V: 31/01/2022,ABBOT,2,ABBOT

In [25]:
dim_detentor.DETENTOR_REGISTRO_PADRONIZADO.nunique()

271

In [26]:
dim_detentor.DETENTOR_REGISTRO_CHAVE.nunique()

271

In [27]:
hist.to_parquet(Path(project_root) / "data/02_silver/hist_dim_detentor_registro/hist_dim_detentor_registro.parquet", index=False)

# 🥇 Gold

In [28]:
hist.columns

Index(['DETENTOR_REGISTRO', 'DETENTOR_REGISTRO_PADRONIZADO',
       'DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR'],
      dtype='object')

In [29]:
dim = hist[['DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR']].drop_duplicates()
dim.to_parquet(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.parquet", index=False)

In [31]:

dim.to_csv(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.csv", sep=";", index=False)