# 🥉 Bronze | Vigimed MEDICAMENTOS

Raw Data
as is production, low quality

In [1]:
%run ../config/bootstrap.py

import pandas as pd 
from pathlib import Path
from utils import get_project_root , desagrupar_colunas_pipe
project_root = get_project_root()

In [2]:
path = Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(path) 
bronze.columns

Index(['IDENTIFICACAO_NOTIFICACAO', 'RELACAO_MEDICAMENTO_EVENTO',
       'NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC',
       'DETENTOR_REGISTRO', 'CONCENTRACAO', 'COMPONENTE_SUSPEITO',
       'ACAO_ADOTADA', 'PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO',
       'INDICACAO_MEDDRA', 'INDICACAO_RELATADA_NOTIFICADOR_INICIAL', 'DOSE',
       'FREQUENCIA_DOSE', 'POSOLOGIA', 'DURACAO', 'INICIO_ADMINISTRACAO',
       'FIM_ADMINISTRACAO', 'FORMA_FARMACEUTICA', 'VIA_ADMINISTRACAO',
       'VIA_ADMINISTRACAO_MAE_PAI', 'NUMELO_LOTE', 'ATUALIZADO'],
      dtype='object')

In [3]:
bronze.head(25)

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
0,BR-ANVISA-300000004,Suspeito,Oxacilina,Oxacillin sodium,J01CF,Teuto,None,None,None,None,None,None,250 milligram (mg),6 hora,None,4 dia,20181124,None,None,infusão intravenosa,None,5833018,2025-11-17
1,BR-ANVISA-300000005,Suspeito,Paracemol,Paracetamol,N02BE,None,None,None,Retirada do medicamento,None,None,None,None,None,None,None,20181122,20181122,None,oral,None,None,2025-11-17
2,BR-ANVISA-300000007,Suspeito,Diamox,Acetazolamide sodium,C03|N03AX|S01EC,None,None,None,Retirada do medicamento,None,None,None,250 milligram (mg),6 hora,250mg a cada 6 horas,None,20181103,20181115,None,oral,None,None,2025-11-17
3,BR-ANVISA-300000007,Suspeito,Hidantal,Phenytoin,N03AB,None,None,None,Retirada do medicamento,None,None,None,None,None,100mg a cada 8 horas,None,20181016,20181115,None,oral,None,None,2025-11-17
4,BR-ANVISA-300000008,Suspeito,Nitroglicerina,Glyceryl trinitrate,C01DA|C05AE,Cristália,None,None,None,None,None,None,None,None,None,None,20181024,None,None,infusão intravenosa,None,None,2025-11-17
5,BR-ANVISA-300000010,Suspeito,Macrodantina,Nitrofurantoin,J01XE,None,None,None,None,None,Infecção urinária,None,None,None,None,None,None,None,None,None,None,None,2025-11-17
6,BR-ANVISA-300000011,Suspeito,Dexa-Citoneurin,Cyanocobalamin|Dexamethasone|Pyridoxine hydrochloride|Thiamine hydrochloride,H02BX,Merck,None,None,Retirada do medicamento,None,None,não relatou,None,None,None,2 dia,20181126,None,None,intramuscular,None,None,2025-11-17
7,BR-ANVISA-300000012,Suspeito,Benzetacil,Benzathine benzylpenicillin,J01CE,Eurofarma,None,None,None,None,None,None,1200000 international unit ([iU]),None,None,None,20181017,None,solução injetável,intramuscular,None,503570A,2025-11-17
8,BR-ANVISA-300000014,Suspeito,Reuquinol,Hydroxychloroquine sulfate,P01BA,APSEN FARMACEUTICA S/A,None,None,Retirada do medicamento,None,Distúrbio autoimune,Doença autoimune,None,None,"400mg, 1 por dia",9 mês,20170610,None,None,oral,None,None,2025-11-17
9,BR-ANVISA-300000015,Suspeito,Anfotericina b,Amphotericin b,J02AA,TEVA,None,None,Sem alteração da dose,None,Paracoccidioidomicose,diagnóstico de paracoccidioidomicose,None,None,None,None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
10,BR-ANVISA-300000016,Suspeito,Oxaliplatina,Oxaliplatin,L01XA,EUROFARMA,None,None,Sem alteração da dose,None,None,ANTINEOPLÁSICO,183 milligram (mg),cíclico,"183MG, CÍCLICA",None,20181019,None,None,intravenosa (não especificado),None,None,2025-11-17
11,BR-ANVISA-300000017,Suspeito,Dimorf,Morphine sulfate,N02AA,CRISTÁLIA,None,None,Sem alteração da dose,None,None,"QUEIXA DE DOR. EM FACE DA INTENSA AGITAÇÃO E DOR DO PACIENTE, FAMILIARES SOLICITAM A NÃO REVERSÃO SATISFATÓRIO DE OPIÓIDE EM VISTA DO CONTROLE SINTOMÁTICO",None,None,"2MG, 6 EM 6 HORAS",None,20181017,20181022,None,intravenosa (não especificado),None,None,2025-11-17
12,BR-ANVISA-300000018,Suspeito,Dimorf,Morphine sulfate,N02AA,CRISTALIA,None,None,Não aplicável,None,None,"Paciente queixa de dor em HCE, sem outras queixas",2 milligram (mg),4 hora,"2MG, 4 EM 4 HORAS EM BOLUS",3 dia,20181026,None,None,intravenosa (não especificado),None,None,2025-11-17
13,BR-ANVISA-300000019,Suspeito,Dimorf,Morphine sulfate,N02AA,CRISTÁLIA,None,None,Retirada do medicamento,None,None,"O' Paciente admitida a esta unidade proveniente do plantão, pré cirúrgica de retossigmoidectomia abdominal..",2 milligram (mg),4 hora,"2MG, 4 EM 4 HORAS EM BOLUS",None,20181018,20181018,None,intravenosa (não especificado),None,None,2025-11-17
14,BR-ANVISA-300000020,Suspeito,Oxaliplatina,Oxaliplatin,L01XA,GLENMARK,None,None,Sem alteração da dose,None,None,ANTINEOPLÁSICO,101 milligram (mg),1 cíclico,"101MG, CÍCLICA",None,20180521,None,None,intravenosa (não especificado),None,None,2025-11-17
15,BR-ANVISA-300000021,Suspeito,Oxaliplatina,Oxaliplatin,L01XA,GLENMARK,None,None,Retirada do medicamento,None,None,ANTINEOPLASICO,221 milligram (mg),cíclico,"221,5MG, CÍCLICA",None,20180911,None,None,intravenosa (não especificado),None,None,2025-11-17
16,BR-ANVISA-300000022,Suspeito,Gynera,Ethinylestradiol|Gestodene,G03AA,BAYER,None,None,Sem alteração da dose,None,None,MÉTODO ANTICONCEPTIVO,None,1 dia,"GESTO0,0075MG/ETINILES0,03MG, 1 CP AO DIA",None,None,2017,None,oral,None,None,2025-11-17
17,BR-ANVISA-300000023,Suspeito,Hetori,Etoricoxib,M01AH,Schering-Plough Indústria Farmacêutica Ltda,None,None,Não aplicável,None,Tendinite,Tendinite no quadril direito,90 milligram (mg),1 dia,"90mg, 1 comprimido 1x/dia",None,20181202,20181208,None,oral,None,None,2025-11-17
18,BR-ANVISA-300000024,Suspeito,Genuxal,Cyclophosphamide,L01AA,Baxter,None,None,Não aplicável,None,None,"Paciente portadora de carcinoma ductal infiltrante, necessitando de receber quimioterapia adjuvante.",None,None,"1000 mg, 950 mg",5 minuto,None,None,None,intravenosa (não especificado),None,None,2025-11-17
19,BR-ANVISA-300000025,Suspeito,Dipirona,Metamizole sodium,N02BB,Teuto,None,None,None,None,None,None,1 gram (g),None,None,None,20181201,None,None,infusão intravenosa,None,26583514,2025-11-17
20,BR-ANVISA-300000026,Suspeito,Docelibbs,Docetaxel,L01CD,LIBBS,None,None,Não aplicável,None,None,Paciente portadora de carcinoma ductal infiltrante.,None,None,"80 MG, 135 MG",5 minuto,20181204,None,None,intravenosa (não especificado),None,None,2025-11-17
21,BR-ANVISA-300000032,Suspeito,Cetoprofeno,Ketoprofen,M01AE|M02AA,None,None,None,None,None,None,None,None,None,"100mg, 12/12h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
22,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,D06AX|J01GB|S01AA|S02AA|S03AA,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
23,BR-ANVISA-300000032,Suspeito,Ondansetron,Ondansetron,A04AA,None,None,None,None,None,None,None,4 milligram (mg),6 hora,"4 mg, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
24,BR-ANVISA-300000032,Suspeito,Dipirona,Metamizole sodium,N02BB,None,None,None,None,None,None,None,None,None,"1g, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17

# Funcao Desagrupar

In [4]:
# Aplicar desagregação usando função do módulo utils
# A função desagrupar_colunas_pipe trata valores separados por pipe "|" ou padrões X000D
# As colunas NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG e CODIGO_ATC
# podem ter valores agrupados, indicando múltiplos valores na mesma linha

colunas_para_desagrupar = ['ATC_CODE_LEVEL_4']
print(f"Shape antes da desagregação: {bronze.shape}") 
bronze_desagrupado = desagrupar_colunas_pipe(bronze.rename(columns={'CODIGO_ATC': 'ATC_CODE_LEVEL_4'}), colunas_para_desagrupar)
print(f"Shape depois da desagregação: {bronze_desagrupado.shape}")
print(f"\nLinhas criadas: {len(bronze_desagrupado) - len(bronze)}")

Shape antes da desagregação: (552887, 23)
Shape depois da desagregação: (748297, 23)

Linhas criadas: 195410

# Checks

## 300000032

In [5]:
bronze.query("IDENTIFICACAO_NOTIFICACAO=='BR-ANVISA-300000032'")

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
21,BR-ANVISA-300000032,Suspeito,Cetoprofeno,Ketoprofen,M01AE|M02AA,None,None,None,None,None,None,None,None,None,"100mg, 12/12h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
22,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,D06AX|J01GB|S01AA|S02AA|S03AA,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
23,BR-ANVISA-300000032,Suspeito,Ondansetron,Ondansetron,A04AA,None,None,None,None,None,None,None,4 milligram (mg),6 hora,"4 mg, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
24,BR-ANVISA-300000032,Suspeito,Dipirona,Metamizole sodium,N02BB,None,None,None,None,None,None,None,None,None,"1g, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
25,BR-ANVISA-300000032,Suspeito,Indapamida,Indapamide,C03BA,None,None,None,None,None,None,None,1.5 milligram (mg),1 dia,"1,5mg, 24/24h",None,None,None,None,oral,None,None,2025-11-17

In [6]:
bronze_desagrupado.query("IDENTIFICACAO_NOTIFICACAO=='BR-ANVISA-300000032'")

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,ATC_CODE_LEVEL_4,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
24,BR-ANVISA-300000032,Suspeito,Cetoprofeno,Ketoprofen,M01AE,None,None,None,None,None,None,None,None,None,"100mg, 12/12h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
25,BR-ANVISA-300000032,Suspeito,Cetoprofeno,Ketoprofen,M02AA,None,None,None,None,None,None,None,None,None,"100mg, 12/12h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
26,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,D06AX,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
27,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,J01GB,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
28,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,S01AA,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
29,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,S02AA,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
30,BR-ANVISA-300000032,Suspeito,Gentamicin,Gentamicin,S03AA,None,None,None,None,None,None,None,240 milligram (mg),1 dia,"240mg, 24/24h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
31,BR-ANVISA-300000032,Suspeito,Ondansetron,Ondansetron,A04AA,None,None,None,None,None,None,None,4 milligram (mg),6 hora,"4 mg, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
32,BR-ANVISA-300000032,Suspeito,Dipirona,Metamizole sodium,N02BB,None,None,None,None,None,None,None,None,None,"1g, 6/6h",None,None,None,None,intravenosa (não especificado),None,None,2025-11-17
33,BR-ANVISA-300000032,Suspeito,Indapamida,Indapamide,C03BA,None,None,None,None,None,None,None,1.5 milligram (mg),1 dia,"1,5mg, 24/24h",None,None,None,None,oral,None,None,2025-11-17

## BR-ANVISA-300328665

In [7]:
bronze.query("IDENTIFICACAO_NOTIFICACAO=='BR-ANVISA-300328665'")

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
524203,BR-ANVISA-300328665,Concomitante,Lactulose,Lactulose,A05BA_x000D_|A06AD,None,None,None,None,None,Constipação,Constipação,10 millilitre (mL),2 por 12 hora,667 mg/ml – 10 ml de 12/12h,None,20240323,20240522,Cápsula,Via oral,None,None,2025-11-17
524204,BR-ANVISA-300328665,Concomitante,Omeprazol,Omeprazole,A02BC,None,None,None,None,None,Profilaxia de úlcera gástrica,Profilaxia de úlcera gástrica,40 milligram (mg),1 por 1 dia,20 mg – 2 cáp em jejum,None,20240323,20240621,Cápsula,Via oral,None,None,2025-11-17
524205,BR-ANVISA-300328665,Concomitante,Gabapentina,Gabapentin,N02BF_x000D_|N03AX_x000D_|N07XX,None,None,None,None,None,Dor neuropática,None,300 milligram (mg),2 por 12 hora,300 mg – 1 cáp à noite 12/12h,None,20231130,20240603,Cápsula,Via oral,None,None,2025-11-17
524206,BR-ANVISA-300328665,Concomitante,Diazepam,Diazepam,M03BX_x000D_|N03AE_x000D_|N05BA,None,None,None,None,None,Ansiedade,Ansiedade,5 milligram (mg),1 por 1 dia,5 mg – 1 comp à noite,None,20240323,20240621,Comprimido,Via oral,None,None,2025-11-17
524207,BR-ANVISA-300328665,Concomitante,Dipirona,Metamizol de magnésio,N02BB,None,None,None,None,None,Dor oncológica,Dor oncológica,1 gram (g),6 por 4 hora,500 mg – 2 comp de 4/4h,None,20240323,20240621,Comprimido,Via oral,None,None,2025-11-17
524208,BR-ANVISA-300328665,Concomitante,Ondansetron,Ondansetrona,A04AA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
524209,BR-ANVISA-300328665,Concomitante,Difenidramina,Cloridrato de difenidramina,D04AA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,25 milligram (mg),cíclico,25 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
524210,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,A01AC_x000D_|C05AA_x000D_|D07AB_x000D_|H02AB_x000D_|R01AD_x000D_|R03BA_x000D_|S01BA_x000D_|S02BA_x000D_|S03BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
524211,BR-ANVISA-300328665,Suspeito,Paclitaxel,Paclitaxel,C01EB_x000D_|L01CD,Accord Farmacêutica Ltda._x0009_,None,None,None,None,Carcinoma lobular da mama,Carcinoma lobular infiltrante + carcinoma lobular “in situ”,110.8 milligram (mg),cíclico,"110,8 mg (",None,20240415,20240415,Solução injetável,Via intravenosa,None,2310460,2025-11-17

In [8]:
bronze.query("IDENTIFICACAO_NOTIFICACAO=='BR-ANVISA-300328665' and NOME_MEDICAMENTO_WHODRUG=='Dexametasona'")

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
524210,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,A01AC_x000D_|C05AA_x000D_|D07AB_x000D_|H02AB_x000D_|R01AD_x000D_|R03BA_x000D_|S01BA_x000D_|S02BA_x000D_|S03BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17

In [9]:
bronze_desagrupado.query("IDENTIFICACAO_NOTIFICACAO=='BR-ANVISA-300328665'and NOME_MEDICAMENTO_WHODRUG=='Dexametasona'")

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,ATC_CODE_LEVEL_4,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,ATUALIZADO
707590,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,A01AC,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707591,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,C05AA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707592,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,D07AB,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707593,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,H02AB,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707594,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,R01AD,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707595,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,R03BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707596,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,S01BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707597,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,S02BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17
707598,BR-ANVISA-300328665,Concomitante,Dexametasona,Dexamethasone,S03BA,None,None,None,None,None,Pré-medicação para quimioterapia,Pré-medicação para quimioterapia,8 milligram (mg),cíclico,8 mg / ciclo de QT,None,20240415,20240415,Solução injetável,Via intravenosa,None,None,2025-11-17