#  ⭐ `dim_notificacoes`

In [1]:
%run ../../config/bootstrap.py

import pandas as pd
import numpy as np
from pathlib import Path
from utils import get_project_root, normalize_date_column, normalize_rows, apply_mappings, fuzzy_merge##, normalize_duration, expandir_gravidade_wide
project_root = get_project_root()

In [2]:
project_root

WindowsPath('C:/Users/janet/Documents/VigiMed/vigimed')

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/anvisa/Notificacoes/Notificacoes.parquet"
bronze = pd.read_parquet(path) 
bronze.columns

Index(['UF', 'TIPO_ENTRADA_VIGIMED', 'RECEBIDO_DE',
       'IDENTIFICACAO_NOTIFICACAO', 'DATA_INCLUSAO_SISTEMA',
       'DATA_ULTIMA_ATUALIZACAO', 'DATA_NOTIFICACAO', 'TIPO_NOTIFICACAO',
       'NOTIFICACAO_PARENT_CHILD', 'DATA_NASCIMENTO', 'IDADE_MOMENTO_REACAO',
       'GRUPO_IDADE', 'IDADE_GESTACIONAL_MOMENTO_REACAO', 'SEXO', 'GESTANTE',
       'LACTANTE', 'PESO_KG', 'ALTURA_CM', 'REACAO_EVENTO_ADVERSO_MEDDRA',
       'GRAVE', 'GRAVIDADE', 'DESFECHO', 'DATA_INICIO_HORA', 'DATA_FINAL_HORA',
       'DURACAO', 'RELACAO_MEDICAMENTO_EVENTO', 'NOME_MEDICAMENTO_WHODRUG',
       'ACAO_ADOTADA', 'NOTIFICADOR', 'ATUALIZADO'],
      dtype='object')

In [4]:
bronze.head(2)

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,ACAO_ADOTADA,NOTIFICADOR,ATUALIZADO
0,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300212656,20230928,20230928,None,Notificaçăo espontânea,None,19900131,30 ano,None,None,Feminino,Năo,Năo,68.0,165,Hemiparesia,Sim,Outro efeito clinicamente significativo,Recuperado,20210125,20210206,12 dia,Concomitante,Tamisa,Năo aplicável,Médico,2026-01-15
1,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300208322,20230901,20230901,None,Notificaçăo espontânea,None,None,None,None,None,Feminino,Năo,Năo,None,None,Cefaleia,Năo,Outro efeito clinicamente significativo,Desconhecido,20210122,None,None,Suspeito,CoronaVac,Năo aplicável,Consumidor ou outro năo profissional de saúde,2026-01-15

# 🥈 Silver

normalized data, medium quality

In [5]:
silver = bronze.copy()
silver.shape

(311134, 30)

## ✅ hash

In [6]:
from utils import build_row_hash

silver["HASH_BRONZE"] = build_row_hash(
    silver, 
    silver.columns.difference(['ATUALIZADO']).tolist(), 
    algo="sha256", 
    sep="|"
)

## ✅ Missing

In [7]:
silver.isna().sum()

UF                                   81507
TIPO_ENTRADA_VIGIMED                    70
RECEBIDO_DE                          55666
IDENTIFICACAO_NOTIFICACAO                0
DATA_INCLUSAO_SISTEMA                    0
DATA_ULTIMA_ATUALIZACAO                 70
DATA_NOTIFICACAO                    151881
TIPO_NOTIFICACAO                         0
NOTIFICACAO_PARENT_CHILD            310006
DATA_NASCIMENTO                      80710
IDADE_MOMENTO_REACAO                110538
GRUPO_IDADE                         183974
IDADE_GESTACIONAL_MOMENTO_REACAO    310802
SEXO                                 11687
GESTANTE                            160811
LACTANTE                            160814
PESO_KG                             189266
ALTURA_CM                           244428
REACAO_EVENTO_ADVERSO_MEDDRA           317
GRAVE                                69292
GRAVIDADE                           168932
DESFECHO                             49933
DATA_INICIO_HORA                     85453
DATA_FINAL_HORA                     153322
DURACAO                             204258
RELACAO_MEDICAMENTO_EVENTO               1
NOME_MEDICAMENTO_WHODRUG               520
ACAO_ADOTADA                        126091
NOTIFICADOR                          18164
ATUALIZADO                               0
HASH_BRONZE                              0
dtype: int64

In [8]:
hist_silver = silver.copy()
for col in silver.select_dtypes(include=['object']).columns:
    silver[col] = normalize_rows(silver[col])

In [9]:
hist_silver.isna().sum()

UF                                   81507
TIPO_ENTRADA_VIGIMED                    70
RECEBIDO_DE                          55666
IDENTIFICACAO_NOTIFICACAO                0
DATA_INCLUSAO_SISTEMA                    0
DATA_ULTIMA_ATUALIZACAO                 70
DATA_NOTIFICACAO                    151881
TIPO_NOTIFICACAO                         0
NOTIFICACAO_PARENT_CHILD            310006
DATA_NASCIMENTO                      80710
IDADE_MOMENTO_REACAO                110538
GRUPO_IDADE                         183974
IDADE_GESTACIONAL_MOMENTO_REACAO    310802
SEXO                                 11687
GESTANTE                            160811
LACTANTE                            160814
PESO_KG                             189266
ALTURA_CM                           244428
REACAO_EVENTO_ADVERSO_MEDDRA           317
GRAVE                                69292
GRAVIDADE                           168932
DESFECHO                             49933
DATA_INICIO_HORA                     85453
DATA_FINAL_HORA                     153322
DURACAO                             204258
RELACAO_MEDICAMENTO_EVENTO               1
NOME_MEDICAMENTO_WHODRUG               520
ACAO_ADOTADA                        126091
NOTIFICADOR                          18164
ATUALIZADO                               0
HASH_BRONZE                              0
dtype: int64

In [10]:
hist_silver.shape

(311134, 31)

## ✅ DATAS

In [11]:
colunas_data = ["DATA_INCLUSAO_SISTEMA", "DATA_ULTIMA_ATUALIZACAO", "DATA_NOTIFICACAO", "DATA_NASCIMENTO", "DATA_INICIO_HORA", "DATA_FINAL_HORA"]

In [12]:
hist_silver[colunas_data].info()
hist_silver[colunas_data].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311134 entries, 0 to 311133
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   DATA_INCLUSAO_SISTEMA    311134 non-null  object
 1   DATA_ULTIMA_ATUALIZACAO  311064 non-null  object
 2   DATA_NOTIFICACAO         159253 non-null  object
 3   DATA_NASCIMENTO          230424 non-null  object
 4   DATA_INICIO_HORA         225681 non-null  object
 5   DATA_FINAL_HORA          157812 non-null  object
dtypes: object(6)
memory usage: 14.2+ MB

,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,DATA_NASCIMENTO,DATA_INICIO_HORA,DATA_FINAL_HORA
0,20230928,20230928,None,19900131,20210125,20210206
1,20230901,20230901,None,None,20210122,None
2,20231006,20231006,None,19710522,20210203,None
3,20250721,20250721,None,19741123,20210302,None
4,20230927,20230927,None,None,None,None

In [13]:
for col in colunas_data:
    if col in hist_silver.columns:
        hist_silver[col] = normalize_date_column(hist_silver[col])

In [14]:
hist_silver[colunas_data].info()
hist_silver[colunas_data].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311134 entries, 0 to 311133
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   DATA_INCLUSAO_SISTEMA    311134 non-null  datetime64[ns]
 1   DATA_ULTIMA_ATUALIZACAO  311064 non-null  datetime64[ns]
 2   DATA_NOTIFICACAO         158960 non-null  datetime64[ns]
 3   DATA_NASCIMENTO          229298 non-null  datetime64[ns]
 4   DATA_INICIO_HORA         169043 non-null  datetime64[ns]
 5   DATA_FINAL_HORA          107847 non-null  datetime64[ns]
dtypes: datetime64[ns](6)
memory usage: 14.2 MB

,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,DATA_NASCIMENTO,DATA_INICIO_HORA,DATA_FINAL_HORA
0,2023-09-28,2023-09-28,NaT,1990-01-31,2021-01-25,2021-02-06
1,2023-09-01,2023-09-01,NaT,NaT,2021-01-22,NaT
2,2023-10-06,2023-10-06,NaT,1971-05-22,2021-02-03,NaT
3,2025-07-21,2025-07-21,NaT,1974-11-23,2021-03-02,NaT
4,2023-09-27,2023-09-27,NaT,NaT,NaT,NaT

In [15]:
hist_silver.shape

(311134, 31)

## ✅ Mappings

- UF
- TIPO_ENTRADA_VIGIMED
- RECEBIDO_DE
- TIPO_NOTIFICACAO
- NOTIFICACAO_PARENT_CHILD
- GRUPO_IDADE
- SEXO
- GESTANTE
- LACTANTE
- GRAVE
- GRAVIDADE
- DESFECHO
- RELACAO_MEDICAMENTO_EVENTO
- ACAO_ADOTADA
- NOTIFICADOR

In [16]:
# UF
uf_map = {
    "AC": 1, "AL": 2, "AP": 3, "AM": 4, "BA": 5, "CE": 6, "DF": 7, "ES": 8, "GO": 9, "MA": 10, 
    "MT": 11, "MS": 12, "MG": 13, "PA": 14, "PB": 15, "PR": 16, "PE": 17, "PI": 18, "RJ": 19,
    "RN": 20, "RS": 21, "RO": 22, "RR": 23, "SC": 24, "SP": 25, "SE": 26, "TO": 27
}

# TIPO_ENTRADA_VIGIMED
tipo_entrada_vigimed_map = {
    "SERVICOS DE SAUDE": 1, "EMPRESAS FARMACEUTICAS": 2, "PACIENTES E PROFISSIONAIS DE SAUDE": 3,
    "SERVICOS DE VACINACAO": 4, "EREPORTING - INDUSTRIA, ENTRADA MANUAL DE DADOS": 5,
    "EREPORTING - INDUSTRIA, CARGA E2B": 6, "VIGIMOBILE": 7, "VIGIFLOW EFORMS": 8
}

# RECEBIDO_DE
recebido_de_map = {
    "CARGA E2B": 1, "ENTRADA MANUAL DE DADOS": 2, "AUTORIDADE REGULADORA": 3,
    "CENTRO REGIONAL DE FARMACOVIGILANCIA": 4, "EMPRESA FARMACEUTICA": 5,
    "OUTRO (P.EX. DISTRIBUIDORA, FINANCIADOR DE ESTUDO, ORGANIZACAO REPRESENTATIVA PARA PESQUISA CLINICA, OU ORGANIZACAO NAO-COMERCIAL)": 6,
    "PACIENTE/CONSUMIDOR": 7, "PROFISSIONAL DE SAUDE": 8
}

# TIPO_NOTIFICACAO
tipo_notificacao_map = {
    "NOTIFICACAO ESPONTANEA": 1, "NOTIFICACAO DE ESTUDO": 2, "OUTRO": 3
}

# NOTIFICACAO_PARENT_CHILD
notificacao_parent_child_map = {
    "SIM": 1, "NAO": 2
}

# GRUPO_IDADE
grupo_idade_map = {
    "FETO": 1, "NEONATO": 2, "INFANTIL": 3, "CRIANCA": 4, "ADOLESCENTE": 5,
    "ADULTO": 6, "IDOSO": 7, "OUTRO": 8
}

# SEXO
sexo_map = {
    "FEMININO": 1, "MASCULINO": 2
}

# GESTANTE
gestante_map = {
    "SIM": 1, "NAO": 2
}

# LACTANTE
lactante_map = {
    "SIM": 1, "NAO": 2
}

# GRAVE
grave_map = {
    "SIM": 1, "NAO": 2
}

# GRAVIDADE
gravidade_map = {
    "OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO": 1, "HOSPITALIZACAO": 2, "AMEACA R VIDA": 3,
    "RESULTOU EM OBITO": 4, "INCAPACIDADE PERSISTENTE OU SIGNIFICATIVA": 5,
    "ANOMALIA CONGENITA OU MALFORMACAO AO NASCER": 6
}

# DESFECHO
desfecho_map = {
    "RECUPERADO": 1, "EM RECUPERACAO": 2, "NAO RECUPERADO": 3, "FATAL": 4
}

# RELACAO_MEDICAMENTO_EVENTO
relacao_medicamento_evento_map = {
    "SUSPEITO": 1, "CONCOMITANTE": 2, "INTERACAO": 3, "MEDICAMENTO NAO ADMINISTRADO": 4
}

# ACAO_ADOTADA
acao_adotada_map = {
    "AUMENTO DA DOSE": 1, "NAO APLICAVEL": 2, "REDUCAO DA DOSE": 3, 
    "RETIRADA DO MEDICAMENTO": 4, "SEM ALTERACAO DA DOSE": 5
}

# NOTIFICADOR
notificador_map = {
    "ADVOGADO": 1, "CONSUMIDOR OU OUTRO NAO PROFISSIONAL DE SAUDE": 2,
    "FARMACEUTICO": 3, "MEDICO": 4, "OUTRO PROFISSIONAL DE SAUDE": 5
}


mappings_config = [
    {
        "kind": "dict",
        "col": "UF",
        "map": uf_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "TIPO_ENTRADA_VIGIMED",
        "map": tipo_entrada_vigimed_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "RECEBIDO_DE",
        "map": recebido_de_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "TIPO_NOTIFICACAO",
        "map": tipo_notificacao_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "NOTIFICACAO_PARENT_CHILD",
        "map": notificacao_parent_child_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "GRUPO_IDADE",
        "map": grupo_idade_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "SEXO",
        "map": sexo_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "GESTANTE",
        "map": gestante_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "LACTANTE",
        "map": lactante_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "GRAVE",
        "map": grave_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "GRAVIDADE",
        "map": gravidade_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "DESFECHO",
        "map": desfecho_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "RELACAO_MEDICAMENTO_EVENTO",
        "map": relacao_medicamento_evento_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "ACAO_ADOTADA",
        "map": acao_adotada_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
    {
        "kind": "dict",
        "col": "NOTIFICADOR",
        "map": notificador_map,
        "fillna_valor": "DESCONHECIDO",
        "fillna_chave": 0,
        "tipo_int64": True,
        "drop_original": False,
    },
]

In [17]:
hist_silver = apply_mappings(hist_silver, mappings_config)

In [18]:
hist_silver.shape

(311134, 61)

In [19]:
hist_silver[['UF','UF_VALOR','UF_CHAVE']].value_counts(dropna=False)

UF   UF_VALOR      UF_CHAVE
SP   SP            25          117317
NaN  DESCONHECIDO  0            81507
MG   MG            13           20254
BA   BA            5            11452
RJ   RJ            19           10871
DF   DF            7            10717
SC   SC            24            9291
RS   RS            21            8592
CE   CE            6             7915
PR   PR            16            7564
GO   GO            9             5921
ES   ES            8             5518
RN   RN            20            3691
PI   PI            18            1697
MA   MA            10            1623
PA   PA            14            1439
PE   PE            17            1398
AM   AM            4             1366
PB   PB            15             870
MS   MS            12             581
MT   MT            11             398
SE   SE            26             396
AL   AL            2              316
 C    C            0              248
RO   RO            22             101
TO   TO            27              53
AP   AP            3               22
AC   AC            1               16
Name: count, dtype: int64

In [20]:
hist_silver[['TIPO_ENTRADA_VIGIMED', 'TIPO_ENTRADA_VIGIMED_VALOR', 'TIPO_ENTRADA_VIGIMED_CHAVE']].value_counts(dropna=False)

TIPO_ENTRADA_VIGIMED                             TIPO_ENTRADA_VIGIMED_VALOR                       TIPO_ENTRADA_VIGIMED_CHAVE
Serviços de Saúde                                SERVIÇOS DE SAÚDE                                1                             152367
Empresas Farmacęuticas                           EMPRESAS FARMACĘUTICAS                           2                              79444
Pacientes e Profissionais de Saúde               PACIENTES E PROFISSIONAIS DE SAÚDE               3                              37774
eReporting - Indústria, Entrada manual de dados  EREPORTING - INDÚSTRIA, ENTRADA MANUAL DE DADOS  5                              11710
eReporting - Indústria, Carga E2B                EREPORTING - INDÚSTRIA, CARGA E2B                6                               9996
Serviços de Vacinaçăo                            SERVIÇOS DE VACINAÇĂO                            4                               9321
VigiMobile                                       VIGIMOBILE                                       7                               8192
VigiFlow eForms                                  VIGIFLOW EFORMS                                  8                               2260
NaN                                              DESCONHECIDO                                     0                                 70
Name: count, dtype: int64

In [21]:
hist_silver[['RECEBIDO_DE', 'RECEBIDO_DE_VALOR', 'RECEBIDO_DE_CHAVE']].value_counts(dropna=False)

RECEBIDO_DE                                                                                                                         RECEBIDO_DE_VALOR                                                                                                                   RECEBIDO_DE_CHAVE
Profissional de Saúde                                                                                                               PROFISSIONAL DE SAÚDE                                                                                                               8                    104704
Empresa Farmacęutica                                                                                                                EMPRESA FARMACĘUTICA                                                                                                                5                    101702
NaN                                                                                                                                 DESCONHECIDO                                                                                                                        0                     55666
Centro Regional de Farmacovigilância                                                                                                CENTRO REGIONAL DE FARMACOVIGILÂNCIA                                                                                                4                     39749
Paciente/Consumidor                                                                                                                 PACIENTE/CONSUMIDOR                                                                                                                 7                      8844
Outro (p.ex. Distribuidora, Financiador de Estudo, Organizaçăo Representativa para Pesquisa Clínica, ou Organizaçăo năo-Comercial)  OUTRO (P.EX. DISTRIBUIDORA, FINANCIADOR DE ESTUDO, ORGANIZAÇĂO REPRESENTATIVA PARA PESQUISA CLÍNICA, OU ORGANIZAÇĂO NĂO-COMERCIAL)  6                       420
Autoridade Reguladora                                                                                                               AUTORIDADE REGULADORA                                                                                                               3                        49
Name: count, dtype: int64

In [22]:
hist_silver[['TIPO_NOTIFICACAO', 'TIPO_NOTIFICACAO_VALOR', 'TIPO_NOTIFICACAO_CHAVE']].value_counts(dropna=False)

TIPO_NOTIFICACAO                                TIPO_NOTIFICACAO_VALOR                          TIPO_NOTIFICACAO_CHAVE
Notificaçăo espontânea                          NOTIFICAÇĂO ESPONTÂNEA                          1                         268975
Notificaçăo de estudo                           NOTIFICAÇĂO DE ESTUDO                           2                          22119
Outro                                           OUTRO                                           3                          19855
Năo disponível pelo notificador (desconhecido)  NĂO DISPONÍVEL PELO NOTIFICADOR (DESCONHECIDO)  0                            185
Name: count, dtype: int64

In [23]:
hist_silver[['NOTIFICACAO_PARENT_CHILD', 'NOTIFICACAO_PARENT_CHILD_VALOR', 'NOTIFICACAO_PARENT_CHILD_CHAVE']].value_counts(dropna=False)

NOTIFICACAO_PARENT_CHILD  NOTIFICACAO_PARENT_CHILD_VALOR  NOTIFICACAO_PARENT_CHILD_CHAVE
NaN                       DESCONHECIDO                    0                                 310006
Sim                       SIM                             1                                   1128
Name: count, dtype: int64

In [24]:
hist_silver[['GRUPO_IDADE', 'GRUPO_IDADE_VALOR', 'GRUPO_IDADE_CHAVE']].value_counts(dropna=False)

GRUPO_IDADE  GRUPO_IDADE_VALOR  GRUPO_IDADE_CHAVE
NaN          DESCONHECIDO       0                    183974
Adulto       ADULTO             6                     71598
Idoso        IDOSO              7                     42827
Criança      CRIANÇA            4                      4389
Infantil     INFANTIL           3                      3734
Adolescente  ADOLESCENTE        5                      3139
Neonato      NEONATO            2                      1409
Feto         FETO               1                        64
Name: count, dtype: int64

In [25]:
hist_silver[['SEXO', 'SEXO_VALOR', 'SEXO_CHAVE']].value_counts(dropna=False)

SEXO          SEXO_VALOR    SEXO_CHAVE
Feminino      FEMININO      1             186527
Masculino     MASCULINO     2             111891
NaN           DESCONHECIDO  0              11687
Desconhecido  DESCONHECIDO  0               1029
Name: count, dtype: int64

In [26]:
hist_silver[['GESTANTE', 'GESTANTE_VALOR', 'GESTANTE_CHAVE']].value_counts(dropna=False)

GESTANTE  GESTANTE_VALOR  GESTANTE_CHAVE
NaN       DESCONHECIDO    0                 160811
Năo       NĂO             2                 148633
Sim       SIM             1                   1690
Name: count, dtype: int64

In [27]:
hist_silver[['LACTANTE', 'LACTANTE_VALOR', 'LACTANTE_CHAVE']].value_counts(dropna=False)

LACTANTE  LACTANTE_VALOR  LACTANTE_CHAVE
NaN       DESCONHECIDO    0                 160814
Năo       NĂO             2                 148497
Sim       SIM             1                   1823
Name: count, dtype: int64

In [28]:
hist_silver[['GRAVE', 'GRAVE_VALOR', 'GRAVE_CHAVE']].value_counts(dropna=False)

GRAVE  GRAVE_VALOR   GRAVE_CHAVE
Sim    SIM           1              136768
Năo    NĂO           2              105074
NaN    DESCONHECIDO  0               69292
Name: count, dtype: int64

In [29]:
hist_silver[['GRAVIDADE', 'GRAVIDADE_VALOR', 'GRAVIDADE_CHAVE']].value_counts(dropna=False)

GRAVIDADE                                    GRAVIDADE_VALOR                              GRAVIDADE_CHAVE
NaN                                          DESCONHECIDO                                 0                  168932
Outro efeito clinicamente significativo      OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO      1                   82979
Hospitalizaçăo                               HOSPITALIZAÇĂO                               2                   31898
Resultou em óbito                            RESULTOU EM ÓBITO                            4                   11049
Ameaça ŕ vida                                AMEAÇA Ŕ VIDA                                3                    9952
Incapacidade persistente ou significativa    INCAPACIDADE PERSISTENTE OU SIGNIFICATIVA    5                    6179
Anomalia congęnita ou malformaçăo ao nascer  ANOMALIA CONGĘNITA OU MALFORMAÇĂO AO NASCER  6                     145
Name: count, dtype: int64

In [30]:
hist_silver[['DESFECHO', 'DESFECHO_VALOR', 'DESFECHO_CHAVE']].value_counts(dropna=False)

DESFECHO        DESFECHO_VALOR  DESFECHO_CHAVE
Recuperado      RECUPERADO      1                 146660
Desconhecido    DESCONHECIDO    0                  53293
NaN             DESCONHECIDO    0                  49933
Em recuperaçăo  EM RECUPERAÇĂO  2                  28389
Năo Recuperado  NĂO RECUPERADO  3                  21947
Fatal           FATAL           4                  10912
Name: count, dtype: int64

In [31]:
hist_silver[['RELACAO_MEDICAMENTO_EVENTO', 'RELACAO_MEDICAMENTO_EVENTO_VALOR', 'RELACAO_MEDICAMENTO_EVENTO_CHAVE']].value_counts(dropna=False)

RELACAO_MEDICAMENTO_EVENTO    RELACAO_MEDICAMENTO_EVENTO_VALOR  RELACAO_MEDICAMENTO_EVENTO_CHAVE
Suspeito                      SUSPEITO                          1                                   300007
Medicamento năo administrado  MEDICAMENTO NĂO ADMINISTRADO      4                                     8418
Concomitante                  CONCOMITANTE                      2                                     1944
Interaçăo                     INTERAÇĂO                         3                                      764
NaN                           DESCONHECIDO                      0                                        1
Name: count, dtype: int64

In [32]:
hist_silver[['ACAO_ADOTADA', 'ACAO_ADOTADA_VALOR', 'ACAO_ADOTADA_CHAVE']].value_counts(dropna=False)

ACAO_ADOTADA             ACAO_ADOTADA_VALOR       ACAO_ADOTADA_CHAVE
NaN                      DESCONHECIDO             0                     126091
Retirada do medicamento  RETIRADA DO MEDICAMENTO  4                      71728
Năo aplicável            NĂO APLICÁVEL            2                      37552
Desconhecido             DESCONHECIDO             0                      35680
Sem alteraçăo da dose    SEM ALTERAÇĂO DA DOSE    5                      31763
Reduçăo da dose          REDUÇĂO DA DOSE          3                       5609
Aumento da dose          AUMENTO DA DOSE          1                       2711
Name: count, dtype: int64

In [33]:
hist_silver[['NOTIFICADOR', 'NOTIFICADOR_VALOR', 'NOTIFICADOR_CHAVE']].value_counts(dropna=False)

NOTIFICADOR                                    NOTIFICADOR_VALOR                              NOTIFICADOR_CHAVE
Farmacęutico                                   FARMACĘUTICO                                   3                    121082
Consumidor ou outro năo profissional de saúde  CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE  2                     85054
Outro profissional de saúde                    OUTRO PROFISSIONAL DE SAÚDE                    5                     65862
Médico                                         MÉDICO                                         4                     20474
NaN                                            DESCONHECIDO                                   0                     18164
Advogado                                       ADVOGADO                                       1                       498
Name: count, dtype: int64

## ✅ IDADE_MOMENTO_REACAO

In [34]:
from utils.not_normalize_idade_momento_reacao import normalize_idade_momento_reacao

In [35]:
hist_silver = normalize_idade_momento_reacao(hist_silver, coluna="IDADE_MOMENTO_REACAO")

In [36]:
hist_silver[['IDADE_MOMENTO_REACAO','IDADE_MOMENTO_REACAO_TIPO_CHAVE','IDADE_MOMENTO_REACAO_TIPO_VALOR','IDADE_MOMENTO_REACAO_VALOR']].value_counts(dropna=False).head(10)

IDADE_MOMENTO_REACAO  IDADE_MOMENTO_REACAO_TIPO_CHAVE  IDADE_MOMENTO_REACAO_TIPO_VALOR  IDADE_MOMENTO_REACAO_VALOR
NaN                   0                                DESCONHECIDO                     NaN                           110538
60 ano                1                                ANO                              60.0                            3481
40 ano                1                                ANO                              40.0                            3312
42 ano                1                                ANO                              42.0                            3281
65 ano                1                                ANO                              65.0                            3279
61 ano                1                                ANO                              61.0                            3276
59 ano                1                                ANO                              59.0                            3275
63 ano                1                                ANO                              63.0                            3264
64 ano                1                                ANO                              64.0                            3232
58 ano                1                                ANO                              58.0                            3221
Name: count, dtype: int64

In [37]:
hist_silver.shape

(311134, 64)

## ✅ DURACAO

In [38]:
from utils.not_normalize_duracao import normalize_duracao

In [39]:
hist_silver = normalize_duracao(hist_silver, coluna="DURACAO")

In [40]:
hist_silver[['DURACAO','DURACAO_TIPO_CHAVE','DURACAO_TIPO_VALOR','DURACAO_VALOR']].value_counts(dropna=False).head(10)

DURACAO    DURACAO_TIPO_CHAVE  DURACAO_TIPO_VALOR  DURACAO_VALOR
NaN        0                   DESCONHECIDO        NaN              204258
           0                   DESCONHECIDO        NaN               31565
1 dia      4                   DIA                 1.0               16744
2 dia      4                   DIA                 2.0                5763
1 hora     3                   HORA                1.0                4157
30 minuto  2                   MINUTO              30.0               3884
3 dia      4                   DIA                 3.0                3616
4 dia      4                   DIA                 4.0                2357
5 dia      4                   DIA                 5.0                2002
2 hora     3                   HORA                2.0                1870
Name: count, dtype: int64

In [41]:
hist_silver.shape

(311134, 67)

## ✅ IDADE_GESTACIONAL_MOMENTO_REACAO

In [42]:
from utils.not_normalize_idade_gestacional_momento_reacao import normalize_idade_gestacional_momento_reacao

In [43]:
hist_silver = normalize_idade_gestacional_momento_reacao(hist_silver, coluna="IDADE_GESTACIONAL_MOMENTO_REACAO")

In [44]:
hist_silver[['IDADE_GESTACIONAL_MOMENTO_REACAO','IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE','IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR','IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR']].value_counts(dropna=False).head(10)

IDADE_GESTACIONAL_MOMENTO_REACAO  IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE  IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR  IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR
NaN                               0                                            DESCONHECIDO                                 NaN                                       310802
1 Trimestre                       3                                            TRIMESTRE                                    1.0                                           20
34 Semanas                        1                                            SEMANA                                       34.0                                          19
35 Semanas                        1                                            SEMANA                                       35.0                                          16
9 Semanas                         1                                            SEMANA                                       9.0                                           14
32 Semanas                        1                                            SEMANA                                       32.0                                          13
36 Semanas                        1                                            SEMANA                                       36.0                                          12
5 Semanas                         1                                            SEMANA                                       5.0                                           12
6 Semanas                         1                                            SEMANA                                       6.0                                           12
8 Semanas                         1                                            SEMANA                                       8.0                                           12
Name: count, dtype: int64

In [45]:
hist_silver.shape

(311134, 70)

In [46]:
hist_silver.head(20) # verificar caracteres especiais

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,ACAO_ADOTADA,NOTIFICADOR,ATUALIZADO,HASH_BRONZE,UF_VALOR,UF_CHAVE,TIPO_ENTRADA_VIGIMED_VALOR,TIPO_ENTRADA_VIGIMED_CHAVE,RECEBIDO_DE_VALOR,RECEBIDO_DE_CHAVE,TIPO_NOTIFICACAO_VALOR,TIPO_NOTIFICACAO_CHAVE,NOTIFICACAO_PARENT_CHILD_VALOR,NOTIFICACAO_PARENT_CHILD_CHAVE,GRUPO_IDADE_VALOR,GRUPO_IDADE_CHAVE,SEXO_VALOR,SEXO_CHAVE,GESTANTE_VALOR,GESTANTE_CHAVE,LACTANTE_VALOR,LACTANTE_CHAVE,GRAVE_VALOR,GRAVE_CHAVE,GRAVIDADE_VALOR,GRAVIDADE_CHAVE,DESFECHO_VALOR,DESFECHO_CHAVE,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,NOTIFICADOR_VALOR,NOTIFICADOR_CHAVE,IDADE_MOMENTO_REACAO_TIPO_CHAVE,IDADE_MOMENTO_REACAO_TIPO_VALOR,IDADE_MOMENTO_REACAO_VALOR,DURACAO_TIPO_VALOR,DURACAO_TIPO_CHAVE,DURACAO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR
0,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,Notificaçăo espontânea,None,1990-01-31,30 ano,None,None,Feminino,Năo,Năo,68.0,165,Hemiparesia,Sim,Outro efeito clinicamente significativo,Recuperado,2021-01-25,2021-02-06,12 dia,Concomitante,Tamisa,Năo aplicável,Médico,2026-01-15,c540f6f2873cded948f9a6156d6a92cf9f59b7e110f84ebc4a988ccdb13b1c3d,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,SIM,1,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,RECUPERADO,1,CONCOMITANTE,2,NĂO APLICÁVEL,2,MÉDICO,4,1,ANO,30.0,DIA,4,12.0,0,DESCONHECIDO,NaN
1,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300208322,2023-09-01,2023-09-01,NaT,Notificaçăo espontânea,None,NaT,None,None,None,Feminino,Năo,Năo,None,None,Cefaleia,Năo,Outro efeito clinicamente significativo,Desconhecido,2021-01-22,NaT,None,Suspeito,CoronaVac,Năo aplicável,Consumidor ou outro năo profissional de saúde,2026-01-15,1f6805d588f843fe6f27dc43ae2026701e8d0400f3a10108c262015650b0b5b5,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,DESCONHECIDO,0,SUSPEITO,1,NĂO APLICÁVEL,2,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,0,DESCONHECIDO,NaN,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
2,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300214015,2023-10-06,2023-10-06,NaT,Notificaçăo espontânea,None,1971-05-22,49 ano,None,None,Masculino,Năo,Năo,None,None,Nefrolitíase,Sim,Hospitalizaçăo,Desconhecido,2021-02-03,NaT,None,Concomitante,Metformina,None,Médico,2026-01-15,0bf848a27d155b0a8bdebe8473dfb8c83b42d7d1e9123a666eceea3d811df4f9,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,HOSPITALIZAÇĂO,2,DESCONHECIDO,0,CONCOMITANTE,2,DESCONHECIDO,0,MÉDICO,4,1,ANO,49.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
3,SP,"eReporting - Indústria, Carga E2B",Empresa Farmacęutica,BR-ANVISA-300345102,2025-07-21,2025-07-21,NaT,Notificaçăo espontânea,None,1974-11-23,46 ano,None,None,Masculino,Năo,Năo,None,None,Choque anafilático,Sim,Ameaça ŕ vida,Desconhecido,2021-03-02,NaT,None,Suspeito,Soro antibotropico (pentavalente),Desconhecido,Farmacęutico,2026-01-15,14d6e7f81906f9def902e0ce10e10c8c1c8139bda38a39a700309ff9bd00dc03,SP,25,"EREPORTING - INDÚSTRIA, CARGA E2B",6,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,AMEAÇA Ŕ VIDA,3,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,FARMACĘUTICO,3,1,ANO,46.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
4,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300212385,2023-09-27,2023-09-27,NaT,Notificaçăo espontânea,None,NaT,None,None,None,Masculino,Năo,Năo,None,None,Abscesso nasal,Sim,Outro efeito clinicamente significativo,Desconhecido,NaT,NaT,None,Suspeito,Vacina adsorvida COVID-19 (inativada),None,Consumidor ou outro năo profissional de saúde,2026-01-15,76a79c5954923381ce6ba55291fc63cc158e622993be2be45c03a795e8f5adbe,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,0,DESCONHECIDO,NaN,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
5,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300212764,2023-09-29,2023-09-29,NaT,Notificaçăo espontânea,None,1982-05-05,39 ano,None,None,Masculino,Năo,Năo,None,None,Descompensaçăo metabólica diabética,Sim,Outro efeito clinicamente significativo,Desconhecido,NaT,NaT,None,Suspeito,CoronaVac,Desconhecido,Consumidor ou outro năo profissional de saúde,2026-01-15,f541eb176637cc7be6489423fcdd68088575458a67a5b6d643b876b85981bfb9,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,1,ANO,39.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
6,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300270421,2024-05-20,2024-05-20,NaT,Notificaçăo espontânea,None,1978-10-05,42 ano,None,None,Feminino,Năo,Năo,78.0,171,Hiperemia,Năo,None,Recuperado,2021-05-13,NaT,None,Suspeito,Vacina influenza trivalente,Desconhecido,Outro profissional de saúde,2026-01-15,4a980a0a952d8cc9e35c46c6b5d59092e811099492cbe8792e4a3d135f0599b7,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,OUTRO PROFISSIONAL DE SAÚDE,5,1,ANO,42.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
7,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300257351,2024-03-07,2024-03-07,NaT,Notificaçăo espontânea,None,1962-06-08,61 ano,None,None,Feminino,Năo,Năo,66.0,163,Neurite óptica,Sim,Hospitalizaçăo,Recuperado,NaT,NaT,None,Suspeito,Vacina influenza trivalente (fragmentada e inativada),Retirada do medicamento,Consumidor ou outro năo profissional de saúde,2026-01-15,d4e1cc9845edeb7cd160dc10c8c29b35aa9d023ef46138f21f921e1ff0f21c02,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,SIM,1,HOSPITALIZAÇĂO,2,RECUPERADO,1,SUSPEITO,1,RETIRADA DO MEDICAMENTO,4,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,1,ANO,61.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
8,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300272878,2024-06-04,2024-06-04,NaT,Notificaçăo espontânea,None,NaT,81 ano,None,None,Feminino,Năo,Năo,75.0,165,Hiperemia,Năo,None,Recuperado,2021-05-13,NaT,None,Suspeito,Vacina influenza trivalente (fragmentada e inativada),Desconhecido,Outro profissional de saúde,2026-01-15,fec36efbe070579a0a0aaf64e968aab18d2495ae80e05f9b75de38d9e2ebffdf,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,OUTRO PROFISSIONAL DE SAÚDE,5,1,ANO,81.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
9,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300270512,2024-05-20,2024-05-20,NaT,Notificaçăo espontânea,None,1960-09-04,60 ano,None,None,Feminino,Năo,Năo,None,None,Calor cutâneo,Năo,None,Desconhecido,2021-04-13,2021-04-13,1 dia,Concomitante,Somalgin,Desconhecido,Médico,2026-01-15,ebe1ce173e4ee43fa7d5448f3145fd07471fb671d2b65a21a17593aa6f956269,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,DESCONHECIDO,0,CONCOMITANTE,2,DESCONHECIDO,0,MÉDICO,4,1,ANO,60.0,DIA,4,1.0,0,DESCONHECIDO,NaN
10,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300272885,2024-06-04,2024-06-04,NaT,Notificaçăo espontânea,None,1960-01-11,61 ano,None,None,Feminino,Năo,Năo,None,None,Calor cutâneo,Năo,None,Desconhecido,2021-04-12,2021-04-12,1 dia,Suspeito,Vacina influenza trivalente,Desconhecido,Médico,2026-01-15,23fbd8894646a69c098c53ee541882c265f24d1dee4047fedcea4fffaddc46c3,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,MÉDICO,4,1,ANO,61.0,DIA,4,1.0,0,DESCONHECIDO,NaN
11,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300260262,2024-03-25,2024-03-25,NaT,Notificaçăo espontânea,None,1972-03-28,49 ano,None,None,Feminino,Năo,Năo,None,None,Calor cutâneo,Năo,None,Desconhecido,2021-04-12,2021-04-12,1 dia,Suspeito,Vacina influenza trivalente (fragmentada e inativada),Desconhecido,Médico,2026-01-15,fb147990e383a695400ca5345285bf41332b56e3b18e9ef8e90fb85cee490eb3,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,MÉDICO,4,1,ANO,49.0,DIA,4,1.0,0,DESCONHECIDO,NaN
12,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300270485,2024-05-20,2024-05-20,NaT,Notificaçăo espontânea,None,1973-02-28,48 ano,None,None,Feminino,Năo,Năo,None,None,Prurido no local de administraçăo,Năo,None,Recuperado,2021-04-14,2021-04-15,1 dia,Suspeito,Vacina influenza trivalente (fragmentada e inativada),Desconhecido,Médico,2026-01-15,9a92ce60e64da8ebdc8c354ec11471a9d19b965ababcfa43ad048e6101043f6a,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,MÉDICO,4,1,ANO,48.0,DIA,4,1.0,0,DESCONHECIDO,NaN
13,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300272891,2024-06-04,2024-06-04,NaT,Notificaçăo espontânea,None,2020-03-27,1 ano,None,None,Feminino,Năo,Năo,None,None,Rinite,Năo,None,Recuperado,2021-04-15,2021-04-17,2 dia,Suspeito,Vacina influenza trivalente (fragmentada e inativada),Desconhecido,Médico,2026-01-15,d355677a7b2dcda12d5ce5bd40badce336ef8adf3d27b901b82319dac83508fe,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,MÉDICO,4,1,ANO,1.0,DIA,4,2.0,0,DESCONHECIDO,NaN
14,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300273077,2024-06-05,2024-06-05,NaT,Notificaçăo espontânea,None,NaT,71 ano,None,None,Masculino,Năo,Năo,80.0,168,COVID-19,Sim,Resultou em óbito,Fatal,2021-05-26,2021-06-03,8 dia,Suspeito,Influenza,Desconhecido,Consumidor ou outro năo profissional de saúde,2026-01-15,3f97ba17a72cfff9beea03ae49c6df6b388f75862383c4107352b87b19174efe,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,RESULTOU EM ÓBITO,4,FATAL,4,SUSPEITO,1,DESCONHECIDO,0,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,1,ANO,71.0,DIA,4,8.0,0,DESCONHECIDO,NaN
15,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300253018,2024-02-09,2024-02-09,NaT,Notificaçăo espontânea,None,1972-11-27,48 ano,None,None,Feminino,Năo,Năo,None,None,Artropatia,Năo,Outro efeito clinicamente significativo,Recuperado,NaT,NaT,,Suspeito,Vacina adsorvida COVID-19 (inativada),Desconhecido,Outro profissional de saúde,2026-01-15,79e3b0db80076609f6fac03952ca1f84b40d2a3ab701a266053ae87f99627f3c,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,OUTRO PROFISSIONAL DE SAÚDE,5,1,ANO,48.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
16,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300224656,2023-12-12,2023-12-12,NaT,Notificaçăo espontânea,None,NaT,36 ano,None,None,Feminino,Năo,Năo,None,None,Mialgia,Năo,Outro efeito clinicamente significativo,Năo Recuperado,NaT,NaT,None,Suspeito,Vacina adsorvida COVID-19 (inativada),Năo aplicável,Outro profissional de saúde,2026-01-15,a893239d73c56ee7e6e80bcc2fbc74b2931c081091aa2b6f20982d3d361994d6,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,NĂO RECUPERADO,3,SUSPEITO,1,NĂO APLICÁVEL,2,OUTRO PROFISSIONAL DE SAÚDE,5,1,ANO,36.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
17,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300271424,2024-05-24,2024-05-24,NaT,Notificaçăo espontânea,None,1979-05-19,41 ano,None,None,Feminino,Năo,Năo,None,None,Remoçăo de prótese mamária,Sim,Hospitalizaçăo,Desconhecido,2021-05-04,NaT,,Suspeito,Soro antirrabico,None,Médico,2026-01-15,9294743de4366933e26f28f25d897e1e35cd1013e9977552c0e281060d655f9a,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,SIM,1,HOSPITALIZAÇĂO,2,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,MÉDICO,4,1,ANO,41.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
18,SP,"eReporting - Indústria, Carga E2B",Empresa Farmacęutica,BR-ANVISA-300326664,2025-04-04,2025-04-04,NaT,Notificaçăo espontânea,None,1970-10-26,54 ano,None,None,Masculino,Năo,Năo,93.0,178,Capacidade de resposta imune diminuída,Năo,Outro efeito clinicamente significativo,Desconhecido,2021-07-21,NaT,None,Suspeito,Vacina adsorvida COVID-19 (inativada),None,Consumidor ou outro năo profissional de saúde,2026-01-15,9a62abfc8234d50d79e81954235f422c1ffe4ce26a230d7c660c54556a9ba47c,SP,25,"EREPORTING - INDÚSTRIA, CARGA E2B",6,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,NĂO,2,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,1,DESCONHECIDO,0,SUSPEITO,1,DESCONHECIDO,0,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,2,1,ANO,54.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN
19,SP,Empresas Farmacęuticas,Empresa Farmacęutica,BR-ANVISA-300270599,2024-05-21,2024-05-21,NaT,Notificaçăo espontânea,None,2011-11-26,10 ano,None,None,Masculino,Năo,Năo,None,None,Queda,Sim,Resultou em óbito,Fatal,2022-01-30,2022-01-30,1 dia,Concomitante,CoronaVac,Năo aplicável,Outro profissional de saúde,2026-01-15,5ce9b65bdc7c75e6fc923b6e12b1a5a0f411b684c5b306396744bb2aaf482862,SP,25,EMPRESAS FARMACĘUTICAS,2,EMPRESA FARMACĘUTICA,5,NOTIFICAÇĂO ESPONTÂNEA,1,DESCONHECIDO,0,DESCONHECIDO,0,MASCULINO,2,NĂO,2,NĂO,2,SIM,1,RESULTOU EM ÓBITO,4,FATAL,4,CONCOMITANTE,2,NĂO APLICÁVEL,2,OUTRO PROFISSIONAL DE SAÚDE,5,1,ANO,10.0,DIA,4,1.0,0,DESCONHECIDO,NaN

In [47]:
### ✅ CODIGO_ATC

In [48]:
from utils import desagrupar_colunas_pipe

In [49]:
colunas_para_desagrupar = ['ATC_CODE_LEVEL_4']
print(f"Shape antes da desagregação: {hist_silver.shape}") 
hist_silver_dedup = desagrupar_colunas_pipe(hist_silver.rename(columns={'CODIGO_ATC': 'ATC_CODE_LEVEL_4'}), colunas_para_desagrupar)
print(f"Shape depois da desagregação: {hist_silver_dedup.shape}")

Shape antes da desagregação: (311134, 70)
Shape depois da desagregação: (311134, 70)

In [50]:
hist_silver_dedup["HASH_SILVER"] = build_row_hash(
    hist_silver_dedup, 
    hist_silver_dedup.columns.difference(['ATUALIZADO', 'HASH_BRONZE']).tolist(), 
    algo="sha256", 
    sep="|"
)

In [51]:
hist_silver_dedup.columns

Index(['UF', 'TIPO_ENTRADA_VIGIMED', 'RECEBIDO_DE',
       'IDENTIFICACAO_NOTIFICACAO', 'DATA_INCLUSAO_SISTEMA',
       'DATA_ULTIMA_ATUALIZACAO', 'DATA_NOTIFICACAO', 'TIPO_NOTIFICACAO',
       'NOTIFICACAO_PARENT_CHILD', 'DATA_NASCIMENTO', 'IDADE_MOMENTO_REACAO',
       'GRUPO_IDADE', 'IDADE_GESTACIONAL_MOMENTO_REACAO', 'SEXO', 'GESTANTE',
       'LACTANTE', 'PESO_KG', 'ALTURA_CM', 'REACAO_EVENTO_ADVERSO_MEDDRA',
       'GRAVE', 'GRAVIDADE', 'DESFECHO', 'DATA_INICIO_HORA', 'DATA_FINAL_HORA',
       'DURACAO', 'RELACAO_MEDICAMENTO_EVENTO', 'NOME_MEDICAMENTO_WHODRUG',
       'ACAO_ADOTADA', 'NOTIFICADOR', 'ATUALIZADO', 'HASH_BRONZE', 'UF_VALOR',
       'UF_CHAVE', 'TIPO_ENTRADA_VIGIMED_VALOR', 'TIPO_ENTRADA_VIGIMED_CHAVE',
       'RECEBIDO_DE_VALOR', 'RECEBIDO_DE_CHAVE', 'TIPO_NOTIFICACAO_VALOR',
       'TIPO_NOTIFICACAO_CHAVE', 'NOTIFICACAO_PARENT_CHILD_VALOR',
       'NOTIFICACAO_PARENT_CHILD_CHAVE', 'GRUPO_IDADE_VALOR',
       'GRUPO_IDADE_CHAVE', 'SEXO_VALOR', 'SEXO_CHAVE', 'GESTANTE_VALOR',
       'GESTANTE_CHAVE', 'LACTANTE_VALOR', 'LACTANTE_CHAVE', 'GRAVE_VALOR',
       'GRAVE_CHAVE', 'GRAVIDADE_VALOR', 'GRAVIDADE_CHAVE', 'DESFECHO_VALOR',
       'DESFECHO_CHAVE', 'RELACAO_MEDICAMENTO_EVENTO_VALOR',
       'RELACAO_MEDICAMENTO_EVENTO_CHAVE', 'ACAO_ADOTADA_VALOR',
       'ACAO_ADOTADA_CHAVE', 'NOTIFICADOR_VALOR', 'NOTIFICADOR_CHAVE',
       'IDADE_MOMENTO_REACAO_TIPO_CHAVE', 'IDADE_MOMENTO_REACAO_TIPO_VALOR',
       'IDADE_MOMENTO_REACAO_VALOR', 'DURACAO_TIPO_VALOR',
       'DURACAO_TIPO_CHAVE', 'DURACAO_VALOR',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR', 'HASH_SILVER'],
      dtype='object')

In [52]:
hist_silver_dedup.to_parquet(Path(project_root) / "data/02_silver/hist_dim_notificacoes/hist_dim_notificacoes.parquet", index=False)

In [53]:
hist_silver_dedup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311134 entries, 0 to 311133
Data columns (total 71 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   UF                                           229627 non-null  object
 1   TIPO_ENTRADA_VIGIMED                         311064 non-null  object
 2   RECEBIDO_DE                                  255468 non-null  object
 3   IDENTIFICACAO_NOTIFICACAO                    311134 non-null  object
 4   DATA_INCLUSAO_SISTEMA                        311134 non-null  datetime64[ns]
 5   DATA_ULTIMA_ATUALIZACAO                      311064 non-null  datetime64[ns]
 6   DATA_NOTIFICACAO                             158960 non-null  datetime64[ns]
 7   TIPO_NOTIFICACAO                             311134 non-null  object
 8   NOTIFICACAO_PARENT_CHILD                     1128 non-null    object
 9   DATA_NASCIMENTO                              229298 non-null  datetime64[ns]
 10  IDADE_MOMENTO_REACAO                         200596 non-null  object
 11  GRUPO_IDADE                                  127160 non-null  object
 12  IDADE_GESTACIONAL_MOMENTO_REACAO             332 non-null     object
 13  SEXO                                         299447 non-null  object
 14  GESTANTE                                     150323 non-null  object
 15  LACTANTE                                     150320 non-null  object
 16  PESO_KG                                      121868 non-null  object
 17  ALTURA_CM                                    66706 non-null   object
 18  REACAO_EVENTO_ADVERSO_MEDDRA                 310817 non-null  object
 19  GRAVE                                        241842 non-null  object
 20  GRAVIDADE                                    142202 non-null  object
 21  DESFECHO                                     261201 non-null  object
 22  DATA_INICIO_HORA                             169043 non-null  datetime64[ns]
 23  DATA_FINAL_HORA                              107847 non-null  datetime64[ns]
 24  DURACAO                                      106876 non-null  object
 25  RELACAO_MEDICAMENTO_EVENTO                   311133 non-null  object
 26  NOME_MEDICAMENTO_WHODRUG                     310614 non-null  object
 27  ACAO_ADOTADA                                 185043 non-null  object
 28  NOTIFICADOR                                  292970 non-null  object
 29  ATUALIZADO                                   311134 non-null  object
 30  HASH_BRONZE                                  311134 non-null  object
 31  UF_VALOR                                     311134 non-null  object
 32  UF_CHAVE                                     311134 non-null  Int64
 33  TIPO_ENTRADA_VIGIMED_VALOR                   311134 non-null  object
 34  TIPO_ENTRADA_VIGIMED_CHAVE                   311134 non-null  Int64
 35  RECEBIDO_DE_VALOR                            311134 non-null  object
 36  RECEBIDO_DE_CHAVE                            311134 non-null  Int64
 37  TIPO_NOTIFICACAO_VALOR                       311134 non-null  object
 38  TIPO_NOTIFICACAO_CHAVE                       311134 non-null  Int64
 39  NOTIFICACAO_PARENT_CHILD_VALOR               311134 non-null  object
 40  NOTIFICACAO_PARENT_CHILD_CHAVE               311134 non-null  Int64
 41  GRUPO_IDADE_VALOR                            311134 non-null  object
 42  GRUPO_IDADE_CHAVE                            311134 non-null  Int64
 43  SEXO_VALOR                                   311134 non-null  object
 44  SEXO_CHAVE                                   311134 non-null  Int64
 45  GESTANTE_VALOR                               311134 non-null  object
 46  GESTANTE_CHAVE                               311134 non-null  Int64
 47  LACTANTE_VALOR                               311134 non-null  object
 48  LACTANTE_CHAVE                               311134 non-null  Int64
 49  GRAVE_VALOR                                  311134 non-null  object
 50  GRAVE_CHAVE                                  311134 non-null  Int64
 51  GRAVIDADE_VALOR                              311134 non-null  object
 52  GRAVIDADE_CHAVE                              311134 non-null  Int64
 53  DESFECHO_VALOR                               311134 non-null  object
 54  DESFECHO_CHAVE                               311134 non-null  Int64
 55  RELACAO_MEDICAMENTO_EVENTO_VALOR             311134 non-null  object
 56  RELACAO_MEDICAMENTO_EVENTO_CHAVE             311134 non-null  Int64
 57  ACAO_ADOTADA_VALOR                           311134 non-null  object
 58  ACAO_ADOTADA_CHAVE                           311134 non-null  Int64
 59  NOTIFICADOR_VALOR                            311134 non-null  object
 60  NOTIFICADOR_CHAVE                            311134 non-null  Int64
 61  IDADE_MOMENTO_REACAO_TIPO_CHAVE              311134 non-null  int64
 62  IDADE_MOMENTO_REACAO_TIPO_VALOR              311134 non-null  object
 63  IDADE_MOMENTO_REACAO_VALOR                   199417 non-null  float64
 64  DURACAO_TIPO_VALOR                           311134 non-null  object
 65  DURACAO_TIPO_CHAVE                           311134 non-null  int64
 66  DURACAO_VALOR                                75191 non-null   float64
 67  IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE  311134 non-null  int64
 68  IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR  311134 non-null  object
 69  IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR       328 non-null     float64
 70  HASH_SILVER                                  311134 non-null  object
dtypes: Int64(15), datetime64[ns](6), float64(3), int64(3), object(44)
memory usage: 173.0+ MB

# 🥇 Gold

In [54]:
hist_silver_dedup.columns

Index(['UF', 'TIPO_ENTRADA_VIGIMED', 'RECEBIDO_DE',
       'IDENTIFICACAO_NOTIFICACAO', 'DATA_INCLUSAO_SISTEMA',
       'DATA_ULTIMA_ATUALIZACAO', 'DATA_NOTIFICACAO', 'TIPO_NOTIFICACAO',
       'NOTIFICACAO_PARENT_CHILD', 'DATA_NASCIMENTO', 'IDADE_MOMENTO_REACAO',
       'GRUPO_IDADE', 'IDADE_GESTACIONAL_MOMENTO_REACAO', 'SEXO', 'GESTANTE',
       'LACTANTE', 'PESO_KG', 'ALTURA_CM', 'REACAO_EVENTO_ADVERSO_MEDDRA',
       'GRAVE', 'GRAVIDADE', 'DESFECHO', 'DATA_INICIO_HORA', 'DATA_FINAL_HORA',
       'DURACAO', 'RELACAO_MEDICAMENTO_EVENTO', 'NOME_MEDICAMENTO_WHODRUG',
       'ACAO_ADOTADA', 'NOTIFICADOR', 'ATUALIZADO', 'HASH_BRONZE', 'UF_VALOR',
       'UF_CHAVE', 'TIPO_ENTRADA_VIGIMED_VALOR', 'TIPO_ENTRADA_VIGIMED_CHAVE',
       'RECEBIDO_DE_VALOR', 'RECEBIDO_DE_CHAVE', 'TIPO_NOTIFICACAO_VALOR',
       'TIPO_NOTIFICACAO_CHAVE', 'NOTIFICACAO_PARENT_CHILD_VALOR',
       'NOTIFICACAO_PARENT_CHILD_CHAVE', 'GRUPO_IDADE_VALOR',
       'GRUPO_IDADE_CHAVE', 'SEXO_VALOR', 'SEXO_CHAVE', 'GESTANTE_VALOR',
       'GESTANTE_CHAVE', 'LACTANTE_VALOR', 'LACTANTE_CHAVE', 'GRAVE_VALOR',
       'GRAVE_CHAVE', 'GRAVIDADE_VALOR', 'GRAVIDADE_CHAVE', 'DESFECHO_VALOR',
       'DESFECHO_CHAVE', 'RELACAO_MEDICAMENTO_EVENTO_VALOR',
       'RELACAO_MEDICAMENTO_EVENTO_CHAVE', 'ACAO_ADOTADA_VALOR',
       'ACAO_ADOTADA_CHAVE', 'NOTIFICADOR_VALOR', 'NOTIFICADOR_CHAVE',
       'IDADE_MOMENTO_REACAO_TIPO_CHAVE', 'IDADE_MOMENTO_REACAO_TIPO_VALOR',
       'IDADE_MOMENTO_REACAO_VALOR', 'DURACAO_TIPO_VALOR',
       'DURACAO_TIPO_CHAVE', 'DURACAO_VALOR',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR',
       'IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR', 'HASH_SILVER'],
      dtype='object')

In [ ]:
# Lista base de colunas (use sempre os nomes de origem aqui)
gold_cols = [
    'UF',
    'UF_CHAVE',
    'UF_VALOR',

    'TIPO_ENTRADA_VIGIMED',
    'TIPO_ENTRADA_VIGIMED_CHAVE',
    'TIPO_ENTRADA_VIGIMED_VALOR',

    'RECEBIDO_DE',
    'RECEBIDO_DE_CHAVE',
    'RECEBIDO_DE_VALOR',

    'IDENTIFICACAO_NOTIFICACAO',

    'DATA_INCLUSAO_SISTEMA',
    'DATA_ULTIMA_ATUALIZACAO',
    'DATA_NOTIFICACAO',

    'TIPO_NOTIFICACAO',
    'TIPO_NOTIFICACAO_CHAVE',
    'TIPO_NOTIFICACAO_VALOR',

    'NOTIFICACAO_PARENT_CHILD',
    'NOTIFICACAO_PARENT_CHILD_CHAVE',
    'NOTIFICACAO_PARENT_CHILD_VALOR',

    'DATA_NASCIMENTO',

    'IDADE_MOMENTO_REACAO',
    'IDADE_MOMENTO_REACAO_TIPO_CHAVE',
    'IDADE_MOMENTO_REACAO_TIPO_VALOR',
    'IDADE_MOMENTO_REACAO_VALOR',

    'GRUPO_IDADE',
    'GRUPO_IDADE_CHAVE',
    'GRUPO_IDADE_VALOR',

    'IDADE_GESTACIONAL_MOMENTO_REACAO',
    'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE',
    'IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR',
    'IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR',

    'SEXO',
    'SEXO_CHAVE',
    'SEXO_VALOR',

    'GESTANTE',
    'GESTANTE_CHAVE',
    'GESTANTE_VALOR',

    'LACTANTE',
    'LACTANTE_CHAVE',
    'LACTANTE_VALOR',

    'PESO_KG',
    'ALTURA_CM',

    'REACAO_EVENTO_ADVERSO_MEDDRA',

    'GRAVE',
    'GRAVE_CHAVE',
    'GRAVE_VALOR',

    'GRAVIDADE',
    'GRAVIDADE_CHAVE',
    'GRAVIDADE_VALOR',

    'DESFECHO',
    'DESFECHO_CHAVE',
    'DESFECHO_VALOR',

    'DATA_INICIO_HORA',
    'DATA_FINAL_HORA',

    'DURACAO',
    'DURACAO_TIPO_CHAVE',
    'DURACAO_TIPO_VALOR',
    'DURACAO_VALOR',

    'RELACAO_MEDICAMENTO_EVENTO',
    'RELACAO_MEDICAMENTO_EVENTO_CHAVE',
    'RELACAO_MEDICAMENTO_EVENTO_VALOR',

    'NOME_MEDICAMENTO_WHODRUG',

    'ACAO_ADOTADA',
    'ACAO_ADOTADA_CHAVE',
    'ACAO_ADOTADA_VALOR',

    'NOTIFICADOR',
    'NOTIFICADOR_CHAVE',
    'NOTIFICADOR_VALOR',

    'ATUALIZADO', 
    'HASH_BRONZE',
    'HASH_SILVER'
]

# Dicionário de renomes: chave = nome original, valor = novo nome
rename_map = {
    'LLT_CHAVE_x': 'INDICACAO_MEDDRA_LLT_CHAVE',
    'LLT_CHAVE_y': 'INDICACAO_RELATADA_NOTIFICADOR_INICIAL_LLT_CHAVE',
    # adicione outras renomeações aqui, ex:
    # 'NUMELO_LOTE': 'NUMERO_LOTE',
}

# Lista final de colunas já com renomeação aplicada
final_cols = [rename_map.get(col, col) for col in gold_cols]

# Opcional: se quiser aplicar no DataFrame pandas
fat = hist_silver_dedup.rename(columns=rename_map)
fat = fat[final_cols]

In [60]:
fat["HASH_GOLD"] = build_row_hash(fat, final_cols, algo="sha256", sep="|")

In [61]:
hist_silver_dedup.to_parquet(Path(project_root) / "data/03_gold/dim_notificacoes/dim_notificacoes.parquet", index=False)