# Análises de Desproporcionalidade – Projeto Vigimed 🇧🇷
# Analysis of Disproportionality – Vigimed Project


https://github.com/mlab-inf-ufrgs/vigimed/tree/main/data/03_gold

- 🌐 [Silmara G. Barnabé](https://www.linkedin.com/in/silmarabarnabe/) | 📧 silmara.barnabe@gmail.com | 📲 +55 51 993 605 067
- 🌐 [Silmara G. Barnabé](https://www.linkedin.com/in/silmarabarnabe/) | 📧 silmara.barnabe@gmail.com | 📲 +55 51 993 605 067
- 🌐 [Silmara G. Barnabé](https://www.linkedin.com/in/silmarabarnabe/) | 📧 silmara.barnabe@gmail.com | 📲 +55 51 993 605 067

Método.: [Metodologia de Base para Ciência de Dados. IBM Analytics, White Paper (2015)](https://www.ibm.com/downloads/cas/B1WQ0GM2) by [John B. Rollins, Ph.D.](https://www.linkedin.com/in/john-b-rollins-phd-pe-inactive-115460/)
- Estágio 1: Entendimento de negócios
- Estágio 2: Abordagem analítica
- Estágio 3: Requisitos de dados
- Estágio 4: Coleta de dados
- Estágio 5: Entendimento dos dados
- Estágio 6: Preparação de dados
- Estágio 7: Modelagem
- Estágio 8: Avaliação
- Estágio 9: Implementação
- Estágio 10: Feedback

# **1️⃣ Entendimento de negócios**

## **1.1 Contexto**

## **1.2 O Problema**

## **1.3 Stakeholders**

## **1.4 SLA**

## **1.5 Perguntas**

## **1.6 Critérios**

# **2️⃣ Abordagem analítica**

# **3️⃣ Requisitos de dados**

### 3.1 Origem dos Dados

### 3.2 Bibliotecas

In [ ]:
#Bases de Dados 
from pathlib import Path
import pandas as pd
import duckdb

# Visualização
import plotly.express as px

# Modelagem 
import numpy as np 
from typing import List, Optional

# **4️⃣ Coleta de dados**

In [ ]:



# Configurações de exibição
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaylimit = 100
%config SqlMagic.named_parameters = "enabled"
%config SqlMagic.autocommit = True

# Se preferir memória: 
%sql duckdb:///:memory:

Connecting to 'duckdb:///:memory:'

In [2]:
path = Path("C:/Users/silma/Projetos/vigimed/data/03_gold")
# Caminhos completos para o DuckDB (parâmetros nomeados não expandem expressões)
path_atc = str(path / 'dim_atc/dim_atc.parquet')
path_fat_medicamentos = str(path / 'fat_medicamentos/fat_medicamentos.parquet')
path_dim_notificacoes = str(path / 'dim_notificacoes/dim_notificacoes.parquet')
path_fat_reacoes = str(path / 'fat_reacoes/fat_reacoes.parquet')
path_dim_soc_llt = str(path / 'dim_soc_llt/dim_soc_llt.parquet')

In [3]:
%sql ROLLBACK;

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [4]:
%%sql
DROP TABLE IF EXISTS dim_atc;
CREATE TABLE dim_atc AS
SELECT * FROM read_parquet(:path_atc);

DROP TABLE IF EXISTS fat_medicamentos;
CREATE TABLE fat_medicamentos AS
SELECT *
FROM read_parquet(:path_fat_medicamentos);

DROP TABLE IF EXISTS dim_notificacoes;
CREATE TABLE dim_notificacoes AS
SELECT *
FROM read_parquet(:path_dim_notificacoes);

DROP TABLE IF EXISTS fat_reacoes;
CREATE TABLE fat_reacoes AS
SELECT *
FROM read_parquet(:path_fat_reacoes);

DROP TABLE IF EXISTS dim_soc_llt;
CREATE TABLE dim_soc_llt AS
SELECT *
FROM read_parquet(:path_dim_soc_llt);

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

# **5️⃣ Entendimento dos dados**

### dim_notificacoes

In [5]:
%%sql 
select * from dim_notificacoes limit 2

Running query in 'duckdb:///:memory:'

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,...,SEXO_CHAVE,GESTANTE_VALOR,GESTANTE_CHAVE,LACTANTE_VALOR,LACTANTE_CHAVE,GRAVE_VALOR,GRAVE_CHAVE,DESFECHO_VALOR,DESFECHO_CHAVE,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,NOTIFICADOR_VALOR,NOTIFICADOR_CHAVE,IDADE_MOMENTO_REACAO_TIPO_CHAVE,IDADE_MOMENTO_REACAO_TIPO_VALOR,IDADE_MOMENTO_REACAO_VALOR,DURACAO_TIPO_VALOR,DURACAO_TIPO_CHAVE,DURACAO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR,HASH_SILVER
0,SP,EMPRESAS FARMACEUTICAS,EMPRESA FARMACEUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICACAO ESPONTANEA,None,1990-01-31,30 ano,None,None,Feminino,Năo,Năo,68.0,165,Hemiparesia,Sim,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 dia,...,1,NĂO,2,NĂO,2,SIM,1,RECUPERADO,1,CONCOMITANTE,2,NAO APLICAVEL,2,MEDICO,4,1,ANO,30.0,DIA,4,12.0,0,DESCONHECIDO,NaN,3c04663c8c6a69bba2510ab19fa043d1d6670b81e42857...
1,SP,EMPRESAS FARMACEUTICAS,EMPRESA FARMACEUTICA,BR-ANVISA-300208322,2023-09-01,2023-09-01,NaT,NOTIFICACAO ESPONTANEA,None,NaT,None,None,None,Feminino,Năo,Năo,None,None,Cefaleia,Năo,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,DESCONHECIDO,2021-01-22,NaT,None,...,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,SUSPEITO,1,NAO APLICAVEL,2,CONSUMIDOR OU OUTRO NAO PROFISSIONAL DE SAUDE,2,0,DESCONHECIDO,NaN,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN,716905c5a2cc460902e5682c94bd1379f674208b0c6ef5...

In [6]:
%%sql 
select IDENTIFICACAO_NOTIFICACAO,count(1) as qt
from dim_notificacoes 
group by 1
having qt > 1
limit 10

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [IDENTIFICACAO_NOTIFICACAO, qt]
Index: []

In [7]:
%%sql 
select * from dim_notificacoes 
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,...,SEXO_CHAVE,GESTANTE_VALOR,GESTANTE_CHAVE,LACTANTE_VALOR,LACTANTE_CHAVE,GRAVE_VALOR,GRAVE_CHAVE,DESFECHO_VALOR,DESFECHO_CHAVE,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,NOTIFICADOR_VALOR,NOTIFICADOR_CHAVE,IDADE_MOMENTO_REACAO_TIPO_CHAVE,IDADE_MOMENTO_REACAO_TIPO_VALOR,IDADE_MOMENTO_REACAO_VALOR,DURACAO_TIPO_VALOR,DURACAO_TIPO_CHAVE,DURACAO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR,HASH_SILVER
0,SP,SERVICOS DE SAUDE,CENTRO REGIONAL DE FARMACOVIGILANCIA,BR-ANVISA-300171130,2023-01-10,2023-01-10,2023-01-10,NOTIFICACAO ESPONTANEA,None,NaT,58 ano,Adulto,None,Masculino,None,None,None,None,Prurido oral,Năo,None,RECUPERADO,2023-01-10,2023-01-10,None,...,2,DESCONHECIDO,0,DESCONHECIDO,0,NĂO,2,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,FARMACEUTICO,3,1,ANO,58.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN,6c94238fcb1543d2c24c3036169c67658af91aa5c58794...

### fat_medicamentos

In [8]:
%%sql 
select * from fat_medicamentos 
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,ATC_CODE_LEVEL_4,DETENTOR_REGISTRO_CHAVE,CONCENTRACAO_TIPO_VALOR,CONCENTRACAO_TIPO_CHAVE,CONCENTRACAO_VALOR,CONCENTRACAO_VALOR_NUMERADOR,CONCENTRACAO_VALOR_DENOMINADOR,COMPONENTE_SUSPEITO_VALOR,COMPONENTE_SUSPEITO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,PROB_ADIC_ABUSO,PROB_ADIC_ERRO_DE_MEDICACAO,PROB_ADIC_EXPOSICAO_OCUPACIONAL,PROB_ADIC_FALSIFICACAO,PROB_ADIC_LOTES_TESTADOS_E_DENTRO_DAS_ESPECIFICACOES,PROB_ADIC_LOTES_TESTADOS_E_FORA_DAS_ESPECIFICACOES,PROB_ADIC_MEDICAMENTO_TOMADO_FORA_DA_DATA_DE_VALIDADE,PROB_ADIC_MEDICAMENTO_TOMADO_PELO_PAI,PROB_ADIC_SUPERDOSE,PROB_ADIC_USO_INCORRETO,PROB_ADIC_USO_OFF_LABEL_USO_SEM_REGISTRO,INDICACAO_MEDDRA_LLT_CHAVE,INDICACAO_RELATADA_NOTIFICADOR_INICIAL_LLT_CHAVE,DOSE_TIPO_VALOR,DOSE_TIPO_CHAVE,DOSE_VALOR,FREQUENCIA_DOSE,POSOLOGIA,DURACAO_TIPO_CHAVE,DURACAO_VALOR,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA_CHAVE,VIA_ADMINISTRACAO_CHAVE,VIA_ADMINISTRACAO_MAE_PAI_CHAVE,NUMELO_LOTE,ATUALIZADO,HASH_BRONZE,HASH_SILVER,HASH_GOLD
0,BR-ANVISA-300171130,CONCOMITANTE,2,NOVALGINA,METAMIZOLE SODIUM,N02BB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLIGRAM (MG),1,1000.0,,None,0,NaN,2023-01-10,2023-01-10,14,6,5,None,2026-01-15,E8421CD05C810683B262026252DF85A8CB234025058ECE...,eb4d0c92502c072339426ef1c74c09d2bcc4e79034b55b...,d7c0da664d119ffd091652c43cc25448b20c13ddf821ca...
1,BR-ANVISA-300171130,CONCOMITANTE,2,BUSCOPAN,HYOSCINE BUTYLBROMIDE,A03BB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLIGRAM (MG),1,20.0,,None,0,NaN,2023-01-10,2023-01-10,14,6,5,None,2026-01-15,4AD3B12C405DB5047BDAF8B3178C11665390EA4407B788...,423f51a6d297a64fd485f8753ada0ff0f9d01daf3f38e4...,38e10a5bb1179c1cba8a6f503c91404bd62342c3a5b0eb...
2,BR-ANVISA-300171130,SUSPEITO,1,HENETIX,IOBITRIDOL,V08AB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLILITRE (ML),2,106.0,,None,0,NaN,2023-01-10,2023-01-10,16,6,5,22WC366B,2026-01-15,C2F0D1941A6EB562A55B581E0F847EAB15244D0E276E9A...,b75c0cbe97ba4062e3e1adbe6c19ae965958e00c4aad07...,c08abb4a449234aa328b3f322d46b72daa575fc276c249...

### fat_reacoes

In [9]:
%%sql 
select * from fat_reacoes limit 2

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,HASH_BRONZE,HASH_SILVER,DATA_INICIO_HORA,DATA_FINAL_HORA,ATUALIZADO,LLT_CHAVE,GRAVE_CHAVE,DESFECHO_CHAVE,DURACAO_TIPO_CHAVE,DURACAO_VALOR,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300000004,e0102770fa7fe4e3e3f58fe5a3675e13fffd3dc4721c0b...,5e664ee6fcb8b1bf52f1a7aa7ef1853a166bf9cedfc2ff...,NaT,NaT,2025-11-17,4114,2,3,4,3.0,0,0,0,0,0,0
1,BR-ANVISA-300000005,21a5c47062a6ba174af4058e70e681ff97ba91db760676...,497e70fa95ec2b543e9cb065388b857d545c25059f7f69...,2018-11-22,2018-11-22,2025-11-17,9107,1,3,0,NaN,0,0,0,0,1,0

In [10]:
%%sql 
select * from fat_reacoes 
left join dim_soc_llt using (LLT_CHAVE)
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,HASH_BRONZE,HASH_SILVER,DATA_INICIO_HORA,DATA_FINAL_HORA,ATUALIZADO,LLT_CHAVE,GRAVE_CHAVE,DESFECHO_CHAVE,DURACAO_TIPO_CHAVE,DURACAO_VALOR,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA,SOC_CHAVE,SOC_VALOR,HLGT,HLT,PT,REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR
0,BR-ANVISA-300171130,bc80540a7cbefd2aca595577b9eefb0b73bc6ecac48230...,2249bcf07a8c777fa3000b360111166561c3169531d014...,2023-01-10,2023-01-10,2025-11-17,5029,2,3,0,NaN,0,0,0,0,0,0,14,Distúrbios gastrointestinais,Quadros clínicos de tecido mole oral,Estomatite e ulceração,Úlcera aftosa,Úlceras aftosas orais
1,BR-ANVISA-300171130,33cda90c040b2714862d636436c2f0105c1307a9b593d5...,5fd9d9ac6bbfa4ac4cc223114f7544e97b92b1d83ad75a...,2023-01-10,2023-01-10,2025-11-17,10541,2,3,0,NaN,0,0,0,0,0,0,13,"Distúrbios respiratórios, torácicos e do media...",Distúrbios brônquicos (excl. neoplasias),Quadros clínicos brônquicos NCO,Alteração brônquica,Alteração brônquica
2,BR-ANVISA-300171130,8d89edb6a4354411417b35144154c636741cce9c0dc40f...,22ed5404cb6f62dbd22e025be5e5b9b4b1a9dab16268e9...,2023-01-10,2023-01-10,2025-11-17,10898,2,3,0,NaN,0,0,0,0,0,0,13,"Distúrbios respiratórios, torácicos e do media...",Distúrbios respiratórios NCO,Distúrbios do trato respiratório NCO,Aspiração,Aspiração de vômito

### dim_soc_llt

In [11]:
%%sql 
select * from dim_soc_llt limit 2

Running query in 'duckdb:///:memory:'

   SOC_CHAVE               SOC_VALOR                            HLGT                                     HLT                  PT  LLT_CHAVE REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR
0         26  Circunstâncias sociais  Fatores relacionados ao gênero  Circunstâncias relacionadas à gravidez         Amamentação          1                          Amamentação
1         26  Circunstâncias sociais  Fatores relacionados ao gênero                 Questões de sexualidade  Abstinência sexual          2                   Abstinência sexual

## 🔎 Medicamentos

#### L01FA01_Rituximab

In [12]:
%%sql
with fat as (
SELECT IDENTIFICACAO_NOTIFICACAO,(CASE 
    WHEN atc.ATC_CODE_LEVEL_4 ='L01FA' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%rituximab%' THEN 'L01FA01_Rituximab' 
    WHEN atc.ATC_CODE_LEVEL_4 ='L01FA' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) NOT LIKE '%rituximab%' THEN 'Missing'
    ELSE 'Outros'
END) as ATC_5_LEVEL_NAME
FROM fat_medicamentos as fat
INNER JOIN dim_atc AS atc
    ON fat.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4 
)
select ATC_5_LEVEL_NAME
,count(distinct IDENTIFICACAO_NOTIFICACAO) AS qt_notificacoes
,count(1) AS qt
,min(IDENTIFICACAO_NOTIFICACAO) as ex1_id
,max(IDENTIFICACAO_NOTIFICACAO) as ex2_id
from fat 
group by 1

Running query in 'duckdb:///:memory:'

    ATC_5_LEVEL_NAME  qt_notificacoes      qt               ex1_id               ex2_id
0             Outros           309014  779704  BR-ANVISA-300000004  BR-ANVISA-300411390
1  L01FA01_Rituximab             3303    3881  BR-ANVISA-300101432  BR-ANVISA-300411299
2            Missing              134     137  BR-ANVISA-300104487  BR-ANVISA-300409611

In [13]:
%%sql
select IDENTIFICACAO_NOTIFICACAO,ATC_CODE_LEVEL_4,PRINCIPIOS_ATIVOS_WHODRUG 
from fat_medicamentos 
where IDENTIFICACAO_NOTIFICACAO in ('BR-ANVISA-300104487','BR-ANVISA-300409611')

Running query in 'duckdb:///:memory:'

  IDENTIFICACAO_NOTIFICACAO ATC_CODE_LEVEL_4 PRINCIPIOS_ATIVOS_WHODRUG
0       BR-ANVISA-300104487            L01FA              OBINUTUZUMAB
1       BR-ANVISA-300409611            L01XX                VENETOCLAX
2       BR-ANVISA-300409611            L01FA             OBINUTUZUMABE
3       BR-ANVISA-300409611            L01FA             OBINUTUZUMABE

#### L04AA24_Abatacept

In [14]:
%%sql
with fat as (
SELECT IDENTIFICACAO_NOTIFICACAO,(CASE 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AA' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%abatacept%' THEN 'L04AA24_Abatacept' 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AA' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) NOT LIKE '%abatacept%' THEN 'Missing'
    ELSE 'Outros'
END) as ATC_5_LEVEL_NAME
FROM fat_medicamentos as fat
INNER JOIN dim_atc AS atc
    ON fat.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4 
)
select ATC_5_LEVEL_NAME
,count(distinct IDENTIFICACAO_NOTIFICACAO) AS qt_notificacoes
,count(1) AS qt
,min(IDENTIFICACAO_NOTIFICACAO) as ex1_id
,max(IDENTIFICACAO_NOTIFICACAO) as ex2_id
from fat 
group by 1

Running query in 'duckdb:///:memory:'

    ATC_5_LEVEL_NAME  qt_notificacoes      qt               ex1_id               ex2_id
0            Missing             4849    6654  BR-ANVISA-300000286  BR-ANVISA-300411192
1             Outros           307801  776881  BR-ANVISA-300000004  BR-ANVISA-300411390
2  L04AA24_Abatacept              172     187  BR-ANVISA-300010039  BR-ANVISA-300410110

In [15]:
%%sql
select distinct IDENTIFICACAO_NOTIFICACAO,ATC_CODE_LEVEL_4,PRINCIPIOS_ATIVOS_WHODRUG 
from fat_medicamentos 
where IDENTIFICACAO_NOTIFICACAO in ('BR-ANVISA-300000286','BR-ANVISA-300411192')
order by 1

Running query in 'duckdb:///:memory:'

   IDENTIFICACAO_NOTIFICACAO ATC_CODE_LEVEL_4    PRINCIPIOS_ATIVOS_WHODRUG
0        BR-ANVISA-300000286            L04AA                  OCRELIZUMAB
1        BR-ANVISA-300411192            R05DA           FOSFATO DE CODEÍNA
2        BR-ANVISA-300411192            S01AA                 AZITHROMYCIN
3        BR-ANVISA-300411192            A02BC              DEXLANSOPRAZOLE
4        BR-ANVISA-300411192            L01FA                   RITUXIMABE
5        BR-ANVISA-300411192            S01BA           METHYLPREDNISOLONE
6        BR-ANVISA-300411192             D07A                   PREDNISONE
7        BR-ANVISA-300411192            A03AX                   SIMETICONE
8        BR-ANVISA-300411192            H02AB                   PREDNISONE
9        BR-ANVISA-300411192            D04AA  CLORIDRATO DE DIFENIDRAMINA
10       BR-ANVISA-300411192            D07AC           METHYLPREDNISOLONE
11       BR-ANVISA-300411192            S01BA                   PREDNISONE
12       BR-ANVISA-300411192            H02AB           METHYLPREDNISOLONE
13       BR-ANVISA-300411192            C10AA        ROSUVASTATINA CÁLCICA
14       BR-ANVISA-300411192            L04AA     MICOFENOLATO DE MOFETILA
15       BR-ANVISA-300411192            D10AF                 AZITHROMYCIN
16       BR-ANVISA-300411192            J01FA                 AZITHROMYCIN
17       BR-ANVISA-300411192            D07AA           METHYLPREDNISOLONE
18       BR-ANVISA-300411192            A07EA                   PREDNISONE
19       BR-ANVISA-300411192            A02BC                  PANTOPRAZOL

#### L04AB01_Etanercept

In [16]:
%%sql
with fat as (
SELECT IDENTIFICACAO_NOTIFICACAO,(CASE 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AB' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%etanercept%' THEN 'L04AB01_Etanercept' 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AB' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) NOT LIKE '%etanercept%' THEN 'Missing'
    ELSE 'Outros'
END) as ATC_5_LEVEL_NAME
FROM fat_medicamentos as fat
INNER JOIN dim_atc AS atc
    ON fat.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4 
)
select ATC_5_LEVEL_NAME
,count(distinct IDENTIFICACAO_NOTIFICACAO) AS qt_notificacoes
,count(1) AS qt
,min(IDENTIFICACAO_NOTIFICACAO) as ex1_id
,max(IDENTIFICACAO_NOTIFICACAO) as ex2_id
from fat 
group by 1

Running query in 'duckdb:///:memory:'

     ATC_5_LEVEL_NAME  qt_notificacoes      qt               ex1_id               ex2_id
0             Missing            17943   23856  BR-ANVISA-300000144  BR-ANVISA-300411281
1              Outros           297467  759385  BR-ANVISA-300000004  BR-ANVISA-300411390
2  L04AB01_Etanercept              382     481  BR-ANVISA-300001036  BR-ANVISA-300403906

In [17]:
%%sql
select distinct IDENTIFICACAO_NOTIFICACAO,ATC_CODE_LEVEL_4,PRINCIPIOS_ATIVOS_WHODRUG 
from fat_medicamentos 
where ATC_CODE_LEVEL_4='L04AB' and IDENTIFICACAO_NOTIFICACAO in ('BR-ANVISA-300000144','BR-ANVISA-300411281')
order by 1

Running query in 'duckdb:///:memory:'

  IDENTIFICACAO_NOTIFICACAO ATC_CODE_LEVEL_4 PRINCIPIOS_ATIVOS_WHODRUG
0       BR-ANVISA-300000144            L04AB                INFLIXIMAB
1       BR-ANVISA-300411281            L04AB               INFLIXIMABE

#### L04AB02_Infliximab

In [18]:
%%sql
with fat as (
SELECT IDENTIFICACAO_NOTIFICACAO,(CASE 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AB' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%infliximab%' THEN 'L04AB02_Infliximab' 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AB' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) NOT LIKE '%infliximab%' THEN 'Missing'
    ELSE 'Outros'
END) as ATC_5_LEVEL_NAME
FROM fat_medicamentos as fat
INNER JOIN dim_atc AS atc
    ON fat.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4 
)
select ATC_5_LEVEL_NAME
,count(distinct IDENTIFICACAO_NOTIFICACAO) AS qt_notificacoes
,count(1) AS qt
,min(IDENTIFICACAO_NOTIFICACAO) as ex1_id
,max(IDENTIFICACAO_NOTIFICACAO) as ex2_id
from fat 
group by 1

Running query in 'duckdb:///:memory:'

     ATC_5_LEVEL_NAME  qt_notificacoes      qt               ex1_id               ex2_id
0             Missing             7266    8679  BR-ANVISA-300001036  BR-ANVISA-300411216
1              Outros           297467  759385  BR-ANVISA-300000004  BR-ANVISA-300411390
2  L04AB02_Infliximab            11206   15658  BR-ANVISA-300000144  BR-ANVISA-300411281

In [19]:
%%sql
select distinct IDENTIFICACAO_NOTIFICACAO,ATC_CODE_LEVEL_4,PRINCIPIOS_ATIVOS_WHODRUG 
from fat_medicamentos 
where ATC_CODE_LEVEL_4='L04AB' and IDENTIFICACAO_NOTIFICACAO in ('BR-ANVISA-300001036','BR-ANVISA-300411216')
order by 1

Running query in 'duckdb:///:memory:'

  IDENTIFICACAO_NOTIFICACAO ATC_CODE_LEVEL_4 PRINCIPIOS_ATIVOS_WHODRUG
0       BR-ANVISA-300001036            L04AB                ETANERCEPT
1       BR-ANVISA-300411216            L04AB       CERTOLIZUMABE PEGOL

#### L04AB04_Adalimumab

#### L04AB05_Certolizumab

#### L04AB06_Golimumab

#### L04AC07_Tocilizumab

#### L04AF02_Baricitinib

#### L04AF03_Upadacitinib

In [20]:
%%sql
with fat as (
SELECT IDENTIFICACAO_NOTIFICACAO,(CASE 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AF' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%upadacitinib%' THEN 'L04AF03_Upadacitinib' 
    WHEN atc.ATC_CODE_LEVEL_4 ='L04AF' and LOWER(fat.PRINCIPIOS_ATIVOS_WHODRUG) NOT LIKE '%upadacitinib%' THEN 'Missing'
    ELSE 'Outros'
END) as ATC_5_LEVEL_NAME
FROM fat_medicamentos as fat
INNER JOIN dim_atc AS atc
    ON fat.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4 
)
select ATC_5_LEVEL_NAME
,count(distinct IDENTIFICACAO_NOTIFICACAO) AS qt_notificacoes
,count(1) AS qt
,min(IDENTIFICACAO_NOTIFICACAO) as ex1_id
,max(IDENTIFICACAO_NOTIFICACAO) as ex2_id
from fat 
group by 1

Running query in 'duckdb:///:memory:'

       ATC_5_LEVEL_NAME  qt_notificacoes      qt               ex1_id               ex2_id
0               Missing              161     184  BR-ANVISA-300184118  BR-ANVISA-300407455
1  L04AF03_Upadacitinib              290     376  BR-ANVISA-300184820  BR-ANVISA-300410000
2                Outros           310097  783162  BR-ANVISA-300000004  BR-ANVISA-300411390

In [21]:
%%sql
select distinct IDENTIFICACAO_NOTIFICACAO,ATC_CODE_LEVEL_4,PRINCIPIOS_ATIVOS_WHODRUG 
from fat_medicamentos 
where ATC_CODE_LEVEL_4='L04AF' and IDENTIFICACAO_NOTIFICACAO in ('BR-ANVISA-300184118','BR-ANVISA-300407455')  
order by 1

Running query in 'duckdb:///:memory:'

  IDENTIFICACAO_NOTIFICACAO ATC_CODE_LEVEL_4 PRINCIPIOS_ATIVOS_WHODRUG
0       BR-ANVISA-300184118            L04AF              BARICITINIBE
1       BR-ANVISA-300407455            L04AF              BARICITINIBE

#### Plots

In [25]:
%%sql resumo_por_ano <<
with fat_med as (
SELECT 
    fat_medicamentos.IDENTIFICACAO_NOTIFICACAO, 
    atc.ATC_CODE_LEVEL_4_LEVEL_NAME,
    (
        CASE 
            WHEN atc.ATC_CODE_LEVEL_4 IN ('L04AB', 'L04AA','L01FA', 'L04AC','L04AF') 
                THEN (
                    CASE 
                        /*Rituximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%rituximab%' THEN 'L01FA01_Rituximab'
                        /*Abatacept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%abatacept%' THEN 'L04AA24_Abatacept'
                        /*Etanercept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%etanercept%' THEN 'L04AB01_Etanercept'
                        /*Infliximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%infliximab%' THEN 'L04AB02_Infliximab'
                        /*Adalimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%adalimumab%' THEN 'L04AB04_Adalimumab'
                        /*Certolizumab Pegol*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%certolizumab%' THEN 'L04AB05_Certolizumab Pegol'   
                        /*Golimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%golimumab%' THEN 'L04AB06_Golimumab'
                        /*Tocilizumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%tocilizumab%' THEN 'L04AC07_Tocilizumab'
                        /*Baricitinib */ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%baricitinib%' THEN 'L04AF02_Baricitinib'
                        /*Upadacitinib*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%upadacitinib%' THEN 'L04AF03_Upadacitinib' 
                        ELSE 'Outros'
                    END
                )
            ELSE 'Outros'
        END
    ) AS ATC_LEVEL_5
FROM fat_medicamentos
INNER JOIN dim_atc AS atc
    ON fat_medicamentos.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4
)
,fat as (
select 
    dim.IDENTIFICACAO_NOTIFICACAO AS ID
    ,strftime(TRY_CAST(dim.DATA_INCLUSAO_SISTEMA AS DATE), '%Y-%m') as DATA_NOTIFICACAO
    ,fat_med.ATC_LEVEL_5 
from dim_notificacoes as dim
inner join fat_med using (IDENTIFICACAO_NOTIFICACAO) 
)

SELECT DATA_NOTIFICACAO
,ATC_LEVEL_5,
COUNT(DISTINCT ID) AS QT_NOTIFICACOES
from fat
group by 1,2

Running query in 'duckdb:///:memory:'

In [26]:
resumo_por_ano.head()

  DATA_NOTIFICACAO                 ATC_LEVEL_5  QT_NOTIFICACOES
0          2025-09  L04AB05_Certolizumab Pegol                9
1          2025-10         L04AC07_Tocilizumab                6
2          2025-11          L04AB02_Infliximab              128
3          2025-12          L04AB02_Infliximab               21
4          2019-02                      Outros              211

In [ ]:

casos_ano = resumo_por_ano.assign(ANO=resumo_por_ano['DATA_NOTIFICACAO'].str[:4]).groupby('ANO', as_index=False)['QT_NOTIFICACOES'].sum()
casos_ano = casos_ano.sort_values('ANO')

fig = px.bar(casos_ano, x='ANO', y='QT_NOTIFICACOES',
             title='Casos (notificações) por ano',
             labels={'ANO': 'Ano', 'QT_NOTIFICACOES': 'Quantidade de notificações'},
             text_auto=True)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [34]:

casos_ano = resumo_por_ano.assign(ANO=resumo_por_ano['DATA_NOTIFICACAO'].str[:4]).groupby(['ANO','ATC_LEVEL_5'], as_index=False)['QT_NOTIFICACOES'].sum()
casos_ano = casos_ano.sort_values(['ANO','ATC_LEVEL_5'])

# Paleta fixa por ATC ("Outros" em cinza, demais com cores distintas)
atcs_ordenados = sorted(casos_ano['ATC_LEVEL_5'].unique(), key=lambda x: (x == 'Outros', x))
paleta_qualitativa = px.colors.qualitative.Bold + px.colors.qualitative.Set3
color_discrete_map = {atc: paleta_qualitativa[i] for i, atc in enumerate(atcs_ordenados) if atc != 'Outros'}
if 'Outros' in atcs_ordenados:
    color_discrete_map['Outros'] = '#9E9E9E'

fig = px.bar(casos_ano, x='ANO', y='QT_NOTIFICACOES', color='ATC_LEVEL_5',
             color_discrete_map=color_discrete_map,
             title='Casos (notificações) por ano',
             labels={'ANO': 'Ano', 'QT_NOTIFICACOES': 'Quantidade de notificações'},
             text_auto=True)
fig.update_layout(xaxis_tickangle=-45, height=600)
fig.show()

# **6️⃣ Preparação de dados**

### 6.1 Aplicacao de regras de negócio

In [50]:
%%sql
DROP TABLE IF EXISTS fat_analytics;

CREATE TABLE fat_analytics AS
with fat_med as (
SELECT 
    fat_medicamentos.IDENTIFICACAO_NOTIFICACAO, 
    atc.ATC_CODE_LEVEL_4_LEVEL_NAME,
    (
        CASE 
            WHEN atc.ATC_CODE_LEVEL_4 IN ('L04AB', 'L04AA','L01FA', 'L04AC','L04AF') 
                THEN (
                    CASE 
                        /*Rituximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%rituximab%' THEN 'L01FA01_Rituximab'
                        /*Abatacept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%abatacept%' THEN 'L04AA24_Abatacept'
                        /*Etanercept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%etanercept%' THEN 'L04AB01_Etanercept'
                        /*Infliximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%infliximab%' THEN 'L04AB02_Infliximab'
                        /*Adalimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%adalimumab%' THEN 'L04AB04_Adalimumab'
                        /*Certolizumab Pegol*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%certolizumab%' THEN 'L04AB05_Certolizumab Pegol'   
                        /*Golimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%golimumab%' THEN 'L04AB06_Golimumab'
                        /*Tocilizumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%tocilizumab%' THEN 'L04AC07_Tocilizumab'
                        /*Baricitinib */ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%baricitinib%' THEN 'L04AF02_Baricitinib'
                        /*Upadacitinib*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%upadacitinib%' THEN 'L04AF03_Upadacitinib' 
                        ELSE 'Outros'
                    END
                )
            ELSE 'Outros'
        END
    ) AS ATC_CODE_LEVEL_5_LEVEL_NAME
FROM fat_medicamentos
INNER JOIN dim_atc AS atc
    ON fat_medicamentos.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4
)
,fat as (
select 
    dim.IDENTIFICACAO_NOTIFICACAO AS ID
    ,dim.SEXO
    ,fat_med.ATC_CODE_LEVEL_4_LEVEL_NAME AS ATC_LEVEL_4
    ,fat_med.ATC_CODE_LEVEL_5_LEVEL_NAME AS ATC_LEVEL_5  
    ,dim_soc_llt.REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR AS REACAO_LLT
    ,dim_soc_llt.PT AS REACAO_PT
from dim_notificacoes as dim
inner join fat_med using (IDENTIFICACAO_NOTIFICACAO)
inner join fat_reacoes using (IDENTIFICACAO_NOTIFICACAO)
left join dim_soc_llt on fat_reacoes.LLT_CHAVE = dim_soc_llt.LLT_CHAVE
)

-- Notificações com medicamentos específicos (não 'Outros')
select * from fat 
where ATC_LEVEL_5 <> 'Outros'

union all 

-- Notificações com 'Outros' SOMENTE se não tiverem medicamentos específicos que iremos estudar
select * from fat as a
where a.ATC_LEVEL_5 = 'Outros'
and a.ID NOT IN (
    SELECT b.ID
    FROM fat as b
    WHERE b.ATC_LEVEL_5 <> 'Outros' 
)

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

### 6.2 Checagens

In [51]:
%%sql
select * from fat_analytics limit 5

Running query in 'duckdb:///:memory:'

                    ID       SEXO                                        ATC_LEVEL_4         ATC_LEVEL_5                                 REACAO_LLT                                  REACAO_PT
0  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab  Lesão da medula espinhal na região lombar  Lesão da medula espinhal na região lombar
1  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab                Erupção no local de injeção        Erupção cutânea no local de injeção
2  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab                              Trombo apical              Trombose cardíaca ventricular
3  BR-ANVISA-300067135   Feminino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab              Urticária no local da injeção              Urticária no local de injeção
4  BR-ANVISA-300067135   Feminino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab   Peptídeo natriurético cerebral aumentado   Peptídeo natriurético cerebral aumentado

In [74]:
%%sql
select ATC_LEVEL_5,count(*) as qt,count(distinct ID) as qt_notificacoes from fat_analytics group by ATC_LEVEL_5

Running query in 'duckdb:///:memory:'

                   ATC_LEVEL_5       qt  qt_notificacoes
0                       Outros  2306743           264340
1           L04AB04_Adalimumab    11835             1519
2            L04AA24_Abatacept      676              170
3          L04AC07_Tocilizumab     3270              851
4   L04AB05_Certolizumab Pegol     5442             1177
5          L04AF02_Baricitinib      738              205
6            L04AB06_Golimumab    12092             3723
7         L04AF03_Upadacitinib     7354             1023
8           L04AB02_Infliximab    53915            10490
9           L04AB01_Etanercept     3700              359
10           L01FA01_Rituximab     9912             2971

In [53]:
%%sql
select id,count(1) from fat_analytics group by 1 having count(1) > 1 limit 2

Running query in 'duckdb:///:memory:'

                    ID  count(1)
0  BR-ANVISA-300315255         3
1  BR-ANVISA-300315256        14

In [54]:
%%sql 
select * from fat_analytics 
where id ='BR-ANVISA-300315256'

Running query in 'duckdb:///:memory:'

                     ID      SEXO                                        ATC_LEVEL_4 ATC_LEVEL_5                             REACAO_LLT                              REACAO_PT
0   BR-ANVISA-300315256  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
1   BR-ANVISA-300315256  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
2   BR-ANVISA-300315256  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
3   BR-ANVISA-300315256  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
4   BR-ANVISA-300315256  Feminino                                         MACROLIDES      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
5   BR-ANVISA-300315256  Feminino                                         MACROLIDES      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
6   BR-ANVISA-300315256  Feminino     ANGIOTENSIN II RECEPTOR BLOCKERS (ARBS), PLAIN      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
7   BR-ANVISA-300315256  Feminino     ANGIOTENSIN II RECEPTOR BLOCKERS (ARBS), PLAIN      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
8   BR-ANVISA-300315256  Feminino                        DIHYDROPYRIDINE DERIVATIVES      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
9   BR-ANVISA-300315256  Feminino                        DIHYDROPYRIDINE DERIVATIVES      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
10  BR-ANVISA-300315256  Feminino                           ANTIVERTIGO PREPARATIONS      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
11  BR-ANVISA-300315256  Feminino                           ANTIVERTIGO PREPARATIONS      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
12  BR-ANVISA-300315256  Feminino                                SULFONAMIDES, PLAIN      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
13  BR-ANVISA-300315256  Feminino                                SULFONAMIDES, PLAIN      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda

### 6.3 Persistindo a Base

In [55]:
%%sql df <<
select * from fat_analytics

Running query in 'duckdb:///:memory:'

In [56]:
df.to_parquet(path/'fat_analytical/fat_analytical.parquet', index=False)

# **7️⃣ Modelagem**

### Funcoes

In [36]:
import numpy as np
import pandas as pd
from typing import List, Optional


def disproportionality_table(
    df: pd.DataFrame,
    case_col: str = "ID",
    drug_col: str = "ATC_LEVEL_5",
    event_col: str = "REACAO_LLT",
    strata_cols: Optional[List[str]] = None,  # ex.: ["SEXO"]
    min_a: int = 3,
    correction: float = 0.5,
    require_all_methods: bool = False,
) -> pd.DataFrame:
    """
    Tabela 2x2 por (drug, event) em nível de caso (ID) com dedup:
      a = #casos com drug & event
      b = #casos com drug & não-event
      c = #casos com event & não-drug
      d = #casos sem drug & sem event
    Calcula: ROR (LCL95), PRR + chi2, BCPNN (IC/IC025), EBGM (EBGM05).
    """

    if strata_cols is None:
        strata_cols = []

    cols = [case_col, drug_col, event_col] + strata_cols
    data = df.loc[:, cols].dropna(subset=[case_col, drug_col, event_col]).copy()

    # opcional: melhora performance
    for c in [drug_col, event_col] + strata_cols:
        data[c] = data[c].astype("category")

    def _compute_one(sub: pd.DataFrame) -> pd.DataFrame:
        # Dedup caso-droga-evento para não inflar "a" por duplicatas idênticas
        pairs = sub[[case_col, drug_col, event_col]].drop_duplicates()
        if pairs.empty:
            return pd.DataFrame()

        N_total = sub[case_col].nunique()

        case_drug = sub[[case_col, drug_col]].drop_duplicates()
        n_drug = case_drug.groupby(drug_col)[case_col].nunique()

        case_evt = sub[[case_col, event_col]].drop_duplicates()
        n_evt = case_evt.groupby(event_col)[case_col].nunique()

        base = (
            pairs.groupby([drug_col, event_col])[case_col]
            .nunique()
            .rename("a")
            .reset_index()
        )

        base["n_drug"] = base[drug_col].map(n_drug).astype(int)
        base["n_evt"] = base[event_col].map(n_evt).astype(int)

        base["b"] = base["n_drug"] - base["a"]
        base["c"] = base["n_evt"] - base["a"]
        base["d"] = N_total - base["a"] - base["b"] - base["c"]
        base["N_total"] = N_total

        # critério N>=3 (a>=3)
        base = base.loc[base["a"] >= min_a].copy()
        if base.empty:
            return base

        a = base["a"].to_numpy(dtype=float)
        b = base["b"].to_numpy(dtype=float)
        c = base["c"].to_numpy(dtype=float)
        d = base["d"].to_numpy(dtype=float)

        # Correção quando alguma célula for 0
        zero_mask = (a == 0) | (b == 0) | (c == 0) | (d == 0)
        a2 = a + correction * zero_mask
        b2 = b + correction * zero_mask
        c2 = c + correction * zero_mask
        d2 = d + correction * zero_mask

        # ROR
        ror = (a2 * d2) / (b2 * c2)
        se = np.sqrt(1 / a2 + 1 / b2 + 1 / c2 + 1 / d2)
        ror_lcl95 = np.exp(np.log(ror) - 1.96 * se)

        # PRR + chi2
        prr = (a2 / (a2 + b2)) / (c2 / (c2 + d2))
        chi2 = ((a2 * d2 - b2 * c2) ** 2) * (a2 + b2 + c2 + d2) / (
            (a2 + b2) * (c2 + d2) * (a2 + c2) * (b2 + d2)
        )

        # BCPNN (IC, IC025)
        ic = np.log2((a2 * (a2 + b2 + c2 + d2)) / ((a2 + b2) * (a2 + c2)))
        ln2 = np.log(2.0)
        v_ic = (1 / (ln2**2)) * (
            (1 / a2) + (1 / (a2 + b2)) + (1 / (a2 + c2)) - (1 / (a2 + b2 + c2 + d2))
        )
        v_ic = np.clip(v_ic, 0, None)
        ic025 = ic - 2.0 * np.sqrt(v_ic)

        # EBGM (forma do artigo) + limite inferior 95% análogo
        ebgm = (a2 * (a2 + b2 + c2 + d2)) / ((a2 + b2) * (a2 + c2))
        ebgm05 = np.exp(np.log(ebgm) - 1.96 * se)

        base["ROR"] = ror
        base["ROR_LCL95"] = ror_lcl95
        base["PRR"] = prr
        base["CHI2"] = chi2
        base["IC"] = ic
        base["IC025"] = ic025
        base["EBGM"] = ebgm
        base["EBGM05"] = ebgm05

        # critérios
        base["signal_ROR"] = base["ROR_LCL95"] > 1
        base["signal_PRR"] = (base["PRR"] >= 2) & (base["CHI2"] >= 4)
        base["signal_BCPNN"] = base["IC025"] > 0
        base["signal_EBGM"] = base["EBGM05"] > 2

        if require_all_methods:
            base["signal"] = (
                base["signal_ROR"]
                & base["signal_PRR"]
                & base["signal_BCPNN"]
                & base["signal_EBGM"]
            )
        else:
            base["signal"] = (
                base["signal_ROR"]
                | base["signal_PRR"]
                | base["signal_BCPNN"]
                | base["signal_EBGM"]
            )

        return base

    if not strata_cols:
        out = _compute_one(data)
        if out.empty:
            return out
        return out.sort_values(["signal", "ROR_LCL95", "a"], ascending=[False, False, False])

    frames = []
    for keys, sub in data.groupby(strata_cols, dropna=False):
        res = _compute_one(sub)
        if res.empty:
            continue
        if not isinstance(keys, tuple):
            keys = (keys,)
        for col, val in zip(strata_cols, keys):
            res.insert(0, col, val)
        frames.append(res)

    if not frames:
        return pd.DataFrame()

    out = pd.concat(frames, ignore_index=True)
    return out.sort_values(strata_cols + ["signal", "ROR_LCL95", "a"],
                           ascending=[True]*len(strata_cols) + [False, False, False])

In [61]:

# ------------------ EXEMPLOS DE USO ------------------

# 1) Geral (ATC_LEVEL_5 x REACAO_LLT)
# tabela = disproportionality_table(df)

# 2) Estratificado por sexo
# tabela_sexo = disproportionality_table(df, strata_cols=["SEXO"])

# 3) Usando REACAO_PT no lugar de LLT
# tabela_pt = disproportionality_table(df, event_col="REACAO_PT")

# 4) Se quiser sinal apenas quando passar em TODOS os métodos (como “cross-validation” mais rígida)
# tabela_all = disproportionality_table(df, require_all_methods=True)

In [37]:
tabela = disproportionality_table(df)

NameError: name 'df' is not defined

In [63]:
tabela.head()

,ATC_LEVEL_5,REACAO_LLT,a,n_drug,n_evt,b,c,d,N_total,ROR,ROR_LCL95,PRR,CHI2,IC,IC025,EBGM,EBGM05,signal_ROR,signal_PRR,signal_BCPNN,signal_EBGM,signal
97748,L04AB05_Certolizumab Pegol,Intolerância láctea,33,1177,49,1144,16,285346,286539,514.445913,282.361287,500.050234,5367.684832,7.357158,6.701994,163.955178,89.989237,True,True,True,True,True
97739,L04AB05_Certolizumab Pegol,Intolerância alimentar,91,1177,157,1086,66,285296,286539,362.212400,262.377269,334.285188,12718.578985,7.140647,6.751338,141.107149,102.214360,True,True,True,True,True
101113,L04AB05_Certolizumab Pegol,Problema físico relacionado ao rótulo do produto,13,1177,17,1164,4,285358,286539,796.746993,259.404025,787.957944,2404.253175,7.540450,6.474055,186.166575,60.611912,True,True,True,True,True
40795,L04AB01_Etanercept,Edema no local do implante,7,359,18,352,11,286169,286539,517.350981,199.402579,507.282856,2161.631998,8.277962,6.983728,310.395079,119.635569,True,True,True,True,True
98739,L04AB05_Certolizumab Pegol,Mau funcionamento de motor de dispositivo,9,1177,13,1168,4,285358,286539,549.705051,169.045400,545.509346,1505.176169,7.396959,6.142958,168.541337,51.829863,True,True,True,True,True

# **8️⃣ Avaliação**

In [38]:
path = Path("C:/Users/silma/Projetos/vigimed/data/03_gold")
df_analytical = pd.read_parquet(path/'fat_analytical/fat_analytical.parquet')
df_analytical.head()

                    ID       SEXO                                        ATC_LEVEL_4         ATC_LEVEL_5                                 REACAO_LLT                                  REACAO_PT
0  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab  Lesão da medula espinhal na região lombar  Lesão da medula espinhal na região lombar
1  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab                Erupção no local de injeção        Erupção cutânea no local de injeção
2  BR-ANVISA-300066865  Masculino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab                              Trombo apical              Trombose cardíaca ventricular
3  BR-ANVISA-300067135   Feminino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab              Urticária no local da injeção              Urticária no local de injeção
4  BR-ANVISA-300067135   Feminino  TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...  L04AB04_Adalimumab   Peptídeo natriurético cerebral aumentado   Peptídeo natriurético cerebral aumentado

## 8.1 Geral (ATC_LEVEL_5 x REACAO_LLT)

In [39]:
tabela = disproportionality_table(df = df_analytical,
                                  case_col = 'ID',
                                  drug_col = 'ATC_LEVEL_5',
                                  event_col =  'REACAO_PT', #ou 'REACAO_LLT',
                                  #strata_cols = None,
                                  min_a = 3,
                                  correction = 0.5,
                                  require_all_methods = False)

C:\Users\silma\AppData\Local\Temp\ipykernel_24724\4051870830.py:44: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\silma\AppData\Local\Temp\ipykernel_24724\4051870830.py:47: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\silma\AppData\Local\Temp\ipykernel_24724\4051870830.py:50: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [40]:
tabela.head(20)

,ATC_LEVEL_5,REACAO_PT,a,n_drug,n_evt,b,c,d,N_total,ROR,ROR_LCL95,PRR,CHI2,IC,IC025,EBGM,EBGM05,signal_ROR,signal_PRR,signal_BCPNN,signal_EBGM,signal
48433,L04AB05_Certolizumab Pegol,Intolerância alimentar,91,1177,157,1086,66,285296,286539,362.212400,262.377269,334.285188,12718.578985,7.140647,6.751338,141.107149,102.214360,True,True,True,True,True
48437,L04AB05_Certolizumab Pegol,Intolerância láctea,33,1177,51,1144,18,285344,286539,457.282051,256.739134,444.489097,5154.640195,7.299442,6.649384,157.525563,88.442082,True,True,True,True,True
50177,L04AB05_Certolizumab Pegol,Problema físico relacionado ao rótulo do produto,13,1177,21,1164,8,285354,286539,398.367912,164.803530,393.978972,1941.384046,7.235596,6.213873,150.706275,62.346703,True,True,True,True,True
45633,L04AB05_Certolizumab Pegol,Dispositivo defeituoso,131,1177,305,1046,174,285188,286539,205.268170,162.325859,182.533140,13506.827099,6.708231,6.395350,104.563168,82.688447,True,True,True,True,True
41822,L04AB04_Adalimumab,Rabdomiólise,7,1519,8,1512,1,285019,286539,1319.532407,162.242992,1313.456221,1147.556899,7.366821,5.871665,165.057028,20.294572,True,True,True,True,True
20120,L04AB01_Etanercept,Edema no local do implante,8,359,26,351,18,286162,286539,362.345046,156.523172,354.292789,1951.352754,7.940092,6.763633,245.587315,106.087018,True,True,True,True,True
43637,L04AB05_Certolizumab Pegol,Alanina aminotransferase,7,1177,10,1170,3,285359,286539,569.092023,146.979837,565.713396,1183.843158,7.412900,5.988490,170.414019,44.012961,True,True,True,True,True
57131,L04AB06_Golimumab,Intolerância à lactose,903,3723,1566,2820,663,282153,286539,136.272990,122.458854,103.463022,39006.655196,5.471836,5.342440,44.379939,39.881098,True,True,True,True,True
50244,L04AB05_Certolizumab Pegol,Procedimento do controle do processo de fabric...,9,1177,17,1168,8,285354,286539,274.848673,105.858112,272.754673,1146.809240,7.009936,5.817530,128.884552,49.639953,True,True,True,True,True
34040,L04AB02_Infliximab,Teste de Staphylococcus positivo,38,10490,42,10452,4,276045,286539,250.901980,89.531326,249.996711,897.657959,4.627255,3.980663,24.713972,8.818881,True,True,True,True,True
23232,L04AB01_Etanercept,Necrose no local do cateter,7,359,35,352,28,286152,286539,203.232955,88.193327,199.289694,1104.985355,7.318604,6.114284,159.631755,69.272504,True,True,True,True,True
15534,L04AA24_Abatacept,Progressão da doença,12,170,158,158,146,286223,286539,148.893532,80.989553,138.453989,1513.999656,7.000163,6.108296,128.014445,69.632526,True,True,True,True,True
62849,L04AC07_Tocilizumab,Desequilíbrio de fluidos,11,851,34,840,23,285665,286539,162.645704,79.033783,160.556277,1180.031600,6.767325,5.761601,108.935128,52.934415,True,True,True,True,True
80223,L04AF03_Upadacitinib,Desconforto ungueal,13,1023,38,1010,25,285491,286539,146.985465,74.985094,145.130323,1224.362219,6.582294,5.650832,95.822581,48.884189,True,True,True,True,True
28123,L04AB02_Infliximab,Diarreia,2432,10490,3498,8058,1066,274983,286539,77.854720,72.205635,60.036734,43557.500182,4.247258,4.166215,18.991183,17.613196,True,True,True,True,True
82430,L04AF03_Upadacitinib,Hipernatremia,4,1023,9,1019,5,285511,286539,224.149951,60.103573,223.277419,491.752997,6.959857,5.223616,124.487455,33.380069,True,True,True,True,True
43350,L04AB04_Adalimumab,Vitiligo,7,1519,15,1512,8,285012,286539,164.937500,59.734637,164.182028,605.534008,6.459930,5.137116,88.030415,31.881560,True,True,True,True,True
33211,L04AB02_Infliximab,Reação relacionada a infusão,1014,10490,1455,9476,441,275608,286539,66.875360,59.690254,60.507618,18078.380545,4.250683,4.129452,19.036330,16.991061,True,True,True,True,True
33130,L04AB02_Infliximab,RNA do HIV no sangue aumentado,29,10490,34,10461,5,276044,286539,153.049919,59.232142,152.629571,642.494996,4.542163,3.812288,23.298466,9.016784,True,True,True,True,True
86749,L04AF03_Upadacitinib,Velocidade de hemossedimentação aumentada,5,1023,13,1018,8,285508,286539,175.287328,57.246197,174.435484,530.612432,6.751270,5.230209,107.729529,35.182839,True,True,True,True,True

In [43]:
tabela.query("signal==True").sort_values(by="ROR").head()

,ATC_LEVEL_5,REACAO_PT,a,n_drug,n_evt,b,c,d,N_total,ROR,ROR_LCL95,PRR,CHI2,IC,IC025,EBGM,EBGM05,signal_ROR,signal_PRR,signal_BCPNN,signal_EBGM,signal
89013,Outros,Disfonia,1657,264340,1767,262683,110,22089,286539,1.266700,1.043881,1.265029,5.763022,0.023608,-0.075076,1.016499,0.837691,True,False,False,False,True
29305,L04AB02_Infliximab,Esterase leucocitária na urina,134,10490,2921,10356,2787,273262,286539,1.268689,1.065598,1.265256,7.183121,0.325487,0.069079,1.253088,1.052494,True,False,True,False,True
93582,Outros,Pressão do LCR anormal,1269,264340,1353,263071,84,22115,286539,1.269978,1.017914,1.268682,4.504263,0.023867,-0.088900,1.016681,0.814891,True,False,False,False,True
90844,Outros,Hemianestesia,1336,264340,1424,263004,88,22111,286539,1.276350,1.028252,1.274953,4.920018,0.024308,-0.085604,1.016992,0.819308,True,False,False,False,True
28773,L04AB02_Infliximab,Edema devido a doença cardíaca,300,10490,6517,10190,6217,269832,286539,1.277791,1.136095,1.269846,16.792954,0.330471,0.157863,1.257424,1.117988,True,False,True,False,True

### Disfonia

In [44]:
tabela.query('REACAO_PT == "Disfonia"')

,ATC_LEVEL_5,REACAO_PT,a,n_drug,n_evt,b,c,d,N_total,ROR,ROR_LCL95,PRR,CHI2,IC,IC025,EBGM,EBGM05,signal_ROR,signal_PRR,signal_BCPNN,signal_EBGM,signal
2113,L01FA01_Rituximab,Disfonia,57,2971,1767,2914,1710,281858,286539,3.224182,2.470123,3.181510,83.023691,1.637443,1.245594,3.111139,2.383518,True,True,True,True,True
89013,Outros,Disfonia,1657,264340,1767,262683,110,22089,286539,1.266700,1.043881,1.265029,5.763022,0.023608,-0.075076,1.016499,0.837691,True,False,False,False,True
62943,L04AC07_Tocilizumab,Disfonia,6,851,1767,845,1761,283927,286539,1.144832,0.512164,1.143811,0.108791,0.193233,-0.990847,1.143323,0.511489,False,False,False,False,False
28183,L04AB02_Infliximab,Disfonia,40,10490,1767,10450,1727,274322,286539,0.608012,0.444129,0.609507,9.841278,-0.693513,-1.155696,0.618346,0.451678,False,False,False,False,False
36873,L04AB04_Adalimumab,Disfonia,3,1519,1767,1516,1764,283256,286539,0.317762,0.102270,0.319110,4.378079,-1.642658,-3.311586,0.320266,0.103075,False,False,False,False,False

### Intolerância láctea

In [73]:
tabela.query('REACAO_PT == "Intolerância láctea"')

,ATC_LEVEL_5,REACAO_PT,a,n_drug,n_evt,b,c,d,N_total,ROR,ROR_LCL95,PRR,CHI2,IC,IC025,EBGM,EBGM05,signal_ROR,signal_PRR,signal_BCPNN,signal_EBGM,signal
48437,L04AB05_Certolizumab Pegol,Intolerância láctea,33,1177,51,1144,18,285344,286539,457.282051,256.739134,444.489097,5154.640195,7.299442,6.649384,157.525563,88.442082,True,True,True,True,True
83197,L04AF03_Upadacitinib,Intolerância láctea,3,1023,51,1020,48,285468,286539,17.491912,5.439495,17.443548,43.774971,4.042319,2.325778,16.476281,5.123662,True,True,True,True,True
39747,L04AB04_Adalimumab,Intolerância láctea,3,1519,51,1516,48,284972,286539,11.748516,3.655388,11.727288,27.710981,3.472003,1.756236,11.096271,3.452451,True,True,True,True,True
57127,L04AB06_Golimumab,Intolerância láctea,5,3723,51,3718,46,282770,286539,8.266775,3.282908,8.257016,28.769213,2.915625,1.562648,7.545544,2.996492,True,True,True,True,True
91887,Outros,Intolerância láctea,3,264340,51,264337,48,22151,286539,0.005237,0.001631,0.005249,532.412351,-3.971126,-5.685304,0.063763,0.019859,False,False,False,False,False

# **9️⃣ Implementação**

# **Estágio 10: Feedback**