# ⭐ `fat_not_reacoes` 

**Objetivo**  
Construir a tabela fato **`fat_not_reacoes`** (Notificações × Rea oes) na camada **Gold** a partir de insumos **Silver**

In [7]:
%run ../config/bootstrap.py

import pandas as pd
import numpy as np
from pathlib import Path
from utils import get_project_root

In [8]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [9]:
path = Path(project_root) / "data/01_bronze/Reacoes/Reacoes.parquet"
bronze = pd.read_parquet(path)     
bronze.head()

,IDENTIFICACAO_NOTIFICACAO,REACAO_EVTO_ADVERSO_MEDDRA_LLT,PT,HLT,HLGT,SOC,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,GRAVIDADE,DESFECHO,ATUALIZADO
0,BR-ANVISA-300000004,Coceira,Prurido,Prurido NCO,Quadros clínicos epidérmicos e dérmicos,Distúrbios dos tecidos cutâneos e subcutâneos,None,None,3 dia,Não,None,Recuperado/Resolvido,2025-11-17
1,BR-ANVISA-300000005,Edema periorbital,Edema periorbital,Distúrbios oculares NCO,Transtornos oculares NCO,Distúrbios oculares,20181122,20181122,None,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
2,BR-ANVISA-300000007,Exantema alérgico,Dermatite alérgica,Dermatite e eczema,Quadros clínicos epidérmicos e dérmicos,Distúrbios dos tecidos cutâneos e subcutâneos,20181115,None,2 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
3,BR-ANVISA-300000008,Flebite,Flebite,Flebite NCO,Infecções e inflamações vasculares,Distúrbios vasculares,20181025,None,5 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
4,BR-ANVISA-300000010,Parestesia,Parestesia,Parestesias e disestesias,Distúrbios neurológicos NCO,Distúrbios do sistema nervoso,201508,201508,None,Sim,Hospitalização/Prolongamento de hospitalização,Recuperado/Resolvido,2025-11-17

In [10]:
bronze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815877 entries, 0 to 815876
Data columns (total 13 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   IDENTIFICACAO_NOTIFICACAO       815877 non-null  object
 1   REACAO_EVTO_ADVERSO_MEDDRA_LLT  799589 non-null  object
 2   PT                              799589 non-null  object
 3   HLT                             799589 non-null  object
 4   HLGT                            799589 non-null  object
 5   SOC                             799589 non-null  object
 6   DATA_INICIO_HORA                456715 non-null  object
 7   DATA_FINAL_HORA                 232180 non-null  object
 8   DURACAO                         127726 non-null  object
 9   GRAVE                           642796 non-null  object
 10  GRAVIDADE                       267804 non-null  object
 11  DESFECHO                        680205 non-null  object
 12  ATUALIZADO                      815877 non-null  object
dtypes: object(13)
memory usage: 80.9+ MB

# 🥈 Silver

normalized data, medium quality

## hist_fat_notificacoes_reacoes

In [11]:
path = Path(project_root) / "data/03_gold/dim_soc/dim_soc.csv"
dim_soc = pd.read_csv(path)  
dim_soc.head()

,PK_SOC,SOC,HLGT,HLT,PT,REACAO_EVTO_ADVERSO_MEDDRA_LLT
0,0,Circunstâncias sociais,Fatores relacionados ao gênero,Circunstâncias relacionadas à gravidez,Amamentação,Amamentação
1,1,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Abstinência sexual,Abstinência sexual
2,2,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Atividade sexual aumentada,Atividade sexual aumentada
3,3,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Não consumação,Não consumação
4,4,Circunstâncias sociais,Fatores relacionados à idade,Questões relacionadas à idade,Bebê,Neonato

In [12]:
path = Path(project_root) / "data/01_bronze/Reacoes/Reacoes.parquet"
silver = pd.read_parquet(path)  
silver.head()

,IDENTIFICACAO_NOTIFICACAO,REACAO_EVTO_ADVERSO_MEDDRA_LLT,PT,HLT,HLGT,SOC,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,GRAVIDADE,DESFECHO,ATUALIZADO
0,BR-ANVISA-300000004,Coceira,Prurido,Prurido NCO,Quadros clínicos epidérmicos e dérmicos,Distúrbios dos tecidos cutâneos e subcutâneos,None,None,3 dia,Não,None,Recuperado/Resolvido,2025-11-17
1,BR-ANVISA-300000005,Edema periorbital,Edema periorbital,Distúrbios oculares NCO,Transtornos oculares NCO,Distúrbios oculares,20181122,20181122,None,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
2,BR-ANVISA-300000007,Exantema alérgico,Dermatite alérgica,Dermatite e eczema,Quadros clínicos epidérmicos e dérmicos,Distúrbios dos tecidos cutâneos e subcutâneos,20181115,None,2 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
3,BR-ANVISA-300000008,Flebite,Flebite,Flebite NCO,Infecções e inflamações vasculares,Distúrbios vasculares,20181025,None,5 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido,2025-11-17
4,BR-ANVISA-300000010,Parestesia,Parestesia,Parestesias e disestesias,Distúrbios neurológicos NCO,Distúrbios do sistema nervoso,201508,201508,None,Sim,Hospitalização/Prolongamento de hospitalização,Recuperado/Resolvido,2025-11-17

In [13]:
silver.columns

Index(['IDENTIFICACAO_NOTIFICACAO', 'REACAO_EVTO_ADVERSO_MEDDRA_LLT', 'PT',
       'HLT', 'HLGT', 'SOC', 'DATA_INICIO_HORA', 'DATA_FINAL_HORA', 'DURACAO',
       'GRAVE', 'GRAVIDADE', 'DESFECHO', 'ATUALIZADO'],
      dtype='object')

In [14]:
# Supondo que no DataFrame `norm` as colunas tenham os mesmos nomes
silver = bronze.merge(
    dim_soc,
    how='left',
    left_on=['SOC', 'HLGT', 'HLT', 'PT', 'REACAO_EVTO_ADVERSO_MEDDRA_LLT'],
    right_on=['SOC', 'HLGT', 'HLT', 'PT', 'REACAO_EVTO_ADVERSO_MEDDRA_LLT']
)


silver["DATA_INICIO_HORA"] = pd.to_datetime(silver["DATA_INICIO_HORA"], format='%Y%m%d', errors='coerce')
silver["DATA_FINAL_HORA"] = pd.to_datetime(silver["DATA_FINAL_HORA"], format='%Y%m%d', errors='coerce')

silver = silver[['IDENTIFICACAO_NOTIFICACAO', 'PK_SOC', 'DATA_INICIO_HORA', 'DATA_FINAL_HORA', 'DURACAO','GRAVE', 'GRAVIDADE', 'DESFECHO']]
 
silver.head()

,IDENTIFICACAO_NOTIFICACAO,PK_SOC,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,GRAVIDADE,DESFECHO
0,BR-ANVISA-300000004,4113,NaT,NaT,3 dia,Não,None,Recuperado/Resolvido
1,BR-ANVISA-300000005,9106,2018-11-22,2018-11-22,None,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido
2,BR-ANVISA-300000007,3902,2018-11-15,NaT,2 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido
3,BR-ANVISA-300000008,11410,2018-10-25,NaT,5 dia,Sim,Outro efeito clinicamente significativo,Recuperado/Resolvido
4,BR-ANVISA-300000010,1993,NaT,NaT,None,Sim,Hospitalização/Prolongamento de hospitalização,Recuperado/Resolvido

In [15]:
silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815877 entries, 0 to 815876
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   IDENTIFICACAO_NOTIFICACAO  815877 non-null  object
 1   PK_SOC                     815877 non-null  int64
 2   DATA_INICIO_HORA           347696 non-null  datetime64[ns]
 3   DATA_FINAL_HORA            189475 non-null  datetime64[ns]
 4   DURACAO                    127726 non-null  object
 5   GRAVE                      642796 non-null  object
 6   GRAVIDADE                  267804 non-null  object
 7   DESFECHO                   680205 non-null  object
dtypes: datetime64[ns](2), int64(1), object(5)
memory usage: 49.8+ MB

In [19]:
silver.to_parquet(Path(project_root) / "data/02_silver/hist_fat_notificacoes_reacoes/hist_fat_notificacoes_reacoes.parquet", index=False)

# 🥇 Gold

In [18]:
fat = silver.copy()
fat.to_parquet(Path(project_root) / "data/03_gold/fat_notificacoes_reacoes/fat_notificacoes_reacoes.parquet", index=False)